/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Money,
  Money$inboundSchema,
  Money$Outbound,
  Money$outboundSchema,
} from "./money.js";
import {
  PrimaryNetworkAssetType,
  PrimaryNetworkAssetType$inboundSchema,
  PrimaryNetworkAssetType$outboundSchema,
} from "./primarynetworkassettype.js";

export type AssetWithPriceInfo = {
  /**
   * Unique ID for an asset.
   */
  assetId: string;
  /**
   * Name of this asset.
   */
  name: string;
  /**
   * Symbol for this asset (max 4 characters).
   */
  symbol: string;
  /**
   * Denomination of this asset to represent fungibility.
   */
  denomination: number;
  /**
   * Type of asset like SECP256K1 or NFT.
   */
  type: PrimaryNetworkAssetType;
  /**
   * Amount of the asset.
   */
  amount: string;
  /**
   * The historical asset price at the time the reward was granted, if available. Note, this is only provided if the reward occured more than 24 hours ago.
   */
  historicalPrice?: Money | undefined;
};

/** @internal */
export const AssetWithPriceInfo$inboundSchema: z.ZodType<
  AssetWithPriceInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$inboundSchema,
  amount: z.string(),
  historicalPrice: Money$inboundSchema.optional(),
});
/** @internal */
export type AssetWithPriceInfo$Outbound = {
  assetId: string;
  name: string;
  symbol: string;
  denomination: number;
  type: string;
  amount: string;
  historicalPrice?: Money$Outbound | undefined;
};

/** @internal */
export const AssetWithPriceInfo$outboundSchema: z.ZodType<
  AssetWithPriceInfo$Outbound,
  z.ZodTypeDef,
  AssetWithPriceInfo
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$outboundSchema,
  amount: z.string(),
  historicalPrice: Money$outboundSchema.optional(),
});

export function assetWithPriceInfoToJSON(
  assetWithPriceInfo: AssetWithPriceInfo,
): string {
  return JSON.stringify(
    AssetWithPriceInfo$outboundSchema.parse(assetWithPriceInfo),
  );
}
export function assetWithPriceInfoFromJSON(
  jsonString: string,
): SafeParseResult<AssetWithPriceInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssetWithPriceInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssetWithPriceInfo' from JSON`,
  );
}
