/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * `renewing` = will roll into another cycle; `exiting` = graceful exit armed, this is the final cycle. Not an outcome - the cycle can still abort on reward eligibility.
 */
export const AutoRenewState = {
  Renewing: "renewing",
  Exiting: "exiting",
  Exited: "exited",
  Aborted: "aborted",
} as const;
/**
 * `renewing` = will roll into another cycle; `exiting` = graceful exit armed, this is the final cycle. Not an outcome - the cycle can still abort on reward eligibility.
 */
export type AutoRenewState = ClosedEnum<typeof AutoRenewState>;

/** @internal */
export const AutoRenewState$inboundSchema: z.ZodNativeEnum<
  typeof AutoRenewState
> = z.nativeEnum(AutoRenewState);
/** @internal */
export const AutoRenewState$outboundSchema: z.ZodNativeEnum<
  typeof AutoRenewState
> = AutoRenewState$inboundSchema;
