/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of balance to monitor
 */
export const CommonBalanceType = {
  UnlockedUnstaked: "unlockedUnstaked",
  UnlockedStaked: "unlockedStaked",
  LockedPlatform: "lockedPlatform",
  LockedStakeable: "lockedStakeable",
  LockedStaked: "lockedStaked",
  PendingStaked: "pendingStaked",
  Unlocked: "unlocked",
  Locked: "locked",
  AtomicMemoryUnlocked: "atomicMemoryUnlocked",
  AtomicMemoryLocked: "atomicMemoryLocked",
} as const;
/**
 * Type of balance to monitor
 */
export type CommonBalanceType = ClosedEnum<typeof CommonBalanceType>;

/** @internal */
export const CommonBalanceType$inboundSchema: z.ZodNativeEnum<
  typeof CommonBalanceType
> = z.nativeEnum(CommonBalanceType);
/** @internal */
export const CommonBalanceType$outboundSchema: z.ZodNativeEnum<
  typeof CommonBalanceType
> = CommonBalanceType$inboundSchema;
