/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BlsCredentials,
  BlsCredentials$inboundSchema,
  BlsCredentials$Outbound,
  BlsCredentials$outboundSchema,
} from "./blscredentials.js";
import {
  Rewards,
  Rewards$inboundSchema,
  Rewards$Outbound,
  Rewards$outboundSchema,
} from "./rewards.js";

export type CompletedValidatorDetails = {
  txHash: string;
  nodeId: string;
  subnetId: string;
  amountStaked: string;
  /**
   * The percentage of total estimated delegator rewards allocated to validator nodes for supporting delegations.
   */
  delegationFee?: string | undefined;
  startTimestamp: number;
  endTimestamp: number;
  /**
   * Present for AddPermissionlessValidatorTx
   */
  blsCredentials?: BlsCredentials | undefined;
  delegatorCount: number;
  amountDelegated?: string | undefined;
  rewards: Rewards;
  validationStatus: "completed";
};

/** @internal */
export const CompletedValidatorDetails$inboundSchema: z.ZodType<
  CompletedValidatorDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  txHash: z.string(),
  nodeId: z.string(),
  subnetId: z.string(),
  amountStaked: z.string(),
  delegationFee: z.string().optional(),
  startTimestamp: z.number(),
  endTimestamp: z.number(),
  blsCredentials: BlsCredentials$inboundSchema.optional(),
  delegatorCount: z.number(),
  amountDelegated: z.string().optional(),
  rewards: Rewards$inboundSchema,
  validationStatus: z.literal("completed"),
});
/** @internal */
export type CompletedValidatorDetails$Outbound = {
  txHash: string;
  nodeId: string;
  subnetId: string;
  amountStaked: string;
  delegationFee?: string | undefined;
  startTimestamp: number;
  endTimestamp: number;
  blsCredentials?: BlsCredentials$Outbound | undefined;
  delegatorCount: number;
  amountDelegated?: string | undefined;
  rewards: Rewards$Outbound;
  validationStatus: "completed";
};

/** @internal */
export const CompletedValidatorDetails$outboundSchema: z.ZodType<
  CompletedValidatorDetails$Outbound,
  z.ZodTypeDef,
  CompletedValidatorDetails
> = z.object({
  txHash: z.string(),
  nodeId: z.string(),
  subnetId: z.string(),
  amountStaked: z.string(),
  delegationFee: z.string().optional(),
  startTimestamp: z.number(),
  endTimestamp: z.number(),
  blsCredentials: BlsCredentials$outboundSchema.optional(),
  delegatorCount: z.number(),
  amountDelegated: z.string().optional(),
  rewards: Rewards$outboundSchema,
  validationStatus: z.literal("completed"),
});

export function completedValidatorDetailsToJSON(
  completedValidatorDetails: CompletedValidatorDetails,
): string {
  return JSON.stringify(
    CompletedValidatorDetails$outboundSchema.parse(completedValidatorDetails),
  );
}
export function completedValidatorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<CompletedValidatorDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletedValidatorDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletedValidatorDetails' from JSON`,
  );
}
