/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ContractDeploymentDetails = {
  txHash: string;
  /**
   * The address that initiated the transaction which deployed this contract.
   */
  deployerAddress: string;
  /**
   * The contract address which deployed this contract via smart contract. This field is only populated when the contract was deployed as part of smart contract execution.
   */
  deployerContractAddress?: string | undefined;
};

/** @internal */
export const ContractDeploymentDetails$inboundSchema: z.ZodType<
  ContractDeploymentDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  txHash: z.string(),
  deployerAddress: z.string(),
  deployerContractAddress: z.string().optional(),
});
/** @internal */
export type ContractDeploymentDetails$Outbound = {
  txHash: string;
  deployerAddress: string;
  deployerContractAddress?: string | undefined;
};

/** @internal */
export const ContractDeploymentDetails$outboundSchema: z.ZodType<
  ContractDeploymentDetails$Outbound,
  z.ZodTypeDef,
  ContractDeploymentDetails
> = z.object({
  txHash: z.string(),
  deployerAddress: z.string(),
  deployerContractAddress: z.string().optional(),
});

export function contractDeploymentDetailsToJSON(
  contractDeploymentDetails: ContractDeploymentDetails,
): string {
  return JSON.stringify(
    ContractDeploymentDetails$outboundSchema.parse(contractDeploymentDetails),
  );
}
export function contractDeploymentDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ContractDeploymentDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContractDeploymentDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContractDeploymentDetails' from JSON`,
  );
}
