/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * ISO 4217 currency code.
 */
export const CurrencyCode = {
  Usd: "usd",
  Eur: "eur",
  Aud: "aud",
  Cad: "cad",
  Chf: "chf",
  Clp: "clp",
  Cny: "cny",
  Czk: "czk",
  Dkk: "dkk",
  Gbp: "gbp",
  Hkd: "hkd",
  Huf: "huf",
  Jpy: "jpy",
  Nzd: "nzd",
} as const;
/**
 * ISO 4217 currency code.
 */
export type CurrencyCode = ClosedEnum<typeof CurrencyCode>;

/** @internal */
export const CurrencyCode$inboundSchema: z.ZodNativeEnum<typeof CurrencyCode> =
  z.nativeEnum(CurrencyCode);
/** @internal */
export const CurrencyCode$outboundSchema: z.ZodNativeEnum<typeof CurrencyCode> =
  CurrencyCode$inboundSchema;
