/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AutoRenewState,
  AutoRenewState$inboundSchema,
  AutoRenewState$outboundSchema,
} from "./autorenewstate.js";

export type CurrentAutoRenewedCycle = {
  /**
   * 1-based sequence within this position. The settled cycles in `cycles` run from 1 to this value minus one.
   */
  cycleIndex: number;
  /**
   * The originating AddAutoRenewedValidatorTx for this position.
   */
  stakingTxHash: string;
  /**
   * This cycle's window start, unix seconds.
   */
  startTimestamp: number;
  /**
   * This cycle's window end, unix seconds. A delegation into this validator must end within it.
   */
  endTimestamp: number;
  /**
   * Weight bonded for this cycle in nAVAX. Rewards compound into weight only at settlement, so this is stable for the whole cycle.
   */
  weightAtCycleStart: string;
  /**
   * Forecast validation reward for the **whole** cycle in nAVAX, minted at cycle start. Not an amount earned so far, and not comparable to a settled cycle's `grossValidationReward` until this cycle settles. Do not add it to sums over `cycles`.
   */
  projectedValidationReward: string;
  /**
   * Delegatee commission already accrued this cycle, in nAVAX, from delegations that have settled within it. Unlike the validation reward this is realised, not forecast; delegations still running contribute nothing yet.
   */
  accruedDelegateeReward: string;
  /**
   * 0-100. The share that will apply when this cycle settles. A SetAutoRenewedValidatorConfigTx mid-cycle changes it, so it is not final until settlement.
   */
  autoCompoundSharePercent: number;
  /**
   * `renewing` = will roll into another cycle; `exiting` = graceful exit armed, this is the final cycle. Not an outcome - the cycle can still abort on reward eligibility.
   */
  state: AutoRenewState;
  /**
   * Delegations overlapping this cycle's window.
   */
  delegatorCount: number;
  /**
   * Total weight of those delegations in nAVAX. Not included in `weightAtCycleStart`.
   */
  amountDelegated: string;
};

/** @internal */
export const CurrentAutoRenewedCycle$inboundSchema: z.ZodType<
  CurrentAutoRenewedCycle,
  z.ZodTypeDef,
  unknown
> = z.object({
  cycleIndex: z.number(),
  stakingTxHash: z.string(),
  startTimestamp: z.number(),
  endTimestamp: z.number(),
  weightAtCycleStart: z.string(),
  projectedValidationReward: z.string(),
  accruedDelegateeReward: z.string(),
  autoCompoundSharePercent: z.number(),
  state: AutoRenewState$inboundSchema,
  delegatorCount: z.number(),
  amountDelegated: z.string(),
});
/** @internal */
export type CurrentAutoRenewedCycle$Outbound = {
  cycleIndex: number;
  stakingTxHash: string;
  startTimestamp: number;
  endTimestamp: number;
  weightAtCycleStart: string;
  projectedValidationReward: string;
  accruedDelegateeReward: string;
  autoCompoundSharePercent: number;
  state: string;
  delegatorCount: number;
  amountDelegated: string;
};

/** @internal */
export const CurrentAutoRenewedCycle$outboundSchema: z.ZodType<
  CurrentAutoRenewedCycle$Outbound,
  z.ZodTypeDef,
  CurrentAutoRenewedCycle
> = z.object({
  cycleIndex: z.number(),
  stakingTxHash: z.string(),
  startTimestamp: z.number(),
  endTimestamp: z.number(),
  weightAtCycleStart: z.string(),
  projectedValidationReward: z.string(),
  accruedDelegateeReward: z.string(),
  autoCompoundSharePercent: z.number(),
  state: AutoRenewState$outboundSchema,
  delegatorCount: z.number(),
  amountDelegated: z.string(),
});

export function currentAutoRenewedCycleToJSON(
  currentAutoRenewedCycle: CurrentAutoRenewedCycle,
): string {
  return JSON.stringify(
    CurrentAutoRenewedCycle$outboundSchema.parse(currentAutoRenewedCycle),
  );
}
export function currentAutoRenewedCycleFromJSON(
  jsonString: string,
): SafeParseResult<CurrentAutoRenewedCycle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentAutoRenewedCycle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentAutoRenewedCycle' from JSON`,
  );
}
