/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TeleporterDestinationTransaction,
  TeleporterDestinationTransaction$inboundSchema,
  TeleporterDestinationTransaction$Outbound,
  TeleporterDestinationTransaction$outboundSchema,
} from "./teleporterdestinationtransaction.js";
import {
  TeleporterReceipt,
  TeleporterReceipt$inboundSchema,
  TeleporterReceipt$Outbound,
  TeleporterReceipt$outboundSchema,
} from "./teleporterreceipt.js";
import {
  TeleporterRewardDetails,
  TeleporterRewardDetails$inboundSchema,
  TeleporterRewardDetails$Outbound,
  TeleporterRewardDetails$outboundSchema,
} from "./teleporterrewarddetails.js";
import {
  TeleporterSourceTransaction,
  TeleporterSourceTransaction$inboundSchema,
  TeleporterSourceTransaction$Outbound,
  TeleporterSourceTransaction$outboundSchema,
} from "./teleportersourcetransaction.js";

export type DeliveredTeleporterMessage = {
  messageId: string;
  teleporterContractAddress: string;
  sourceBlockchainId: string;
  destinationBlockchainId: string;
  sourceEvmChainId: string;
  destinationEvmChainId: string;
  messageNonce: string;
  from: string;
  to: string;
  data?: string | undefined;
  messageExecuted: boolean;
  receipts: Array<TeleporterReceipt>;
  receiptDelivered: boolean;
  rewardDetails: TeleporterRewardDetails;
  sourceTransaction: TeleporterSourceTransaction;
  destinationTransaction: TeleporterDestinationTransaction;
  status: "delivered";
};

/** @internal */
export const DeliveredTeleporterMessage$inboundSchema: z.ZodType<
  DeliveredTeleporterMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: z.string(),
  teleporterContractAddress: z.string(),
  sourceBlockchainId: z.string(),
  destinationBlockchainId: z.string(),
  sourceEvmChainId: z.string(),
  destinationEvmChainId: z.string(),
  messageNonce: z.string(),
  from: z.string(),
  to: z.string(),
  data: z.string().optional(),
  messageExecuted: z.boolean(),
  receipts: z.array(TeleporterReceipt$inboundSchema),
  receiptDelivered: z.boolean(),
  rewardDetails: TeleporterRewardDetails$inboundSchema,
  sourceTransaction: TeleporterSourceTransaction$inboundSchema,
  destinationTransaction: TeleporterDestinationTransaction$inboundSchema,
  status: z.literal("delivered"),
});
/** @internal */
export type DeliveredTeleporterMessage$Outbound = {
  messageId: string;
  teleporterContractAddress: string;
  sourceBlockchainId: string;
  destinationBlockchainId: string;
  sourceEvmChainId: string;
  destinationEvmChainId: string;
  messageNonce: string;
  from: string;
  to: string;
  data?: string | undefined;
  messageExecuted: boolean;
  receipts: Array<TeleporterReceipt$Outbound>;
  receiptDelivered: boolean;
  rewardDetails: TeleporterRewardDetails$Outbound;
  sourceTransaction: TeleporterSourceTransaction$Outbound;
  destinationTransaction: TeleporterDestinationTransaction$Outbound;
  status: "delivered";
};

/** @internal */
export const DeliveredTeleporterMessage$outboundSchema: z.ZodType<
  DeliveredTeleporterMessage$Outbound,
  z.ZodTypeDef,
  DeliveredTeleporterMessage
> = z.object({
  messageId: z.string(),
  teleporterContractAddress: z.string(),
  sourceBlockchainId: z.string(),
  destinationBlockchainId: z.string(),
  sourceEvmChainId: z.string(),
  destinationEvmChainId: z.string(),
  messageNonce: z.string(),
  from: z.string(),
  to: z.string(),
  data: z.string().optional(),
  messageExecuted: z.boolean(),
  receipts: z.array(TeleporterReceipt$outboundSchema),
  receiptDelivered: z.boolean(),
  rewardDetails: TeleporterRewardDetails$outboundSchema,
  sourceTransaction: TeleporterSourceTransaction$outboundSchema,
  destinationTransaction: TeleporterDestinationTransaction$outboundSchema,
  status: z.literal("delivered"),
});

export function deliveredTeleporterMessageToJSON(
  deliveredTeleporterMessage: DeliveredTeleporterMessage,
): string {
  return JSON.stringify(
    DeliveredTeleporterMessage$outboundSchema.parse(deliveredTeleporterMessage),
  );
}
export function deliveredTeleporterMessageFromJSON(
  jsonString: string,
): SafeParseResult<DeliveredTeleporterMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeliveredTeleporterMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeliveredTeleporterMessage' from JSON`,
  );
}
