/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Erc721Token,
  Erc721Token$inboundSchema,
  Erc721Token$Outbound,
  Erc721Token$outboundSchema,
} from "./erc721token.js";
import {
  RichAddress,
  RichAddress$inboundSchema,
  RichAddress$Outbound,
  RichAddress$outboundSchema,
} from "./richaddress.js";

export type Erc721Transfer = {
  /**
   * The block number on the chain.
   */
  blockNumber: string;
  /**
   * The block creation (proposal) timestamp in seconds
   */
  blockTimestamp: number;
  /**
   * The block creation (proposal) timestamp in milliseconds. Available only after Granite upgrade.
   */
  blockTimestampMilliseconds?: number | undefined;
  /**
   * The block hash identifier.
   */
  blockHash: string;
  /**
   * The transaction hash identifier.
   */
  txHash: string;
  from: RichAddress;
  to: RichAddress;
  logIndex: number;
  erc721Token: Erc721Token;
};

/** @internal */
export const Erc721Transfer$inboundSchema: z.ZodType<
  Erc721Transfer,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockNumber: z.string(),
  blockTimestamp: z.number(),
  blockTimestampMilliseconds: z.number().optional(),
  blockHash: z.string(),
  txHash: z.string(),
  from: RichAddress$inboundSchema,
  to: RichAddress$inboundSchema,
  logIndex: z.number(),
  erc721Token: Erc721Token$inboundSchema,
});
/** @internal */
export type Erc721Transfer$Outbound = {
  blockNumber: string;
  blockTimestamp: number;
  blockTimestampMilliseconds?: number | undefined;
  blockHash: string;
  txHash: string;
  from: RichAddress$Outbound;
  to: RichAddress$Outbound;
  logIndex: number;
  erc721Token: Erc721Token$Outbound;
};

/** @internal */
export const Erc721Transfer$outboundSchema: z.ZodType<
  Erc721Transfer$Outbound,
  z.ZodTypeDef,
  Erc721Transfer
> = z.object({
  blockNumber: z.string(),
  blockTimestamp: z.number(),
  blockTimestampMilliseconds: z.number().optional(),
  blockHash: z.string(),
  txHash: z.string(),
  from: RichAddress$outboundSchema,
  to: RichAddress$outboundSchema,
  logIndex: z.number(),
  erc721Token: Erc721Token$outboundSchema,
});

export function erc721TransferToJSON(erc721Transfer: Erc721Transfer): string {
  return JSON.stringify(Erc721Transfer$outboundSchema.parse(erc721Transfer));
}
export function erc721TransferFromJSON(
  jsonString: string,
): SafeParseResult<Erc721Transfer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Erc721Transfer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Erc721Transfer' from JSON`,
  );
}
