/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EvmGenesisAllocDto = {
  /**
   * Account balance in hex format
   */
  balance?: string | undefined;
  /**
   * Contract bytecode in hex format
   */
  code?: string | undefined;
  /**
   * Contract storage slots
   */
  storage?: { [k: string]: string } | undefined;
};

/** @internal */
export const EvmGenesisAllocDto$inboundSchema: z.ZodType<
  EvmGenesisAllocDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  balance: z.string().optional(),
  code: z.string().optional(),
  storage: z.record(z.string()).optional(),
});
/** @internal */
export type EvmGenesisAllocDto$Outbound = {
  balance?: string | undefined;
  code?: string | undefined;
  storage?: { [k: string]: string } | undefined;
};

/** @internal */
export const EvmGenesisAllocDto$outboundSchema: z.ZodType<
  EvmGenesisAllocDto$Outbound,
  z.ZodTypeDef,
  EvmGenesisAllocDto
> = z.object({
  balance: z.string().optional(),
  code: z.string().optional(),
  storage: z.record(z.string()).optional(),
});

export function evmGenesisAllocDtoToJSON(
  evmGenesisAllocDto: EvmGenesisAllocDto,
): string {
  return JSON.stringify(
    EvmGenesisAllocDto$outboundSchema.parse(evmGenesisAllocDto),
  );
}
export function evmGenesisAllocDtoFromJSON(
  jsonString: string,
): SafeParseResult<EvmGenesisAllocDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvmGenesisAllocDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmGenesisAllocDto' from JSON`,
  );
}
