/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EvmGenesisWarpConfigDto = {
  /**
   * Block timestamp
   */
  blockTimestamp?: number | undefined;
  /**
   * Quorum numerator
   */
  quorumNumerator?: number | undefined;
  /**
   * Require primary network signers
   */
  requirePrimaryNetworkSigners?: boolean | undefined;
};

/** @internal */
export const EvmGenesisWarpConfigDto$inboundSchema: z.ZodType<
  EvmGenesisWarpConfigDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockTimestamp: z.number().optional(),
  quorumNumerator: z.number().optional(),
  requirePrimaryNetworkSigners: z.boolean().optional(),
});
/** @internal */
export type EvmGenesisWarpConfigDto$Outbound = {
  blockTimestamp?: number | undefined;
  quorumNumerator?: number | undefined;
  requirePrimaryNetworkSigners?: boolean | undefined;
};

/** @internal */
export const EvmGenesisWarpConfigDto$outboundSchema: z.ZodType<
  EvmGenesisWarpConfigDto$Outbound,
  z.ZodTypeDef,
  EvmGenesisWarpConfigDto
> = z.object({
  blockTimestamp: z.number().optional(),
  quorumNumerator: z.number().optional(),
  requirePrimaryNetworkSigners: z.boolean().optional(),
});

export function evmGenesisWarpConfigDtoToJSON(
  evmGenesisWarpConfigDto: EvmGenesisWarpConfigDto,
): string {
  return JSON.stringify(
    EvmGenesisWarpConfigDto$outboundSchema.parse(evmGenesisWarpConfigDto),
  );
}
export function evmGenesisWarpConfigDtoFromJSON(
  jsonString: string,
): SafeParseResult<EvmGenesisWarpConfigDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvmGenesisWarpConfigDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmGenesisWarpConfigDto' from JSON`,
  );
}
