/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EvmGenesisAllowListConfigDto = {
  /**
   * Block timestamp
   */
  blockTimestamp?: number | undefined;
  /**
   * Admin addresses
   */
  adminAddresses?: Array<string> | undefined;
  /**
   * Manager addresses
   */
  managerAddresses?: Array<string> | undefined;
  /**
   * Enabled addresses
   */
  enabledAddresses?: Array<string> | undefined;
};

/** @internal */
export const EvmGenesisAllowListConfigDto$inboundSchema: z.ZodType<
  EvmGenesisAllowListConfigDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockTimestamp: z.number().optional(),
  adminAddresses: z.array(z.string()).optional(),
  managerAddresses: z.array(z.string()).optional(),
  enabledAddresses: z.array(z.string()).optional(),
});
/** @internal */
export type EvmGenesisAllowListConfigDto$Outbound = {
  blockTimestamp?: number | undefined;
  adminAddresses?: Array<string> | undefined;
  managerAddresses?: Array<string> | undefined;
  enabledAddresses?: Array<string> | undefined;
};

/** @internal */
export const EvmGenesisAllowListConfigDto$outboundSchema: z.ZodType<
  EvmGenesisAllowListConfigDto$Outbound,
  z.ZodTypeDef,
  EvmGenesisAllowListConfigDto
> = z.object({
  blockTimestamp: z.number().optional(),
  adminAddresses: z.array(z.string()).optional(),
  managerAddresses: z.array(z.string()).optional(),
  enabledAddresses: z.array(z.string()).optional(),
});

export function evmGenesisAllowListConfigDtoToJSON(
  evmGenesisAllowListConfigDto: EvmGenesisAllowListConfigDto,
): string {
  return JSON.stringify(
    EvmGenesisAllowListConfigDto$outboundSchema.parse(
      evmGenesisAllowListConfigDto,
    ),
  );
}
export function evmGenesisAllowListConfigDtoFromJSON(
  jsonString: string,
): SafeParseResult<EvmGenesisAllowListConfigDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvmGenesisAllowListConfigDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmGenesisAllowListConfigDto' from JSON`,
  );
}
