/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetEvmBlockResponse = {
  /**
   * The EVM chain ID on which the block was created.
   */
  chainId: string;
  /**
   * The block number on the chain.
   */
  blockNumber: string;
  /**
   * The block creation (proposal) timestamp in seconds
   */
  blockTimestamp: number;
  /**
   * The block creation (proposal) timestamp in milliseconds. Available only after Granite upgrade.
   */
  blockTimestampMilliseconds?: number | undefined;
  /**
   * Minimum block delay in milliseconds. Available only after Granite upgrade.
   */
  blockMinDelayExcess?: number | undefined;
  /**
   * The block hash identifier.
   */
  blockHash: string;
  /**
   * The number of evm transactions in the block.
   */
  txCount: number;
  /**
   * The base gas fee for a transaction to be included in the block.
   */
  baseFee: string;
  /**
   * The gas used for transactions in the block.
   */
  gasUsed: string;
  /**
   * The total gas limit set for transactions in the block.
   */
  gasLimit: string;
  gasCost: string;
  /**
   * The hash of the parent block.
   */
  parentHash: string;
  /**
   * The amount of fees spent/burned for transactions in the block.
   */
  feesSpent: string;
  /**
   * The cumulative number of transactions for the chain including this block.
   */
  cumulativeTransactions: string;
};

/** @internal */
export const GetEvmBlockResponse$inboundSchema: z.ZodType<
  GetEvmBlockResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainId: z.string(),
  blockNumber: z.string(),
  blockTimestamp: z.number(),
  blockTimestampMilliseconds: z.number().optional(),
  blockMinDelayExcess: z.number().optional(),
  blockHash: z.string(),
  txCount: z.number(),
  baseFee: z.string(),
  gasUsed: z.string(),
  gasLimit: z.string(),
  gasCost: z.string(),
  parentHash: z.string(),
  feesSpent: z.string(),
  cumulativeTransactions: z.string(),
});
/** @internal */
export type GetEvmBlockResponse$Outbound = {
  chainId: string;
  blockNumber: string;
  blockTimestamp: number;
  blockTimestampMilliseconds?: number | undefined;
  blockMinDelayExcess?: number | undefined;
  blockHash: string;
  txCount: number;
  baseFee: string;
  gasUsed: string;
  gasLimit: string;
  gasCost: string;
  parentHash: string;
  feesSpent: string;
  cumulativeTransactions: string;
};

/** @internal */
export const GetEvmBlockResponse$outboundSchema: z.ZodType<
  GetEvmBlockResponse$Outbound,
  z.ZodTypeDef,
  GetEvmBlockResponse
> = z.object({
  chainId: z.string(),
  blockNumber: z.string(),
  blockTimestamp: z.number(),
  blockTimestampMilliseconds: z.number().optional(),
  blockMinDelayExcess: z.number().optional(),
  blockHash: z.string(),
  txCount: z.number(),
  baseFee: z.string(),
  gasUsed: z.string(),
  gasLimit: z.string(),
  gasCost: z.string(),
  parentHash: z.string(),
  feesSpent: z.string(),
  cumulativeTransactions: z.string(),
});

export function getEvmBlockResponseToJSON(
  getEvmBlockResponse: GetEvmBlockResponse,
): string {
  return JSON.stringify(
    GetEvmBlockResponse$outboundSchema.parse(getEvmBlockResponse),
  );
}
export function getEvmBlockResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEvmBlockResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEvmBlockResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEvmBlockResponse' from JSON`,
  );
}
