/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Money,
  Money$inboundSchema,
  Money$Outbound,
  Money$outboundSchema,
} from "./money.js";

export const IcmRewardDetailsErcType = {
  Erc20: "ERC-20",
} as const;
export type IcmRewardDetailsErcType = ClosedEnum<
  typeof IcmRewardDetailsErcType
>;

export type IcmRewardDetails = {
  /**
   * A wallet or contract address in mixed-case checksum encoding.
   */
  address: string;
  /**
   * The contract name.
   */
  name: string;
  /**
   * The contract symbol.
   */
  symbol: string;
  /**
   * The number of decimals the token uses. For example `6`, means to divide the token amount by `1000000` to get its user representation.
   */
  decimals: number;
  /**
   * The logo uri for the address.
   */
  logoUri?: string | undefined;
  ercType: IcmRewardDetailsErcType;
  /**
   * The token price, if available.
   */
  price?: Money | undefined;
  value: string;
};

/** @internal */
export const IcmRewardDetailsErcType$inboundSchema: z.ZodNativeEnum<
  typeof IcmRewardDetailsErcType
> = z.nativeEnum(IcmRewardDetailsErcType);
/** @internal */
export const IcmRewardDetailsErcType$outboundSchema: z.ZodNativeEnum<
  typeof IcmRewardDetailsErcType
> = IcmRewardDetailsErcType$inboundSchema;

/** @internal */
export const IcmRewardDetails$inboundSchema: z.ZodType<
  IcmRewardDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string(),
  name: z.string(),
  symbol: z.string(),
  decimals: z.number(),
  logoUri: z.string().optional(),
  ercType: IcmRewardDetailsErcType$inboundSchema,
  price: Money$inboundSchema.optional(),
  value: z.string(),
});
/** @internal */
export type IcmRewardDetails$Outbound = {
  address: string;
  name: string;
  symbol: string;
  decimals: number;
  logoUri?: string | undefined;
  ercType: string;
  price?: Money$Outbound | undefined;
  value: string;
};

/** @internal */
export const IcmRewardDetails$outboundSchema: z.ZodType<
  IcmRewardDetails$Outbound,
  z.ZodTypeDef,
  IcmRewardDetails
> = z.object({
  address: z.string(),
  name: z.string(),
  symbol: z.string(),
  decimals: z.number(),
  logoUri: z.string().optional(),
  ercType: IcmRewardDetailsErcType$outboundSchema,
  price: Money$outboundSchema.optional(),
  value: z.string(),
});

export function icmRewardDetailsToJSON(
  icmRewardDetails: IcmRewardDetails,
): string {
  return JSON.stringify(
    IcmRewardDetails$outboundSchema.parse(icmRewardDetails),
  );
}
export function icmRewardDetailsFromJSON(
  jsonString: string,
): SafeParseResult<IcmRewardDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IcmRewardDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IcmRewardDetails' from JSON`,
  );
}
