/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ICMRollingWindowMetricsValue = {
  /**
   * Aggregated value for the current metrics in last hour.
   */
  lastHour?: number | undefined;
  /**
   * Aggregated value for the current metrics in last day.
   */
  lastDay?: number | undefined;
  /**
   * Aggregated value for the current metrics in last week.
   */
  lastWeek?: number | undefined;
  /**
   * Aggregated value for the current metrics in last month.
   */
  lastMonth?: number | undefined;
  /**
   * Aggregated value for the current metrics in last 90 days.
   */
  last90Days?: number | undefined;
  /**
   * Aggregated value for the current metrics in last year.
   */
  lastYear?: number | undefined;
  /**
   * Aggregated value for the current metrics for all time.
   */
  allTime?: number | undefined;
  /**
   * Source blockchainId.
   */
  srcBlockchainId: string;
  /**
   * Destination blockchainId.
   */
  destBlockchainId: string;
};

/** @internal */
export const ICMRollingWindowMetricsValue$inboundSchema: z.ZodType<
  ICMRollingWindowMetricsValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  lastHour: z.number().optional(),
  lastDay: z.number().optional(),
  lastWeek: z.number().optional(),
  lastMonth: z.number().optional(),
  last90Days: z.number().optional(),
  lastYear: z.number().optional(),
  allTime: z.number().optional(),
  srcBlockchainId: z.string(),
  destBlockchainId: z.string(),
});
/** @internal */
export type ICMRollingWindowMetricsValue$Outbound = {
  lastHour?: number | undefined;
  lastDay?: number | undefined;
  lastWeek?: number | undefined;
  lastMonth?: number | undefined;
  last90Days?: number | undefined;
  lastYear?: number | undefined;
  allTime?: number | undefined;
  srcBlockchainId: string;
  destBlockchainId: string;
};

/** @internal */
export const ICMRollingWindowMetricsValue$outboundSchema: z.ZodType<
  ICMRollingWindowMetricsValue$Outbound,
  z.ZodTypeDef,
  ICMRollingWindowMetricsValue
> = z.object({
  lastHour: z.number().optional(),
  lastDay: z.number().optional(),
  lastWeek: z.number().optional(),
  lastMonth: z.number().optional(),
  last90Days: z.number().optional(),
  lastYear: z.number().optional(),
  allTime: z.number().optional(),
  srcBlockchainId: z.string(),
  destBlockchainId: z.string(),
});

export function icmRollingWindowMetricsValueToJSON(
  icmRollingWindowMetricsValue: ICMRollingWindowMetricsValue,
): string {
  return JSON.stringify(
    ICMRollingWindowMetricsValue$outboundSchema.parse(
      icmRollingWindowMetricsValue,
    ),
  );
}
export function icmRollingWindowMetricsValueFromJSON(
  jsonString: string,
): SafeParseResult<ICMRollingWindowMetricsValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ICMRollingWindowMetricsValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ICMRollingWindowMetricsValue' from JSON`,
  );
}
