/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CChainExportTransaction,
  CChainExportTransaction$inboundSchema,
  CChainExportTransaction$Outbound,
  CChainExportTransaction$outboundSchema,
} from "./cchainexporttransaction.js";
import {
  CChainImportTransaction,
  CChainImportTransaction$inboundSchema,
  CChainImportTransaction$Outbound,
  CChainImportTransaction$outboundSchema,
} from "./cchainimporttransaction.js";
import {
  PrimaryNetworkChainInfo,
  PrimaryNetworkChainInfo$inboundSchema,
  PrimaryNetworkChainInfo$Outbound,
  PrimaryNetworkChainInfo$outboundSchema,
} from "./primarynetworkchaininfo.js";

export type ListCChainAtomicTransactionsResponseTransaction =
  | CChainExportTransaction
  | CChainImportTransaction;

export type ListCChainAtomicTransactionsResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  transactions: Array<CChainExportTransaction | CChainImportTransaction>;
  chainInfo: PrimaryNetworkChainInfo;
};

/** @internal */
export const ListCChainAtomicTransactionsResponseTransaction$inboundSchema:
  z.ZodType<
    ListCChainAtomicTransactionsResponseTransaction,
    z.ZodTypeDef,
    unknown
  > = z.union([
    CChainExportTransaction$inboundSchema,
    CChainImportTransaction$inboundSchema,
  ]);
/** @internal */
export type ListCChainAtomicTransactionsResponseTransaction$Outbound =
  | CChainExportTransaction$Outbound
  | CChainImportTransaction$Outbound;

/** @internal */
export const ListCChainAtomicTransactionsResponseTransaction$outboundSchema:
  z.ZodType<
    ListCChainAtomicTransactionsResponseTransaction$Outbound,
    z.ZodTypeDef,
    ListCChainAtomicTransactionsResponseTransaction
  > = z.union([
    CChainExportTransaction$outboundSchema,
    CChainImportTransaction$outboundSchema,
  ]);

export function listCChainAtomicTransactionsResponseTransactionToJSON(
  listCChainAtomicTransactionsResponseTransaction:
    ListCChainAtomicTransactionsResponseTransaction,
): string {
  return JSON.stringify(
    ListCChainAtomicTransactionsResponseTransaction$outboundSchema.parse(
      listCChainAtomicTransactionsResponseTransaction,
    ),
  );
}
export function listCChainAtomicTransactionsResponseTransactionFromJSON(
  jsonString: string,
): SafeParseResult<
  ListCChainAtomicTransactionsResponseTransaction,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListCChainAtomicTransactionsResponseTransaction$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListCChainAtomicTransactionsResponseTransaction' from JSON`,
  );
}

/** @internal */
export const ListCChainAtomicTransactionsResponse$inboundSchema: z.ZodType<
  ListCChainAtomicTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  transactions: z.array(
    z.union([
      CChainExportTransaction$inboundSchema,
      CChainImportTransaction$inboundSchema,
    ]),
  ),
  chainInfo: PrimaryNetworkChainInfo$inboundSchema,
});
/** @internal */
export type ListCChainAtomicTransactionsResponse$Outbound = {
  nextPageToken?: string | undefined;
  transactions: Array<
    CChainExportTransaction$Outbound | CChainImportTransaction$Outbound
  >;
  chainInfo: PrimaryNetworkChainInfo$Outbound;
};

/** @internal */
export const ListCChainAtomicTransactionsResponse$outboundSchema: z.ZodType<
  ListCChainAtomicTransactionsResponse$Outbound,
  z.ZodTypeDef,
  ListCChainAtomicTransactionsResponse
> = z.object({
  nextPageToken: z.string().optional(),
  transactions: z.array(
    z.union([
      CChainExportTransaction$outboundSchema,
      CChainImportTransaction$outboundSchema,
    ]),
  ),
  chainInfo: PrimaryNetworkChainInfo$outboundSchema,
});

export function listCChainAtomicTransactionsResponseToJSON(
  listCChainAtomicTransactionsResponse: ListCChainAtomicTransactionsResponse,
): string {
  return JSON.stringify(
    ListCChainAtomicTransactionsResponse$outboundSchema.parse(
      listCChainAtomicTransactionsResponse,
    ),
  );
}
export function listCChainAtomicTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCChainAtomicTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListCChainAtomicTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCChainAtomicTransactionsResponse' from JSON`,
  );
}
