/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PChainStakingTransaction,
  PChainStakingTransaction$inboundSchema,
  PChainStakingTransaction$Outbound,
  PChainStakingTransaction$outboundSchema,
} from "./pchainstakingtransaction.js";
import {
  PrimaryNetworkChainInfo,
  PrimaryNetworkChainInfo$inboundSchema,
  PrimaryNetworkChainInfo$Outbound,
  PrimaryNetworkChainInfo$outboundSchema,
} from "./primarynetworkchaininfo.js";

export type ListPChainStakingTransactionsResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  transactions: Array<PChainStakingTransaction>;
  chainInfo: PrimaryNetworkChainInfo;
};

/** @internal */
export const ListPChainStakingTransactionsResponse$inboundSchema: z.ZodType<
  ListPChainStakingTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  transactions: z.array(PChainStakingTransaction$inboundSchema),
  chainInfo: PrimaryNetworkChainInfo$inboundSchema,
});
/** @internal */
export type ListPChainStakingTransactionsResponse$Outbound = {
  nextPageToken?: string | undefined;
  transactions: Array<PChainStakingTransaction$Outbound>;
  chainInfo: PrimaryNetworkChainInfo$Outbound;
};

/** @internal */
export const ListPChainStakingTransactionsResponse$outboundSchema: z.ZodType<
  ListPChainStakingTransactionsResponse$Outbound,
  z.ZodTypeDef,
  ListPChainStakingTransactionsResponse
> = z.object({
  nextPageToken: z.string().optional(),
  transactions: z.array(PChainStakingTransaction$outboundSchema),
  chainInfo: PrimaryNetworkChainInfo$outboundSchema,
});

export function listPChainStakingTransactionsResponseToJSON(
  listPChainStakingTransactionsResponse: ListPChainStakingTransactionsResponse,
): string {
  return JSON.stringify(
    ListPChainStakingTransactionsResponse$outboundSchema.parse(
      listPChainStakingTransactionsResponse,
    ),
  );
}
export function listPChainStakingTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPChainStakingTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListPChainStakingTransactionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPChainStakingTransactionsResponse' from JSON`,
  );
}
