/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InternalTransaction,
  InternalTransaction$inboundSchema,
  InternalTransaction$Outbound,
  InternalTransaction$outboundSchema,
} from "./internaltransaction.js";

export type ListInternalTransactionsResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  transactions: Array<InternalTransaction>;
};

/** @internal */
export const ListInternalTransactionsResponse$inboundSchema: z.ZodType<
  ListInternalTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  transactions: z.array(InternalTransaction$inboundSchema),
});
/** @internal */
export type ListInternalTransactionsResponse$Outbound = {
  nextPageToken?: string | undefined;
  transactions: Array<InternalTransaction$Outbound>;
};

/** @internal */
export const ListInternalTransactionsResponse$outboundSchema: z.ZodType<
  ListInternalTransactionsResponse$Outbound,
  z.ZodTypeDef,
  ListInternalTransactionsResponse
> = z.object({
  nextPageToken: z.string().optional(),
  transactions: z.array(InternalTransaction$outboundSchema),
});

export function listInternalTransactionsResponseToJSON(
  listInternalTransactionsResponse: ListInternalTransactionsResponse,
): string {
  return JSON.stringify(
    ListInternalTransactionsResponse$outboundSchema.parse(
      listInternalTransactionsResponse,
    ),
  );
}
export function listInternalTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListInternalTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInternalTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInternalTransactionsResponse' from JSON`,
  );
}
