/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Subnet,
  Subnet$inboundSchema,
  Subnet$Outbound,
  Subnet$outboundSchema,
} from "./subnet.js";

export type ListSubnetsResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  subnets: Array<Subnet>;
};

/** @internal */
export const ListSubnetsResponse$inboundSchema: z.ZodType<
  ListSubnetsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  subnets: z.array(Subnet$inboundSchema),
});
/** @internal */
export type ListSubnetsResponse$Outbound = {
  nextPageToken?: string | undefined;
  subnets: Array<Subnet$Outbound>;
};

/** @internal */
export const ListSubnetsResponse$outboundSchema: z.ZodType<
  ListSubnetsResponse$Outbound,
  z.ZodTypeDef,
  ListSubnetsResponse
> = z.object({
  nextPageToken: z.string().optional(),
  subnets: z.array(Subnet$outboundSchema),
});

export function listSubnetsResponseToJSON(
  listSubnetsResponse: ListSubnetsResponse,
): string {
  return JSON.stringify(
    ListSubnetsResponse$outboundSchema.parse(listSubnetsResponse),
  );
}
export function listSubnetsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSubnetsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSubnetsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSubnetsResponse' from JSON`,
  );
}
