/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DeliveredSourceNotIndexedIcmMessage,
  DeliveredSourceNotIndexedIcmMessage$inboundSchema,
  DeliveredSourceNotIndexedIcmMessage$Outbound,
  DeliveredSourceNotIndexedIcmMessage$outboundSchema,
} from "./deliveredsourcenotindexedicmmessage.js";
import {
  DeliveredTeleporterMessage,
  DeliveredTeleporterMessage$inboundSchema,
  DeliveredTeleporterMessage$Outbound,
  DeliveredTeleporterMessage$outboundSchema,
} from "./deliveredteleportermessage.js";
import {
  PendingTeleporterMessage,
  PendingTeleporterMessage$inboundSchema,
  PendingTeleporterMessage$Outbound,
  PendingTeleporterMessage$outboundSchema,
} from "./pendingteleportermessage.js";

export type ListTeleporterMessagesResponseMessage =
  | PendingTeleporterMessage
  | DeliveredTeleporterMessage
  | DeliveredSourceNotIndexedIcmMessage;

export type ListTeleporterMessagesResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  messages: Array<
    | PendingTeleporterMessage
    | DeliveredTeleporterMessage
    | DeliveredSourceNotIndexedIcmMessage
  >;
};

/** @internal */
export const ListTeleporterMessagesResponseMessage$inboundSchema: z.ZodType<
  ListTeleporterMessagesResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.union([
  PendingTeleporterMessage$inboundSchema,
  DeliveredTeleporterMessage$inboundSchema,
  DeliveredSourceNotIndexedIcmMessage$inboundSchema,
]);
/** @internal */
export type ListTeleporterMessagesResponseMessage$Outbound =
  | PendingTeleporterMessage$Outbound
  | DeliveredTeleporterMessage$Outbound
  | DeliveredSourceNotIndexedIcmMessage$Outbound;

/** @internal */
export const ListTeleporterMessagesResponseMessage$outboundSchema: z.ZodType<
  ListTeleporterMessagesResponseMessage$Outbound,
  z.ZodTypeDef,
  ListTeleporterMessagesResponseMessage
> = z.union([
  PendingTeleporterMessage$outboundSchema,
  DeliveredTeleporterMessage$outboundSchema,
  DeliveredSourceNotIndexedIcmMessage$outboundSchema,
]);

export function listTeleporterMessagesResponseMessageToJSON(
  listTeleporterMessagesResponseMessage: ListTeleporterMessagesResponseMessage,
): string {
  return JSON.stringify(
    ListTeleporterMessagesResponseMessage$outboundSchema.parse(
      listTeleporterMessagesResponseMessage,
    ),
  );
}
export function listTeleporterMessagesResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<ListTeleporterMessagesResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListTeleporterMessagesResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTeleporterMessagesResponseMessage' from JSON`,
  );
}

/** @internal */
export const ListTeleporterMessagesResponse$inboundSchema: z.ZodType<
  ListTeleporterMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  messages: z.array(
    z.union([
      PendingTeleporterMessage$inboundSchema,
      DeliveredTeleporterMessage$inboundSchema,
      DeliveredSourceNotIndexedIcmMessage$inboundSchema,
    ]),
  ),
});
/** @internal */
export type ListTeleporterMessagesResponse$Outbound = {
  nextPageToken?: string | undefined;
  messages: Array<
    | PendingTeleporterMessage$Outbound
    | DeliveredTeleporterMessage$Outbound
    | DeliveredSourceNotIndexedIcmMessage$Outbound
  >;
};

/** @internal */
export const ListTeleporterMessagesResponse$outboundSchema: z.ZodType<
  ListTeleporterMessagesResponse$Outbound,
  z.ZodTypeDef,
  ListTeleporterMessagesResponse
> = z.object({
  nextPageToken: z.string().optional(),
  messages: z.array(
    z.union([
      PendingTeleporterMessage$outboundSchema,
      DeliveredTeleporterMessage$outboundSchema,
      DeliveredSourceNotIndexedIcmMessage$outboundSchema,
    ]),
  ),
});

export function listTeleporterMessagesResponseToJSON(
  listTeleporterMessagesResponse: ListTeleporterMessagesResponse,
): string {
  return JSON.stringify(
    ListTeleporterMessagesResponse$outboundSchema.parse(
      listTeleporterMessagesResponse,
    ),
  );
}
export function listTeleporterMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTeleporterMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTeleporterMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTeleporterMessagesResponse' from JSON`,
  );
}
