/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AutoRenewedCycle,
  AutoRenewedCycle$inboundSchema,
  AutoRenewedCycle$Outbound,
  AutoRenewedCycle$outboundSchema,
} from "./autorenewedcycle.js";
import {
  CurrentAutoRenewedCycle,
  CurrentAutoRenewedCycle$inboundSchema,
  CurrentAutoRenewedCycle$Outbound,
  CurrentAutoRenewedCycle$outboundSchema,
} from "./currentautorenewedcycle.js";

export type ListAutoRenewedCyclesResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  /**
   * Settled cycles, newest first by default. Empty for a node with no auto-renewed validation. The in-flight cycle is not included; it is on the validator object.
   */
  cycles: Array<AutoRenewedCycle>;
  /**
   * The cycle in flight. Absent when the position has ended, and on any page but the first.
   */
  currentCycle?: CurrentAutoRenewedCycle | undefined;
};

/** @internal */
export const ListAutoRenewedCyclesResponse$inboundSchema: z.ZodType<
  ListAutoRenewedCyclesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  cycles: z.array(AutoRenewedCycle$inboundSchema),
  currentCycle: CurrentAutoRenewedCycle$inboundSchema.optional(),
});
/** @internal */
export type ListAutoRenewedCyclesResponse$Outbound = {
  nextPageToken?: string | undefined;
  cycles: Array<AutoRenewedCycle$Outbound>;
  currentCycle?: CurrentAutoRenewedCycle$Outbound | undefined;
};

/** @internal */
export const ListAutoRenewedCyclesResponse$outboundSchema: z.ZodType<
  ListAutoRenewedCyclesResponse$Outbound,
  z.ZodTypeDef,
  ListAutoRenewedCyclesResponse
> = z.object({
  nextPageToken: z.string().optional(),
  cycles: z.array(AutoRenewedCycle$outboundSchema),
  currentCycle: CurrentAutoRenewedCycle$outboundSchema.optional(),
});

export function listAutoRenewedCyclesResponseToJSON(
  listAutoRenewedCyclesResponse: ListAutoRenewedCyclesResponse,
): string {
  return JSON.stringify(
    ListAutoRenewedCyclesResponse$outboundSchema.parse(
      listAutoRenewedCyclesResponse,
    ),
  );
}
export function listAutoRenewedCyclesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAutoRenewedCyclesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAutoRenewedCyclesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAutoRenewedCyclesResponse' from JSON`,
  );
}
