/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UsageMetricsValueDTO,
  UsageMetricsValueDTO$inboundSchema,
  UsageMetricsValueDTO$Outbound,
  UsageMetricsValueDTO$outboundSchema,
} from "./usagemetricsvaluedto.js";

export type Metric = {
  /**
   * The timestamp of the metrics value
   */
  timestamp: number;
  /**
   * The metrics values for the timestamp
   */
  values: Array<UsageMetricsValueDTO>;
};

/** @internal */
export const Metric$inboundSchema: z.ZodType<Metric, z.ZodTypeDef, unknown> = z
  .object({
    timestamp: z.number(),
    values: z.array(UsageMetricsValueDTO$inboundSchema),
  });
/** @internal */
export type Metric$Outbound = {
  timestamp: number;
  values: Array<UsageMetricsValueDTO$Outbound>;
};

/** @internal */
export const Metric$outboundSchema: z.ZodType<
  Metric$Outbound,
  z.ZodTypeDef,
  Metric
> = z.object({
  timestamp: z.number(),
  values: z.array(UsageMetricsValueDTO$outboundSchema),
});

export function metricToJSON(metric: Metric): string {
  return JSON.stringify(Metric$outboundSchema.parse(metric));
}
export function metricFromJSON(
  jsonString: string,
): SafeParseResult<Metric, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metric$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metric' from JSON`,
  );
}
