/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Network on which this blockchain or subnet is created on.
 */
export const NetworkType = {
  Mainnet: "mainnet",
  Testnet: "testnet",
} as const;
/**
 * Network on which this blockchain or subnet is created on.
 */
export type NetworkType = ClosedEnum<typeof NetworkType>;

/** @internal */
export const NetworkType$inboundSchema: z.ZodNativeEnum<typeof NetworkType> = z
  .nativeEnum(NetworkType);
/** @internal */
export const NetworkType$outboundSchema: z.ZodNativeEnum<typeof NetworkType> =
  NetworkType$inboundSchema;
