/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const OperationStatusCode = {
  ErrInvalidRequest: "ErrInvalidRequest",
  ErrInternal: "ErrInternal",
  WarnTruncatedExport: "WarnTruncatedExport",
} as const;
export type OperationStatusCode = ClosedEnum<typeof OperationStatusCode>;

/** @internal */
export const OperationStatusCode$inboundSchema: z.ZodNativeEnum<
  typeof OperationStatusCode
> = z.nativeEnum(OperationStatusCode);
/** @internal */
export const OperationStatusCode$outboundSchema: z.ZodNativeEnum<
  typeof OperationStatusCode
> = OperationStatusCode$inboundSchema;
