/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const OperationStatus = {
  Running: "RUNNING",
  Completed: "COMPLETED",
  CompletedWithWarning: "COMPLETED_WITH_WARNING",
  Failed: "FAILED",
} as const;
export type OperationStatus = ClosedEnum<typeof OperationStatus>;

/** @internal */
export const OperationStatus$inboundSchema: z.ZodNativeEnum<
  typeof OperationStatus
> = z.nativeEnum(OperationStatus);
/** @internal */
export const OperationStatus$outboundSchema: z.ZodNativeEnum<
  typeof OperationStatus
> = OperationStatus$inboundSchema;
