/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OperationStatus,
  OperationStatus$inboundSchema,
  OperationStatus$outboundSchema,
} from "./operationstatus.js";
import {
  OperationType,
  OperationType$inboundSchema,
  OperationType$outboundSchema,
} from "./operationtype.js";
import {
  TransactionExportMetadata,
  TransactionExportMetadata$inboundSchema,
  TransactionExportMetadata$Outbound,
  TransactionExportMetadata$outboundSchema,
} from "./transactionexportmetadata.js";

export type OperationStatusResponseMetadata = TransactionExportMetadata;

export type OperationStatusResponse = {
  operationId: string;
  operationType: OperationType;
  operationStatus: OperationStatus;
  message?: string | undefined;
  metadata?: TransactionExportMetadata | undefined;
  createdAtTimestamp: number;
  updatedAtTimestamp: number;
};

/** @internal */
export const OperationStatusResponseMetadata$inboundSchema: z.ZodType<
  OperationStatusResponseMetadata,
  z.ZodTypeDef,
  unknown
> = TransactionExportMetadata$inboundSchema;
/** @internal */
export type OperationStatusResponseMetadata$Outbound =
  TransactionExportMetadata$Outbound;

/** @internal */
export const OperationStatusResponseMetadata$outboundSchema: z.ZodType<
  OperationStatusResponseMetadata$Outbound,
  z.ZodTypeDef,
  OperationStatusResponseMetadata
> = TransactionExportMetadata$outboundSchema;

export function operationStatusResponseMetadataToJSON(
  operationStatusResponseMetadata: OperationStatusResponseMetadata,
): string {
  return JSON.stringify(
    OperationStatusResponseMetadata$outboundSchema.parse(
      operationStatusResponseMetadata,
    ),
  );
}
export function operationStatusResponseMetadataFromJSON(
  jsonString: string,
): SafeParseResult<OperationStatusResponseMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OperationStatusResponseMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperationStatusResponseMetadata' from JSON`,
  );
}

/** @internal */
export const OperationStatusResponse$inboundSchema: z.ZodType<
  OperationStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  operationId: z.string(),
  operationType: OperationType$inboundSchema,
  operationStatus: OperationStatus$inboundSchema,
  message: z.string().optional(),
  metadata: TransactionExportMetadata$inboundSchema.optional(),
  createdAtTimestamp: z.number(),
  updatedAtTimestamp: z.number(),
});
/** @internal */
export type OperationStatusResponse$Outbound = {
  operationId: string;
  operationType: string;
  operationStatus: string;
  message?: string | undefined;
  metadata?: TransactionExportMetadata$Outbound | undefined;
  createdAtTimestamp: number;
  updatedAtTimestamp: number;
};

/** @internal */
export const OperationStatusResponse$outboundSchema: z.ZodType<
  OperationStatusResponse$Outbound,
  z.ZodTypeDef,
  OperationStatusResponse
> = z.object({
  operationId: z.string(),
  operationType: OperationType$outboundSchema,
  operationStatus: OperationStatus$outboundSchema,
  message: z.string().optional(),
  metadata: TransactionExportMetadata$outboundSchema.optional(),
  createdAtTimestamp: z.number(),
  updatedAtTimestamp: z.number(),
});

export function operationStatusResponseToJSON(
  operationStatusResponse: OperationStatusResponse,
): string {
  return JSON.stringify(
    OperationStatusResponse$outboundSchema.parse(operationStatusResponse),
  );
}
export function operationStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<OperationStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OperationStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperationStatusResponse' from JSON`,
  );
}
