/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const PChainId = {
  ElevenNonillionOneHundredAndElevenOctillionOneHundredAndElevenSeptillionOneHundredAndElevenSextillionOneHundredAndElevenQuintillionOneHundredAndElevenQuadrillionOneHundredAndElevenTrillionOneHundredAndElevenBillionOneHundredAndElevenMillionOneHundredAndElevenThousandOneHundredAndElevenLpoYY:
    "11111111111111111111111111111111LpoYY",
  PChain: "p-chain",
} as const;
export type PChainId = ClosedEnum<typeof PChainId>;

/** @internal */
export const PChainId$inboundSchema: z.ZodNativeEnum<typeof PChainId> = z
  .nativeEnum(PChainId);
/** @internal */
export const PChainId$outboundSchema: z.ZodNativeEnum<typeof PChainId> =
  PChainId$inboundSchema;
