/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PChainAddressDetails = {
  /**
   * A list of P-Chain addresses.
   */
  addresses: Array<string>;
  /**
   * Route dependent value associated with an address at a given point in time.
   */
  sortKey: string;
};

/** @internal */
export const PChainAddressDetails$inboundSchema: z.ZodType<
  PChainAddressDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  addresses: z.array(z.string()),
  sortKey: z.string(),
});
/** @internal */
export type PChainAddressDetails$Outbound = {
  addresses: Array<string>;
  sortKey: string;
};

/** @internal */
export const PChainAddressDetails$outboundSchema: z.ZodType<
  PChainAddressDetails$Outbound,
  z.ZodTypeDef,
  PChainAddressDetails
> = z.object({
  addresses: z.array(z.string()),
  sortKey: z.string(),
});

export function pChainAddressDetailsToJSON(
  pChainAddressDetails: PChainAddressDetails,
): string {
  return JSON.stringify(
    PChainAddressDetails$outboundSchema.parse(pChainAddressDetails),
  );
}
export function pChainAddressDetailsFromJSON(
  jsonString: string,
): SafeParseResult<PChainAddressDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PChainAddressDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PChainAddressDetails' from JSON`,
  );
}
