/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PrimaryNetworkAssetType,
  PrimaryNetworkAssetType$inboundSchema,
  PrimaryNetworkAssetType$outboundSchema,
} from "./primarynetworkassettype.js";

export type PChainSharedAsset = {
  /**
   * Unique ID for an asset.
   */
  assetId: string;
  /**
   * Name of this asset.
   */
  name: string;
  /**
   * Symbol for this asset (max 4 characters).
   */
  symbol: string;
  /**
   * Denomination of this asset to represent fungibility.
   */
  denomination: number;
  /**
   * Type of asset like SECP256K1 or NFT.
   */
  type: PrimaryNetworkAssetType;
  /**
   * Amount of the asset.
   */
  amount: string;
  utxoCount: number;
  sharedWithChainId: string;
  status: string;
};

/** @internal */
export const PChainSharedAsset$inboundSchema: z.ZodType<
  PChainSharedAsset,
  z.ZodTypeDef,
  unknown
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$inboundSchema,
  amount: z.string(),
  utxoCount: z.number(),
  sharedWithChainId: z.string(),
  status: z.string(),
});
/** @internal */
export type PChainSharedAsset$Outbound = {
  assetId: string;
  name: string;
  symbol: string;
  denomination: number;
  type: string;
  amount: string;
  utxoCount: number;
  sharedWithChainId: string;
  status: string;
};

/** @internal */
export const PChainSharedAsset$outboundSchema: z.ZodType<
  PChainSharedAsset$Outbound,
  z.ZodTypeDef,
  PChainSharedAsset
> = z.object({
  assetId: z.string(),
  name: z.string(),
  symbol: z.string(),
  denomination: z.number(),
  type: PrimaryNetworkAssetType$outboundSchema,
  amount: z.string(),
  utxoCount: z.number(),
  sharedWithChainId: z.string(),
  status: z.string(),
});

export function pChainSharedAssetToJSON(
  pChainSharedAsset: PChainSharedAsset,
): string {
  return JSON.stringify(
    PChainSharedAsset$outboundSchema.parse(pChainSharedAsset),
  );
}
export function pChainSharedAssetFromJSON(
  jsonString: string,
): SafeParseResult<PChainSharedAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PChainSharedAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PChainSharedAsset' from JSON`,
  );
}
