/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Array of address activity sub-event types
 */
export const PrimaryNetworkAddressActivitySubEventType = {
  BalanceChange: "balance_change",
  BalanceThreshold: "balance_threshold",
  RewardDistribution: "reward_distribution",
} as const;
/**
 * Array of address activity sub-event types
 */
export type PrimaryNetworkAddressActivitySubEventType = ClosedEnum<
  typeof PrimaryNetworkAddressActivitySubEventType
>;

/** @internal */
export const PrimaryNetworkAddressActivitySubEventType$inboundSchema:
  z.ZodNativeEnum<typeof PrimaryNetworkAddressActivitySubEventType> = z
    .nativeEnum(PrimaryNetworkAddressActivitySubEventType);
/** @internal */
export const PrimaryNetworkAddressActivitySubEventType$outboundSchema:
  z.ZodNativeEnum<typeof PrimaryNetworkAddressActivitySubEventType> =
    PrimaryNetworkAddressActivitySubEventType$inboundSchema;
