/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const PrimaryNetworkTxType = {
  AddValidatorTx: "AddValidatorTx",
  AddSubnetValidatorTx: "AddSubnetValidatorTx",
  AddDelegatorTx: "AddDelegatorTx",
  CreateChainTx: "CreateChainTx",
  CreateSubnetTx: "CreateSubnetTx",
  ImportTx: "ImportTx",
  ExportTx: "ExportTx",
  AdvanceTimeTx: "AdvanceTimeTx",
  RewardValidatorTx: "RewardValidatorTx",
  RemoveSubnetValidatorTx: "RemoveSubnetValidatorTx",
  TransformSubnetTx: "TransformSubnetTx",
  AddPermissionlessValidatorTx: "AddPermissionlessValidatorTx",
  AddPermissionlessDelegatorTx: "AddPermissionlessDelegatorTx",
  BaseTx: "BaseTx",
  TransferSubnetOwnershipTx: "TransferSubnetOwnershipTx",
  ConvertSubnetToL1Tx: "ConvertSubnetToL1Tx",
  RegisterL1ValidatorTx: "RegisterL1ValidatorTx",
  SetL1ValidatorWeightTx: "SetL1ValidatorWeightTx",
  DisableL1ValidatorTx: "DisableL1ValidatorTx",
  IncreaseL1ValidatorBalanceTx: "IncreaseL1ValidatorBalanceTx",
  Unknown: "UNKNOWN",
  CreateAssetTx: "CreateAssetTx",
  OperationTx: "OperationTx",
} as const;
export type PrimaryNetworkTxType = ClosedEnum<typeof PrimaryNetworkTxType>;

/** @internal */
export const PrimaryNetworkTxType$inboundSchema: z.ZodNativeEnum<
  typeof PrimaryNetworkTxType
> = z.nativeEnum(PrimaryNetworkTxType);
/** @internal */
export const PrimaryNetworkTxType$outboundSchema: z.ZodNativeEnum<
  typeof PrimaryNetworkTxType
> = PrimaryNetworkTxType$inboundSchema;
