/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Network,
  Network$inboundSchema,
  Network$outboundSchema,
} from "./network.js";
import {
  PrimaryNetworkChainName,
  PrimaryNetworkChainName$inboundSchema,
  PrimaryNetworkChainName$outboundSchema,
} from "./primarynetworkchainname.js";

export type PrimaryNetworkChainInfo = {
  chainName: PrimaryNetworkChainName;
  network: Network;
};

/** @internal */
export const PrimaryNetworkChainInfo$inboundSchema: z.ZodType<
  PrimaryNetworkChainInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainName: PrimaryNetworkChainName$inboundSchema,
  network: Network$inboundSchema,
});
/** @internal */
export type PrimaryNetworkChainInfo$Outbound = {
  chainName: string;
  network: string;
};

/** @internal */
export const PrimaryNetworkChainInfo$outboundSchema: z.ZodType<
  PrimaryNetworkChainInfo$Outbound,
  z.ZodTypeDef,
  PrimaryNetworkChainInfo
> = z.object({
  chainName: PrimaryNetworkChainName$outboundSchema,
  network: Network$outboundSchema,
});

export function primaryNetworkChainInfoToJSON(
  primaryNetworkChainInfo: PrimaryNetworkChainInfo,
): string {
  return JSON.stringify(
    PrimaryNetworkChainInfo$outboundSchema.parse(primaryNetworkChainInfo),
  );
}
export function primaryNetworkChainInfoFromJSON(
  jsonString: string,
): SafeParseResult<PrimaryNetworkChainInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrimaryNetworkChainInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrimaryNetworkChainInfo' from JSON`,
  );
}
