/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChainRollingWindowMetricsValue,
  ChainRollingWindowMetricsValue$inboundSchema,
  ChainRollingWindowMetricsValue$Outbound,
  ChainRollingWindowMetricsValue$outboundSchema,
} from "./chainrollingwindowmetricsvalue.js";

export type RollingWindowMetricsApiResponse = {
  /**
   * Array of current metrics values for different windows.
   */
  result: ChainRollingWindowMetricsValue;
};

/** @internal */
export const RollingWindowMetricsApiResponse$inboundSchema: z.ZodType<
  RollingWindowMetricsApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: ChainRollingWindowMetricsValue$inboundSchema,
});
/** @internal */
export type RollingWindowMetricsApiResponse$Outbound = {
  result: ChainRollingWindowMetricsValue$Outbound;
};

/** @internal */
export const RollingWindowMetricsApiResponse$outboundSchema: z.ZodType<
  RollingWindowMetricsApiResponse$Outbound,
  z.ZodTypeDef,
  RollingWindowMetricsApiResponse
> = z.object({
  result: ChainRollingWindowMetricsValue$outboundSchema,
});

export function rollingWindowMetricsApiResponseToJSON(
  rollingWindowMetricsApiResponse: RollingWindowMetricsApiResponse,
): string {
  return JSON.stringify(
    RollingWindowMetricsApiResponse$outboundSchema.parse(
      rollingWindowMetricsApiResponse,
    ),
  );
}
export function rollingWindowMetricsApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<RollingWindowMetricsApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RollingWindowMetricsApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RollingWindowMetricsApiResponse' from JSON`,
  );
}
