/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SortByOption = {
  BlockIndex: "blockIndex",
  DelegationCapacity: "delegationCapacity",
  TimeRemaining: "timeRemaining",
  DelegationFee: "delegationFee",
  UptimePerformance: "uptimePerformance",
} as const;
export type SortByOption = ClosedEnum<typeof SortByOption>;

/** @internal */
export const SortByOption$inboundSchema: z.ZodNativeEnum<typeof SortByOption> =
  z.nativeEnum(SortByOption);
/** @internal */
export const SortByOption$outboundSchema: z.ZodNativeEnum<typeof SortByOption> =
  SortByOption$inboundSchema;
