/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Staking kind. `autoRenewed` type validators run in repeating cycles; for these the top-level startTimestamp/endTimestamp/amountStaked reflect the current cycle and compounded weight.
 */
export const StakingType = {
  Fixed: "fixed",
  AutoRenewed: "autoRenewed",
} as const;
/**
 * Staking kind. `autoRenewed` type validators run in repeating cycles; for these the top-level startTimestamp/endTimestamp/amountStaked reflect the current cycle and compounded weight.
 */
export type StakingType = ClosedEnum<typeof StakingType>;

/** @internal */
export const StakingType$inboundSchema: z.ZodNativeEnum<typeof StakingType> = z
  .nativeEnum(StakingType);
/** @internal */
export const StakingType$outboundSchema: z.ZodNativeEnum<typeof StakingType> =
  StakingType$inboundSchema;
