/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  StakingDistribution,
  StakingDistribution$inboundSchema,
  StakingDistribution$Outbound,
  StakingDistribution$outboundSchema,
} from "./stakingdistribution.js";

export type ValidatorsDetails = {
  validatorCount: number;
  totalAmountStaked: string;
  /**
   * Total potential rewards from currently active validations and delegations.
   */
  estimatedAnnualStakingReward: string;
  stakingDistributionByVersion: Array<StakingDistribution>;
  /**
   * Ratio of total active stake amount to the current supply.
   */
  stakingRatio: string;
};

/** @internal */
export const ValidatorsDetails$inboundSchema: z.ZodType<
  ValidatorsDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  validatorCount: z.number(),
  totalAmountStaked: z.string(),
  estimatedAnnualStakingReward: z.string(),
  stakingDistributionByVersion: z.array(StakingDistribution$inboundSchema),
  stakingRatio: z.string(),
});
/** @internal */
export type ValidatorsDetails$Outbound = {
  validatorCount: number;
  totalAmountStaked: string;
  estimatedAnnualStakingReward: string;
  stakingDistributionByVersion: Array<StakingDistribution$Outbound>;
  stakingRatio: string;
};

/** @internal */
export const ValidatorsDetails$outboundSchema: z.ZodType<
  ValidatorsDetails$Outbound,
  z.ZodTypeDef,
  ValidatorsDetails
> = z.object({
  validatorCount: z.number(),
  totalAmountStaked: z.string(),
  estimatedAnnualStakingReward: z.string(),
  stakingDistributionByVersion: z.array(StakingDistribution$outboundSchema),
  stakingRatio: z.string(),
});

export function validatorsDetailsToJSON(
  validatorsDetails: ValidatorsDetails,
): string {
  return JSON.stringify(
    ValidatorsDetails$outboundSchema.parse(validatorsDetails),
  );
}
export function validatorsDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ValidatorsDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidatorsDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidatorsDetails' from JSON`,
  );
}
