/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const WebhookStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type WebhookStatus = ClosedEnum<typeof WebhookStatus>;

/** @internal */
export const WebhookStatus$inboundSchema: z.ZodNativeEnum<
  typeof WebhookStatus
> = z.nativeEnum(WebhookStatus);
/** @internal */
export const WebhookStatus$outboundSchema: z.ZodNativeEnum<
  typeof WebhookStatus
> = WebhookStatus$inboundSchema;
