/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const XChainId = {
  TwooYmbnv4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM:
    "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM",
  TwoJVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm:
    "2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm",
  XChain: "x-chain",
} as const;
export type XChainId = ClosedEnum<typeof XChainId>;

/** @internal */
export const XChainId$inboundSchema: z.ZodNativeEnum<typeof XChainId> = z
  .nativeEnum(XChainId);
/** @internal */
export const XChainId$outboundSchema: z.ZodNativeEnum<typeof XChainId> =
  XChainId$inboundSchema;
