export {
  CircularReferenceError,
  InvalidAbiItemError,
  InvalidAbiParameterError,
  InvalidAbiParametersError,
  InvalidAbiTypeParameterError,
  InvalidFunctionModifierError,
  InvalidModifierError,
  InvalidParameterError,
  InvalidParenthesisError,
  InvalidSignatureError,
  InvalidStructSignatureError,
  parseAbi,
  parseAbiItem,
  parseAbiParameter,
  parseAbiParameters,
  SolidityProtectedKeywordError,
  UnknownSignatureError,
  UnknownTypeError,
  type Abi,
  type AbiEvent,
  type AbiFunction,
  type AbiParameter,
  type AbiParameterKind,
  type AbiParameterToPrimitiveType,
  type AbiStateMutability,
  type Address,
  type Narrow,
  type ParseAbi,
  type ParseAbiItem,
  type ParseAbiParameter,
  type ParseAbiParameters,
  type TypedData,
  type TypedDataDomain,
  type TypedDataParameter,
} from "viem";
export type { BlockOverrides, RpcBlockOverrides } from "viem";

export {
  AbiConstructorNotFoundError,
  AbiConstructorParamsNotFoundError,
  AbiDecodingDataSizeInvalidError,
  AbiDecodingDataSizeTooSmallError,
  AbiDecodingZeroDataError,
  AbiEncodingArrayLengthMismatchError,
  AbiEncodingBytesSizeMismatchError,
  AbiEncodingLengthMismatchError,
  AbiErrorInputsNotFoundError,
  AbiErrorNotFoundError,
  AbiErrorSignatureNotFoundError,
  AbiEventNotFoundError,
  AbiEventSignatureEmptyTopicsError,
  AbiEventSignatureNotFoundError,
  AbiFunctionNotFoundError,
  AbiFunctionOutputsNotFoundError,
  AbiFunctionSignatureNotFoundError,
  AccountStateConflictError,
  assertCurrentChain,
  assertRequest,
  assertTransactionEIP1559,
  assertTransactionEIP2930,
  assertTransactionLegacy,
  AtomicityNotSupportedError,
  AtomicReadyWalletRejectedUpgradeError,
  BaseError,
  BaseFeeScalarError,
  blobsToCommitments,
  blobsToProofs,
  BlockNotFoundError,
  boolToBytes,
  boolToHex,
  BundleTooLargeError,
  BytesSizeMismatchError,
  bytesToBigInt,
  bytesToBool,
  bytesToHex,
  bytesToNumber,
  bytesToRlp,
  bytesToString,
  CallExecutionError,
  /** @deprecated Use `ccipRequest`. */
  ccipRequest as ccipFetch,
  ccipRequest,
  ChainDisconnectedError,
  ChainDoesNotSupportContract,
  ChainMismatchError,
  ChainNotFoundError,
  checksumAddress,
  ClientChainNotConfiguredError,
  commitmentsToVersionedHashes,
  commitmentToVersionedHash,
  /** @deprecated Use `serializeCompactSignature` instead. */
  serializeCompactSignature as compactSignatureToHex,
  compactSignatureToSignature,
  concat,
  concatBytes,
  concatHex,
  ContractFunctionExecutionError,
  ContractFunctionRevertedError,
  ContractFunctionZeroDataError,
  CounterfactualDeploymentFailedError,
  createClient,
  createNonceManager,
  createPublicClient,
  createTestClient,
  createTransport,
  createWalletClient,
  custom,
  decodeAbiParameters,
  decodeDeployData,
  decodeErrorResult,
  decodeEventLog,
  decodeFunctionData,
  decodeFunctionResult,
  DecodeLogDataMismatch,
  DecodeLogTopicsMismatch,
  defineBlock,
  defineChain,
  defineKzg,
  defineTransaction,
  defineTransactionReceipt,
  defineTransactionRequest,
  deploylessCallViaBytecodeBytecode,
  deploylessCallViaFactoryBytecode,
  domainSeparator,
  DuplicateIdError,
  ProviderRpcError as EIP1193ProviderRpcError,
  Eip1559FeesNotSupportedError,
  encodeAbiParameters,
  encodeDeployData,
  encodeErrorResult,
  encodeEventTopics,
  encodeFunctionData,
  encodeFunctionResult,
  encodePacked,
  EnsAvatarInvalidNftUriError,
  EnsAvatarUnsupportedNamespaceError,
  EnsAvatarUriResolutionError,
  erc1155Abi,
  erc20Abi,
  erc20Abi_bytes32,
  erc4626Abi,
  erc721Abi,
  EstimateGasExecutionError,
  ethAddress,
  etherUnits,
  ExecutionRevertedError,
  extractChain,
  fallback,
  FeeCapTooHighError,
  FeeCapTooLowError,
  FeeConflictError,
  FilterTypeNotSupportedError,
  formatBlock,
  formatEther,
  formatGwei,
  formatLog,
  formatTransaction,
  formatTransactionReceipt,
  formatTransactionRequest,
  formatUnits,
  fromBlobs,
  fromBytes,
  fromHex,
  fromRlp,
  getAbiItem,
  getAddress,
  getChainContractAddress,
  getContract,
  getContractAddress,
  getContractError,
  getCreate2Address,
  getCreateAddress,
  /** @deprecated use `toEventSelector`. */
  toEventSelector as getEventSelector,
  /** @deprecated use `toEventSignature`. */
  toEventSignature as getEventSignature,
  /** @deprecated use `toFunctionSelector`. */
  toFunctionSelector as getFunctionSelector,
  /** @deprecated use `toFunctionSignature`. */
  toFunctionSignature as getFunctionSignature,
  getSerializedTransactionType,
  getTransactionType,
  getTypesForEIP712Domain,
  gweiUnits,
  hashDomain,
  hashMessage,
  hashStruct,
  hashTypedData,
  hexToBigInt,
  hexToBool,
  hexToBytes,
  /** @deprecated Use `parseCompactSignature`. */
  parseCompactSignature as hexToCompactSignature,
  hexToNumber,
  hexToRlp,
  /** @deprecated Use `parseSignature`. */
  parseSignature as hexToSignature,
  hexToString,
  http,
  HttpRequestError,
  InsufficientFundsError,
  IntegerOutOfRangeError,
  InternalRpcError,
  IntrinsicGasTooHighError,
  IntrinsicGasTooLowError,
  InvalidAbiDecodingTypeError,
  InvalidAbiEncodingTypeError,
  InvalidAddressError,
  InvalidArrayError,
  InvalidBytesBooleanError,
  InvalidChainIdError,
  InvalidDecimalNumberError,
  InvalidDefinitionTypeError,
  InvalidDomainError,
  InvalidHexBooleanError,
  InvalidHexValueError,
  InvalidInputRpcError,
  InvalidLegacyVError,
  InvalidParamsRpcError,
  InvalidPrimaryTypeError,
  InvalidRequestRpcError,
  InvalidSerializableTransactionError,
  InvalidSerializedTransactionError,
  InvalidSerializedTransactionTypeError,
  InvalidStorageKeySizeError,
  InvalidStructTypeError,
  isAddress,
  isAddressEqual,
  isBytes,
  isErc6492Signature,
  isHash,
  isHex,
  JsonRpcVersionUnsupportedError,
  keccak256,
  labelhash,
  LimitExceededRpcError,
  MaxFeePerGasTooLowError,
  maxInt104,
  maxInt112,
  maxInt120,
  maxInt128,
  maxInt136,
  maxInt144,
  maxInt152,
  maxInt16,
  maxInt160,
  maxInt168,
  maxInt176,
  maxInt184,
  maxInt192,
  maxInt200,
  maxInt208,
  maxInt216,
  maxInt224,
  maxInt232,
  maxInt24,
  maxInt240,
  maxInt248,
  maxInt256,
  maxInt32,
  maxInt40,
  maxInt48,
  maxInt56,
  maxInt64,
  maxInt72,
  maxInt8,
  maxInt80,
  maxInt88,
  maxInt96,
  maxUint104,
  maxUint112,
  maxUint120,
  maxUint128,
  maxUint136,
  maxUint144,
  maxUint152,
  maxUint16,
  maxUint160,
  maxUint168,
  maxUint176,
  maxUint184,
  maxUint192,
  maxUint200,
  maxUint208,
  maxUint216,
  maxUint224,
  maxUint232,
  maxUint24,
  maxUint240,
  maxUint248,
  maxUint256,
  maxUint32,
  maxUint40,
  maxUint48,
  maxUint56,
  maxUint64,
  maxUint72,
  maxUint8,
  maxUint80,
  maxUint88,
  maxUint96,
  MethodNotFoundRpcError,
  MethodNotSupportedRpcError,
  minInt104,
  minInt112,
  minInt120,
  minInt128,
  minInt136,
  minInt144,
  minInt152,
  minInt16,
  minInt160,
  minInt168,
  minInt176,
  minInt184,
  minInt192,
  minInt200,
  minInt208,
  minInt216,
  minInt224,
  minInt232,
  minInt24,
  minInt240,
  minInt248,
  minInt256,
  minInt32,
  minInt40,
  minInt48,
  minInt56,
  minInt64,
  minInt72,
  minInt8,
  minInt80,
  minInt88,
  minInt96,
  multicall3Abi,
  namehash,
  nonceManager,
  NonceMaxValueError,
  NonceTooHighError,
  NonceTooLowError,
  numberToBytes,
  numberToHex,
  offchainLookup,
  offchainLookupAbiItem,
  offchainLookupSignature,
  pad,
  padBytes,
  padHex,
  parseCompactSignature,
  parseErc6492Signature,
  parseEther,
  parseEventLogs,
  parseGwei,
  ParseRpcError,
  parseSignature,
  parseTransaction,
  parseUnits,
  prepareEncodeFunctionData,
  presignMessagePrefix,
  ProviderDisconnectedError,
  ProviderRpcError,
  publicActions,
  RawContractError,
  recoverAddress,
  recoverMessageAddress,
  recoverPublicKey,
  recoverTransactionAddress,
  recoverTypedDataAddress,
  ResourceNotFoundRpcError,
  ResourceUnavailableRpcError,
  ripemd160,
  RpcError,
  RpcRequestError,
  rpcSchema,
  rpcTransactionType,
  serializeAccessList,
  serializeCompactSignature,
  serializeErc6492Signature,
  serializeSignature,
  serializeTransaction,
  serializeTypedData,
  setErrorConfig,
  setupKzg,
  sha256,
  shouldThrow,
  sidecarsToVersionedHashes,
  signatureToCompactSignature,
  /** @deprecated Use `serializeSignature` instead. */
  serializeSignature as signatureToHex,
  size,
  SizeExceedsPaddingSizeError,
  SizeOverflowError,
  slice,
  sliceBytes,
  sliceHex,
  SliceOffsetOutOfBoundsError,
  SocketClosedError,
  StateAssignmentConflictError,
  stringify,
  stringToBytes,
  stringToHex,
  SwitchChainError,
  testActions,
  TimeoutError,
  TipAboveFeeCapError,
  toBlobs,
  toBlobSidecars,
  toBytes,
  toEventHash,
  toEventSelector,
  toEventSignature,
  toFunctionHash,
  toFunctionSelector,
  toFunctionSignature,
  toHex,
  toPrefixedMessage,
  toRlp,
  TransactionExecutionError,
  TransactionNotFoundError,
  TransactionReceiptNotFoundError,
  TransactionRejectedRpcError,
  transactionType,
  TransactionTypeNotSupportedError,
  trim,
  UnauthorizedProviderError,
  universalSignatureValidatorAbi,
  universalSignatureValidatorByteCode,
  UnknownBundleIdError,
  UnknownNodeError,
  UnknownRpcError,
  UnsupportedChainIdError,
  UnsupportedNonOptionalCapabilityError,
  UnsupportedPackedAbiType,
  UnsupportedProviderMethodError,
  UrlRequiredError,
  UserRejectedRequestError,
  validateTypedData,
  verifyHash,
  verifyMessage,
  verifyTypedData,
  WaitForCallsStatusTimeoutError,
  WaitForTransactionReceiptTimeoutError,
  walletActions,
  webSocket,
  WebSocketRequestError,
  weiUnits,
  withCache,
  withRetry,
  withTimeout,
  zeroAddress,
  zeroHash,
  type AbiConstructorNotFoundErrorType,
  type AbiConstructorParamsNotFoundErrorType,
  type AbiDecodingDataSizeInvalidErrorType,
  type AbiDecodingDataSizeTooSmallErrorType,
  type AbiDecodingZeroDataErrorType,
  type AbiEncodingArrayLengthMismatchErrorType,
  type AbiEncodingBytesSizeMismatchErrorType,
  type AbiEncodingLengthMismatchErrorType,
  type AbiErrorInputsNotFoundErrorType,
  type AbiErrorNotFoundErrorType,
  type AbiErrorSignatureNotFoundErrorType,
  type AbiEventNotFoundErrorType,
  type AbiEventSignatureEmptyTopicsErrorType,
  type AbiEventSignatureNotFoundErrorType,
  type AbiFunctionNotFoundErrorType,
  type AbiFunctionOutputsNotFoundErrorType,
  type AbiFunctionSignatureNotFoundErrorType,
  type AccountStateConflictErrorType,
  type AssertCurrentChainErrorType,
  type AssertCurrentChainParameters,
  type AssertRequestErrorType,
  type AssertTransactionEIP1559ErrorType,
  type AssertTransactionEIP2930ErrorType,
  type AssertTransactionLegacyErrorType,
  type AtomicityNotSupportedErrorType,
  type AtomicReadyWalletRejectedUpgradeErrorType,
  type BaseErrorType,
  type BaseFeeScalarErrorType,
  type BlobsToCommitmentsErrorType,
  type BlobsToCommitmentsParameters,
  type BlobsToCommitmentsReturnType,
  type blobsToProofsErrorType,
  type blobsToProofsParameters,
  type blobsToProofsReturnType,
  type BlockNotFoundErrorType,
  type BoolToBytesErrorType,
  type BoolToBytesOpts,
  type BoolToHexErrorType,
  type BoolToHexOpts,
  type BundleTooLargeErrorType,
  type BytesSizeMismatchErrorType,
  type BytesToBigIntErrorType,
  type BytesToBigIntOpts,
  type BytesToBoolErrorType,
  type BytesToBoolOpts,
  type BytesToHexErrorType,
  type BytesToHexOpts,
  type BytesToNumberErrorType,
  type BytesToNumberOpts,
  type BytesToRlpErrorType,
  type BytesToStringErrorType,
  type BytesToStringOpts,
  type CallExecutionErrorType,
  type CcipRequestErrorType,
  type CcipRequestParameters,
  type ChainDisconnectedErrorType,
  type ChainDoesNotSupportContractErrorType,
  type ChainMismatchErrorType,
  type ChainNotFoundErrorType,
  type ChecksumAddressErrorType,
  type Client,
  type ClientChainNotConfiguredErrorType,
  type ClientConfig,
  type CommitmentsToVersionedHashesErrorType,
  type CommitmentsToVersionedHashesParameters,
  type CommitmentsToVersionedHashesReturnType,
  type CommitmentToVersionedHashErrorType,
  type CommitmentToVersionedHashParameters,
  type CommitmentToVersionedHashReturnType,
  /** @deprecated Use `SignatureToHexErrorType` instead. */
  type SerializeCompactSignatureErrorType as CompactSignatureToHexErrorType,
  type CompactSignatureToSignatureErrorType,
  type ConcatBytesErrorType,
  type ConcatErrorType,
  type ConcatHexErrorType,
  type ConcatReturnType,
  type ContractFunctionExecutionErrorType,
  type ContractFunctionRevertedErrorType,
  type ContractFunctionZeroDataErrorType,
  type CounterfactualDeploymentFailedErrorType,
  type CreateClientErrorType,
  type CreateNonceManagerParameters,
  type CreatePublicClientErrorType,
  type CreateTestClientErrorType,
  type CreateTransportErrorType,
  type CreateWalletClientErrorType,
  type CustomTransport,
  type CustomTransportConfig,
  type CustomTransportErrorType,
  type DecodeAbiParametersErrorType,
  type DecodeAbiParametersReturnType,
  type DecodeDeployDataErrorType,
  type DecodeDeployDataParameters,
  type DecodeDeployDataReturnType,
  type DecodeErrorResultErrorType,
  type DecodeErrorResultParameters,
  type DecodeErrorResultReturnType,
  type DecodeEventLogErrorType,
  type DecodeEventLogParameters,
  type DecodeEventLogReturnType,
  type DecodeFunctionDataErrorType,
  type DecodeFunctionDataParameters,
  type DecodeFunctionDataReturnType,
  type DecodeFunctionResultErrorType,
  type DecodeFunctionResultParameters,
  type DecodeFunctionResultReturnType,
  type DecodeLogDataMismatchErrorType,
  type DecodeLogTopicsMismatchErrorType,
  type DefineBlockErrorType,
  type DefineKzgErrorType,
  type DefineKzgParameters,
  type DefineKzgReturnType,
  type DefineTransactionErrorType,
  type DefineTransactionReceiptErrorType,
  type DefineTransactionRequestErrorType,
  type DomainSeparatorErrorType,
  type DuplicateIdErrorType,
  type Eip1559FeesNotSupportedErrorType,
  type EncodeAbiParametersErrorType,
  type EncodeAbiParametersReturnType,
  type EncodeDeployDataErrorType,
  type EncodeDeployDataParameters,
  type EncodeDeployDataReturnType,
  type EncodeErrorResultErrorType,
  type EncodeErrorResultParameters,
  type EncodeErrorResultReturnType,
  type EncodeEventTopicsErrorType,
  type EncodeEventTopicsParameters,
  type EncodeEventTopicsReturnType,
  type EncodeFunctionDataErrorType,
  type EncodeFunctionDataParameters,
  type EncodeFunctionDataReturnType,
  type EncodeFunctionResultErrorType,
  type EncodeFunctionResultParameters,
  type EncodeFunctionResultReturnType,
  type EncodePackedErrorType,
  type EnsAvatarInvalidMetadataError,
  type EnsAvatarInvalidMetadataErrorType,
  type EnsAvatarInvalidNftUriErrorType,
  type EnsAvatarUnsupportedNamespaceErrorType,
  type EnsAvatarUriResolutionErrorType,
  type EstimateGasExecutionErrorType,
  type ExecutionRevertedErrorType,
  type ExtractChainErrorType,
  type ExtractChainParameters,
  type ExtractChainReturnType,
  type FallbackTransport,
  type FallbackTransportConfig,
  type FallbackTransportErrorType,
  type FeeCapTooHighErrorType,
  type FeeCapTooLowErrorType,
  type FeeConflictErrorType,
  type FilterTypeNotSupportedErrorType,
  type FormatBlockErrorType,
  type FormatEtherErrorType,
  type FormatGweiErrorType,
  type FormatLogErrorType,
  type FormattedBlock,
  type FormattedTransaction,
  type FormattedTransactionReceipt,
  type FormattedTransactionRequest,
  type FormatTransactionErrorType,
  type FormatTransactionReceiptErrorType,
  type FormatTransactionRequestErrorType,
  type FormatUnitsErrorType,
  type FromBlobsErrorType,
  type FromBlobsParameters,
  type FromBlobsReturnType,
  type FromBytesErrorType,
  type FromBytesParameters,
  type FromHexErrorType,
  type FromRlpErrorType,
  type FromRlpReturnType,
  type GetAbiItemErrorType,
  type GetAbiItemParameters,
  type GetAbiItemReturnType,
  type GetAddressErrorType,
  type GetChainContractAddressErrorType,
  type GetContractAddressOptions,
  type GetContractErrorReturnType,
  type GetContractErrorType,
  type GetContractParameters,
  type GetContractReturnType,
  type GetCreate2AddressErrorType,
  type GetCreate2AddressOptions,
  type GetCreateAddressErrorType,
  type GetCreateAddressOptions,
  /** @deprecated use `ToEventSelectorErrorType`. */
  type ToEventSelectorErrorType as GetEventSelectorErrorType,
  /** @deprecated use `ToEventSignatureErrorType`. */
  type ToEventSignatureErrorType as GetEventSignatureErrorType,
  /** @deprecated use `ToFunctionSelectorErrorType`. */
  type ToFunctionSelectorErrorType as GetFunctionSelectorErrorType,
  /** @deprecated use `ToFunctionSignatureErrorType`. */
  type ToFunctionSignatureErrorType as GetFunctionSignatureErrorType,
  type GetSerializedTransactionType,
  type GetSerializedTransactionTypeErrorType,
  type GetTransactionType,
  type GetTransactionTypeErrorType,
  type GetTypesForEIP712DomainErrorType,
  type HashDomainErrorType,
  type HashMessageErrorType,
  type HashStructErrorType,
  type HashTypedDataErrorType,
  type HashTypedDataParameters,
  type HashTypedDataReturnType,
  type HexToBigIntErrorType,
  type HexToBoolErrorType,
  type HexToBytesErrorType,
  type HexToBytesOpts,
  /** @deprecated Use `ParseCompactSignatureErrorType`. */
  type ParseCompactSignatureErrorType as HexToCompactSignatureErrorType,
  type HexToNumberErrorType,
  type HexToRlpErrorType,
  /** @deprecated Use `ParseSignatureErrorType`. */
  type ParseSignatureErrorType as HexToSignatureErrorType,
  type HexToStringErrorType,
  type HttpRequestErrorType,
  type HttpTransport,
  type HttpTransportConfig,
  type HttpTransportErrorType,
  type InsufficientFundsErrorType,
  type IntegerOutOfRangeErrorType,
  type InternalRpcErrorType,
  type IntrinsicGasTooHighErrorType,
  type IntrinsicGasTooLowErrorType,
  type InvalidAbiDecodingTypeErrorType,
  type InvalidAbiEncodingTypeErrorType,
  type InvalidAddressErrorType,
  type InvalidArrayErrorType,
  type InvalidBytesBooleanErrorType,
  type InvalidChainIdErrorType,
  type InvalidDecimalNumberErrorType,
  type InvalidDefinitionTypeErrorType,
  type InvalidDomainErrorType,
  type InvalidHexBooleanErrorType,
  type InvalidHexValueErrorType,
  type InvalidInputRpcErrorType,
  type InvalidLegacyVErrorType,
  type InvalidParamsRpcErrorType,
  type InvalidPrimaryTypeErrorType,
  type InvalidRequestRpcErrorType,
  type InvalidSerializableTransactionErrorType,
  type InvalidSerializedTransactionErrorType,
  type InvalidSerializedTransactionTypeErrorType,
  type InvalidStorageKeySizeErrorType,
  type InvalidStructTypeErrorType,
  type IsAddressEqualErrorType,
  type IsAddressEqualReturnType,
  type IsAddressErrorType,
  type IsAddressOptions,
  type IsBytesErrorType,
  type IsErc6492SignatureErrorType,
  type IsErc6492SignatureParameters,
  type IsErc6492SignatureReturnType,
  type IsHashErrorType,
  type IsHexErrorType,
  type JsonRpcVersionUnsupportedErrorType,
  type Keccak256ErrorType,
  type Keccak256Hash,
  type LabelhashErrorType,
  type LimitExceededRpcErrorType,
  type MaxFeePerGasTooLowErrorType,
  type MethodNotFoundRpcErrorType,
  type MethodNotSupportedRpcErrorType,
  type MulticallBatchOptions,
  type NamehashErrorType,
  type NonceManager,
  type NonceManagerSource,
  type NonceMaxValueErrorType,
  type NonceTooHighErrorType,
  type NonceTooLowErrorType,
  type NumberToBytesErrorType,
  type NumberToHexErrorType,
  type NumberToHexOpts,
  type OffchainLookupErrorType,
  type PadBytesErrorType,
  type PadErrorType,
  type PadHexErrorType,
  type PadReturnType,
  type ParseCompactSignatureErrorType,
  type ParseErc6492SignatureErrorType,
  type ParseErc6492SignatureParameters,
  type ParseErc6492SignatureReturnType,
  type ParseEtherErrorType,
  type ParseEventLogsErrorType,
  type ParseEventLogsParameters,
  type ParseEventLogsReturnType,
  type ParseGweiErrorType,
  type ParseRpcErrorType,
  type ParseSignatureErrorType,
  type ParseTransactionErrorType,
  type ParseTransactionReturnType,
  type ParseUnitsErrorType,
  type PrepareEncodeFunctionDataErrorType,
  type PrepareEncodeFunctionDataParameters,
  type PrepareEncodeFunctionDataReturnType,
  type ProviderDisconnectedErrorType,
  type ProviderRpcErrorCode,
  type ProviderRpcErrorType,
  type PublicActions,
  type PublicClient,
  type PublicClientConfig,
  type RawContractErrorType,
  type RecoverAddressErrorType,
  type RecoverAddressParameters,
  type RecoverAddressReturnType,
  type RecoverMessageAddressErrorType,
  type RecoverMessageAddressParameters,
  type RecoverMessageAddressReturnType,
  type RecoverPublicKeyErrorType,
  type RecoverPublicKeyParameters,
  type RecoverPublicKeyReturnType,
  type RecoverTransactionAddressErrorType,
  type RecoverTransactionAddressParameters,
  type RecoverTransactionAddressReturnType,
  type RecoverTypedDataAddressErrorType,
  type RecoverTypedDataAddressParameters,
  type RecoverTypedDataAddressReturnType,
  type ResourceNotFoundRpcErrorType,
  type ResourceUnavailableRpcErrorType,
  type Ripemd160ErrorType,
  type Ripemd160Hash,
  type RpcErrorCode,
  type RpcErrorType,
  type RpcRequestErrorType,
  type SerializeAccessListErrorType,
  type SerializeCompactSignatureErrorType,
  type SerializedTransactionReturnType,
  type SerializeErc6492SignatureErrorType,
  type SerializeErc6492SignatureParameters,
  type SerializeErc6492SignatureReturnType,
  type SerializeSignatureErrorType,
  type SerializeSignatureParameters,
  type SerializeSignatureReturnType,
  type SerializeTransactionErrorType,
  type SerializeTransactionFn,
  type SerializeTypedDataErrorType,
  type SetupKzgErrorType,
  type SetupKzgParameters,
  type SetupKzgReturnType,
  type Sha256ErrorType,
  type Sha256Hash,
  type SidecarsToVersionedHashesErrorType,
  type SidecarsToVersionedHashesParameters,
  type SidecarsToVersionedHashesReturnType,
  type SignatureToCompactSignatureErrorType,
  /** @deprecated Use `SignatureToHexErrorType` instead. */
  type SerializeSignatureErrorType as SignatureToHexErrorType,
  type SizeErrorType,
  type SizeExceedsPaddingSizeErrorType,
  type SizeOverflowErrorType,
  type SliceBytesErrorType,
  type SliceErrorType,
  type SliceHexErrorType,
  type SliceOffsetOutOfBoundsErrorType,
  type SocketClosedErrorType,
  type StateAssignmentConflictErrorType,
  type StringifyErrorType,
  type StringToBytesErrorType,
  type StringToBytesOpts,
  type StringToHexErrorType,
  type StringToHexOpts,
  type TestActions,
  type TestClient,
  type TestClientConfig,
  type TimeoutErrorType,
  type TipAboveFeeCapErrorType,
  type ToBlobsErrorType,
  type ToBlobSidecarsErrorType,
  type ToBlobSidecarsParameters,
  type ToBlobSidecarsReturnType,
  type ToBlobsParameters,
  type ToBlobsReturnType,
  type ToBytesErrorType,
  type ToBytesParameters,
  type ToEventHashErrorType,
  type ToEventSelectorErrorType,
  type ToEventSignatureErrorType,
  type ToFunctionHashErrorType,
  type ToFunctionSelectorErrorType,
  type ToFunctionSignatureErrorType,
  type ToHexErrorType,
  type ToHexParameters,
  type ToPrefixedMessageErrorType,
  type ToRlpErrorType,
  type ToRlpReturnType,
  type TransactionExecutionErrorType,
  type TransactionNotFoundErrorType,
  type TransactionReceiptNotFoundErrorType,
  type TransactionRejectedRpcErrorType,
  type TransactionTypeNotSupportedErrorType,
  type Transport,
  type TransportConfig,
  type TrimErrorType,
  type TrimReturnType,
  type UnauthorizedProviderErrorType,
  type UnknownBundleIdErrorType,
  type UnknownNodeErrorType,
  type UnknownRpcErrorType,
  type UnsupportedChainIdErrorType,
  type UnsupportedNonOptionalCapabilityErrorType,
  type UnsupportedPackedAbiTypeErrorType,
  type UnsupportedProviderMethodErrorType,
  type UrlRequiredErrorType,
  type UserRejectedRequestErrorType,
  type ValidateTypedDataErrorType,
  type VerifyHashErrorType,
  type VerifyHashParameters,
  type VerifyHashReturnType,
  type VerifyMessageErrorType,
  type VerifyMessageParameters,
  type VerifyMessageReturnType,
  type VerifyTypedDataErrorType,
  type VerifyTypedDataParameters,
  type VerifyTypedDataReturnType,
  type WaitForTransactionReceiptTimeoutErrorType,
  type WalletActions,
  type WalletClient,
  type WalletClientConfig,
  type WebSocketRequestErrorType,
  type WebSocketTransport,
  type WebSocketTransportConfig,
  type WebSocketTransportErrorType,
  type WithRetryErrorType,
  type WithTimeoutErrorType,
} from "viem";
export type {
  AbiEventParametersToPrimitiveTypes,
  AbiEventParameterToPrimitiveType,
  AbiEventTopicToPrimitiveType,
  AbiItem,
  AbiItemArgs,
  AbiItemName,
  AccessList,
  Account,
  AccountSource,
  AddChainErrorType,
  AddChainParameters,
  AddEthereumChainParameter,
  AssetGateway,
  AssetGatewayUrls,
  Assign,
  Authorization,
  AuthorizationList,
  AuthorizationRequest,
  BlobSidecar,
  BlobSidecars,
  // Block is exported separately below from our augmented type (includes Avalanche-specific fields)
  BlockIdentifier,
  BlockNumber,
  BlockTag,
  Branded,
  BundlerRpcSchema,
  ByteArray,
  Call,
  CallErrorType,
  CallParameters,
  CallReturnType,
  Calls,
  Capabilities,
  CapabilitiesSchema,
  Chain,
  ChainConfig,
  ChainContract,
  ChainEstimateFeesPerGasFn,
  ChainEstimateFeesPerGasFnParameters,
  ChainFees,
  ChainFeesFnParameters,
  ChainFormatter,
  ChainFormatters,
  ChainIdToCapabilities,
  ChainMaxPriorityFeePerGasFn,
  ChainSerializers,
  CompactSignature,
  ContractConstructorArgs,
  ContractErrorArgs,
  ContractErrorName,
  ContractEventArgs,
  ContractEventArgsFromTopics,
  ContractEventName,
  ContractFunctionArgs,
  ContractFunctionName,
  ContractFunctionParameters,
  ContractFunctionReturnType,
  CreateAccessListErrorType,
  CreateAccessListParameters,
  CreateAccessListReturnType,
  CreateBlockFilterErrorType,
  CreateBlockFilterReturnType,
  CreateContractEventFilterErrorType,
  CreateContractEventFilterParameters,
  CreateContractEventFilterReturnType,
  CreateEventFilterErrorType,
  CreateEventFilterParameters,
  CreateEventFilterReturnType,
  CreatePendingTransactionFilterErrorType,
  CreatePendingTransactionFilterReturnType,
  CustomSource,
  DebugBundlerRpcSchema,
  DeployContractErrorType,
  DeployContractParameters,
  DeployContractReturnType,
  DeriveAccount,
  DeriveChain,
  DropTransactionErrorType,
  DropTransactionParameters,
  DumpStateErrorType,
  DumpStateReturnType,
  EIP1193EventMap,
  EIP1193Events,
  EIP1193Parameters,
  EIP1193Provider,
  ProviderRpcErrorType as EIP1193ProviderRpcErrorType,
  EIP1193RequestFn,
  EIP1474Methods,
  EstimateContractGasErrorType,
  EstimateContractGasParameters,
  EstimateContractGasReturnType,
  EstimateFeesPerGasErrorType,
  EstimateFeesPerGasParameters,
  EstimateFeesPerGasReturnType,
  EstimateGasErrorType,
  EstimateGasParameters,
  EstimateGasReturnType,
  EstimateMaxPriorityFeePerGasErrorType,
  EstimateMaxPriorityFeePerGasParameters,
  EstimateMaxPriorityFeePerGasReturnType,
  Evaluate,
  EventDefinition,
  ExactPartial,
  ExactRequired,
  ExtractAbiFunctionForArgs,
  ExtractAbiItem,
  ExtractAbiItemForArgs,
  ExtractAbiItemNames,
  ExtractCapabilities,
  ExtractChainFormatterExclude,
  ExtractChainFormatterParameters,
  ExtractChainFormatterReturnType,
  FeeHistory,
  FeeValues,
  FeeValuesEIP1559,
  FeeValuesEIP4844,
  FeeValuesLegacy,
  FeeValuesType,
  Filter,
  FilterType,
  GetAddressesErrorType,
  GetAddressesReturnType,
  GetAutomineErrorType,
  GetAutomineReturnType,
  GetBalanceErrorType,
  GetBalanceParameters,
  GetBalanceReturnType,
  GetBlobBaseFeeErrorType,
  GetBlobBaseFeeReturnType,
  GetBlockErrorType,
  GetBlockNumberErrorType,
  GetBlockNumberParameters,
  GetBlockNumberReturnType,
  GetBlockParameters,
  GetBlockReturnType,
  GetBlockTransactionCountErrorType,
  GetBlockTransactionCountParameters,
  GetBlockTransactionCountReturnType,
  /** @deprecated Use `GetCodeErrorType` instead */
  GetCodeErrorType as GetBytecodeErrorType,
  /** @deprecated Use `GetCodeParameters` instead */
  GetCodeParameters as GetBytecodeParameters,
  /** @deprecated Use `GetCodeReturnType` instead  */
  GetCodeReturnType as GetBytecodeReturnType,
  GetCallsStatusErrorType,
  GetCallsStatusParameters,
  GetCallsStatusReturnType,
  GetCapabilitiesErrorType,
  GetCapabilitiesParameters,
  GetCapabilitiesReturnType,
  GetChainIdErrorType,
  GetChainIdReturnType,
  GetChainParameter,
  GetCodeErrorType,
  GetCodeParameters,
  GetCodeReturnType,
  GetContractEventsErrorType,
  GetContractEventsParameters,
  GetContractEventsReturnType,
  GetEip712DomainErrorType,
  GetEip712DomainParameters,
  GetEip712DomainReturnType,
  GetEnsAddressErrorType,
  GetEnsAddressParameters,
  GetEnsAddressReturnType,
  GetEnsAvatarErrorType,
  GetEnsAvatarParameters,
  GetEnsAvatarReturnType,
  GetEnsNameErrorType,
  GetEnsNameParameters,
  GetEnsNameReturnType,
  GetEnsResolverErrorType,
  GetEnsResolverParameters,
  GetEnsResolverReturnType,
  GetEnsTextErrorType,
  GetEnsTextParameters,
  GetEnsTextReturnType,
  GetEventArgs,
  GetFeeHistoryErrorType,
  GetFeeHistoryParameters,
  GetFeeHistoryReturnType,
  GetFilterChangesErrorType,
  GetFilterChangesParameters,
  GetFilterChangesReturnType,
  GetFilterLogsErrorType,
  GetFilterLogsParameters,
  GetFilterLogsReturnType,
  GetGasPriceErrorType,
  GetGasPriceReturnType,
  GetLogsErrorType,
  GetLogsParameters,
  GetLogsReturnType,
  GetMutabilityAwareValue,
  GetPermissionsErrorType,
  GetPermissionsReturnType,
  GetPollOptions,
  GetProofErrorType,
  GetProofParameters,
  GetProofReturnType,
  GetStorageAtErrorType,
  GetStorageAtParameters,
  GetStorageAtReturnType,
  GetTransactionConfirmationsErrorType,
  GetTransactionConfirmationsParameters,
  GetTransactionConfirmationsReturnType,
  GetTransactionCountErrorType,
  GetTransactionCountParameters,
  GetTransactionCountReturnType,
  GetTransactionErrorType,
  GetTransactionParameters,
  GetTransactionReceiptErrorType,
  GetTransactionReceiptParameters,
  GetTransactionReceiptReturnType,
  GetTransactionRequestKzgParameter,
  GetTransactionReturnType,
  GetTransportConfig,
  GetTxpoolContentErrorType,
  GetTxpoolContentReturnType,
  GetTxpoolStatusErrorType,
  GetTxpoolStatusReturnType,
  GetValue,
  Hash,
  HDAccount,
  HDKey,
  HDOptions,
  Hex,
  ImpersonateAccountErrorType,
  ImpersonateAccountParameters,
  IncreaseTimeErrorType,
  IncreaseTimeParameters,
  Index,
  InspectTxpoolErrorType,
  InspectTxpoolReturnType,
  IsNarrowable,
  IsNever,
  IsUndefined,
  IsUnion,
  JsonRpcAccount,
  Kzg,
  LoadStateErrorType,
  LoadStateParameters,
  LoadStateReturnType,
  LocalAccount,
  Log,
  LogTopic,
  LogTopicType,
  LooseOmit,
  MaybeAbiEventName,
  MaybeExtractEventArgsFromAbi,
  MaybePartial,
  MaybePromise,
  MaybeRequired,
  MineErrorType,
  MineParameters,
  MulticallContracts,
  MulticallErrorType,
  MulticallParameters,
  MulticallResponse,
  MulticallResults,
  MulticallReturnType,
  Mutable,
  NetworkSync,
  NoInfer,
  NoUndefined,
  Omit,
  OnBlock,
  OnBlockNumberFn,
  OnBlockNumberParameter,
  OnBlockParameter,
  OneOf,
  OnTransactionsFn,
  OnTransactionsParameter,
  Or,
  ParseAccount,
  PartialBy,
  PaymasterRpcSchema,
  PrepareAuthorizationErrorType,
  PrepareAuthorizationParameters,
  PrepareAuthorizationReturnType,
  PrepareTransactionRequestErrorType,
  PrepareTransactionRequestParameters,
  PrepareTransactionRequestParameterType,
  PrepareTransactionRequestRequest,
  PrepareTransactionRequestReturnType,
  Prettify,
  PrivateKeyAccount,
  ProviderConnectInfo,
  ProviderMessage,
  PublicRpcSchema,
  Quantity,
  ReadContractErrorType,
  ReadContractParameters,
  ReadContractReturnType,
  Register,
  RemoveBlockTimestampIntervalErrorType,
  ReplacementReason,
  ReplacementReturnType,
  RequestAddressesErrorType,
  RequestAddressesReturnType,
  RequestPermissionsErrorType,
  RequestPermissionsParameters,
  RequestPermissionsReturnType,
  RequiredBy,
  ResetErrorType,
  ResetParameters,
  ResolvedRegister,
  RevertErrorType,
  RevertParameters,
  RpcAccountStateOverride,
  RpcAuthorization,
  RpcAuthorizationList,
  RpcBlock,
  RpcBlockIdentifier,
  RpcBlockNumber,
  RpcFeeHistory,
  RpcFeeValues,
  RpcLog,
  RpcProof,
  RpcSchema,
  RpcSchemaOverride,
  RpcStateMapping,
  RpcStateOverride,
  RpcTransaction,
  RpcTransactionReceipt,
  RpcTransactionRequest,
  RpcUncle,
  SendCallsErrorType,
  SendCallsParameters,
  SendCallsReturnType,
  SendRawTransactionErrorType,
  SendRawTransactionParameters,
  SendRawTransactionReturnType,
  SendTransactionErrorType,
  SendTransactionParameters,
  SendTransactionRequest,
  SendTransactionReturnType,
  SendUnsignedTransactionErrorType,
  SendUnsignedTransactionParameters,
  SendUnsignedTransactionReturnType,
  SerializedAuthorization,
  SerializedAuthorizationList,
  SetAutomineErrorType,
  SetBalanceErrorType,
  SetBalanceParameters,
  SetBlockGasLimitErrorType,
  SetBlockGasLimitParameters,
  SetBlockTimestampIntervalErrorType,
  SetBlockTimestampIntervalParameters,
  SetCodeErrorType,
  SetCodeParameters,
  SetCoinbaseErrorType,
  SetCoinbaseParameters,
  SetIntervalMiningErrorType,
  SetIntervalMiningParameters,
  SetLoggingEnabledErrorType,
  SetMinGasPriceErrorType,
  SetMinGasPriceParameters,
  SetNextBlockBaseFeePerGasErrorType,
  SetNextBlockBaseFeePerGasParameters,
  SetNextBlockTimestampErrorType,
  SetNextBlockTimestampParameters,
  SetNonceErrorType,
  SetNonceParameters,
  SetRpcUrlErrorType,
  SetStorageAtErrorType,
  SetStorageAtParameters,
  ShowCallsStatusErrorType,
  ShowCallsStatusParameters,
  ShowCallsStatusReturnType,
  SignableMessage,
  Signature,
  SignAuthorizationErrorType,
  SignAuthorizationParameters,
  SignAuthorizationReturnType,
  SignedAuthorization,
  SignedAuthorizationList,
  SignMessageErrorType,
  SignMessageParameters,
  SignMessageReturnType,
  SignTransactionErrorType,
  SignTransactionParameters,
  SignTransactionReturnType,
  SignTypedDataErrorType,
  SignTypedDataParameters,
  SignTypedDataReturnType,
  SimulateBlocksErrorType,
  SimulateBlocksParameters,
  SimulateBlocksReturnType,
  SimulateCallsErrorType,
  SimulateCallsParameters,
  SimulateCallsReturnType,
  SimulateContractErrorType,
  SimulateContractParameters,
  SimulateContractReturnType,
  SnapshotErrorType,
  Some,
  StateMapping,
  StateOverride,
  Status,
  StopImpersonatingAccountErrorType,
  StopImpersonatingAccountParameters,
  SwitchChainErrorType,
  SwitchChainParameters,
  TestRpcSchema,
  Transaction,
  TransactionBase,
  TransactionEIP1559,
  TransactionEIP2930,
  TransactionEIP4844,
  TransactionEIP7702,
  TransactionLegacy,
  TransactionReceipt,
  TransactionRequest,
  TransactionRequestBase,
  TransactionRequestEIP1559,
  TransactionRequestEIP2930,
  TransactionRequestEIP4844,
  TransactionRequestEIP7702,
  TransactionRequestGeneric,
  TransactionRequestLegacy,
  TransactionSerializable,
  TransactionSerializableBase,
  TransactionSerializableEIP1559,
  TransactionSerializableEIP2930,
  TransactionSerializableEIP4844,
  TransactionSerializableEIP7702,
  TransactionSerializableGeneric,
  TransactionSerializableLegacy,
  TransactionSerialized,
  TransactionSerializedEIP1559,
  TransactionSerializedEIP2930,
  TransactionSerializedEIP4844,
  TransactionSerializedEIP7702,
  TransactionSerializedGeneric,
  TransactionSerializedLegacy,
  TransactionType,
  TypedDataDefinition,
  Uncle,
  UninstallFilterErrorType,
  UninstallFilterParameters,
  UninstallFilterReturnType,
  UnionEvaluate,
  UnionLooseOmit,
  UnionOmit,
  UnionPartialBy,
  UnionPick,
  UnionRequiredBy,
  UnionToTuple,
  UnionWiden,
  ValueOf,
  VerifyHashErrorType as VerifyHashActionErrorType,
  VerifyHashParameters as VerifyHashActionParameters,
  VerifyHashReturnType as VerifyHashActionReturnType,
  VerifyMessageErrorType as VerifyMessageActionErrorType,
  VerifyMessageParameters as VerifyMessageActionParameters,
  VerifyMessageReturnType as VerifyMessageActionReturnType,
  VerifyTypedDataErrorType as VerifyTypedDataActionErrorType,
  VerifyTypedDataParameters as VerifyTypedDataActionParameters,
  VerifyTypedDataReturnType as VerifyTypedDataActionReturnType,
  WaitForCallsStatusErrorType,
  WaitForCallsStatusParameters,
  WaitForCallsStatusReturnType,
  WaitForCallsStatusTimeoutErrorType,
  WaitForTransactionReceiptErrorType,
  WaitForTransactionReceiptParameters,
  WaitForTransactionReceiptReturnType,
  WalletCallReceipt,
  /** @deprecated Use `Capabilities` instead. */
  Capabilities as WalletCapabilities,
  /** @deprecated Use `ChainIdToCapabilities` instead. */
  ChainIdToCapabilities as WalletCapabilitiesRecord,
  WalletGetCallsStatusReturnType,
  WalletGrantPermissionsParameters,
  WalletGrantPermissionsReturnType,
  WalletPermission,
  WalletPermissionCaveat,
  WalletRpcSchema,
  WalletSendCallsParameters,
  WalletSendCallsReturnType,
  WatchAssetErrorType,
  WatchAssetParameters,
  WatchAssetParams,
  WatchAssetReturnType,
  WatchBlockNumberErrorType,
  WatchBlockNumberParameters,
  WatchBlockNumberReturnType,
  WatchBlocksErrorType,
  WatchBlocksParameters,
  WatchBlocksReturnType,
  WatchContractEventErrorType,
  WatchContractEventOnLogsFn,
  WatchContractEventOnLogsParameter,
  WatchContractEventParameters,
  WatchContractEventReturnType,
  WatchEventErrorType,
  WatchEventOnLogsFn,
  WatchEventOnLogsParameter,
  WatchEventParameters,
  WatchEventReturnType,
  WatchPendingTransactionsErrorType,
  WatchPendingTransactionsParameters,
  WatchPendingTransactionsReturnType,
  Widen,
  Withdrawal,
  WriteContractErrorType,
  WriteContractParameters,
  WriteContractReturnType,
} from "viem";

// ------------- Custom Clients ------------- //
export {
  createAdminApiClient,
  type AdminApiClient,
  type AdminApiClientConfig,
  type CreateAdminApiClientErrorType,
} from "./clients/createAdminApiClient.js";
export {
  createAvalancheBaseClient,
  type AvalancheBaseClient,
  type AvalancheBaseClientConfig,
  type CreateAvalancheBaseClientErrorType,
} from "./clients/createAvalancheBaseClient.js";
export { createAvalancheClient } from "./clients/createAvalancheClient.js";
export {
  createAvalancheCoreClient,
  type AvalancheCoreClient,
  type AvalancheCoreClientConfig,
  type CreateAvalancheCoreClientErrorType,
} from "./clients/createAvalancheCoreClient.js";
export {
  createAvalancheWalletClient,
  type AvalancheWalletClient,
  type AvalancheWalletClientConfig,
  type CreateAvalancheWalletClientErrorType,
} from "./clients/createAvalancheWalletClient.js";
export {
  createAvalancheWalletCoreClient,
  type AvalancheWalletCoreClient,
  type AvalancheWalletCoreClientConfig,
  type CreateAvalancheWalletCoreClientErrorType,
} from "./clients/createAvalancheWalletCoreClient.js";
export {
  createCChainClient,
  type CChainClient,
  type CChainClientConfig,
  type CreateCChainClientErrorType,
} from "./clients/createCChainClient.js";
export {
  createHealthApiClient,
  type CreateHealthApiClientErrorType,
  type HealthApiClient,
  type HealthApiClientConfig,
} from "./clients/createHealthApiClient.js";
export {
  createIndexApiClient,
  type CreateIndexApiClientErrorType,
  type IndexApiClient,
  type IndexApiClientConfig,
} from "./clients/createIndexApiClient.js";
export {
  createInfoApiClient,
  type CreateInfoApiClientErrorType,
  type InfoApiClient,
  type InfoApiClientConfig,
} from "./clients/createInfoApiClient.js";
export {
  createPChainClient,
  type CreatePChainClientErrorType,
  type PChainClient,
  type PChainClientConfig,
} from "./clients/createPChainClient.js";
export {
  createProposervmApiClient,
  type CreateProposervmApiClientErrorType,
  type ProposervmApiClient,
  type ProposervmApiClientConfig,
} from "./clients/createProposervmApiClient.js";
export {
  createXChainClient,
  type CreateXChainClientErrorType,
  type XChainClient,
  type XChainClientConfig,
} from "./clients/createXChainClient.js";
export {
  adminAPIActions,
  type AdminAPIActions,
} from "./clients/decorators/adminApi.js";
export {
  avalanchePublicActions,
  type AvalanchePublicActions,
} from "./clients/decorators/avalanchePublic.js";
export {
  avalancheWalletActions,
  type AvalancheWalletActions,
} from "./clients/decorators/avalancheWallet.js";
export {
  cChainActions,
  type CChainActions,
} from "./clients/decorators/cChain.js";
export {
  cChainWalletActions,
  type CChainWalletActions,
} from "./clients/decorators/cChainWallet.js";
export { erc20Actions, type Erc20Actions } from "./clients/decorators/erc20.js";
export {
  healthAPIActions,
  type HealthAPIActions,
} from "./clients/decorators/healthApi.js";
export {
  indexAPIActions,
  type IndexAPIActions,
} from "./clients/decorators/indexApi.js";
export {
  infoAPIActions,
  type InfoAPIActions,
} from "./clients/decorators/infoApi.js";
export {
  pChainActions,
  type PChainActions,
} from "./clients/decorators/pChain.js";
export {
  proposervmAPIActions,
  type ProposervmAPIActions,
} from "./clients/decorators/proposervmApi.js";
export {
  xChainActions,
  type XChainActions,
} from "./clients/decorators/xChain.js";
export {
  type AvalancheClient,
  type AvalancheClientConfig,
  type CreateAvalancheClientErrorType,
} from "./clients/types/createAvalancheClient.js";
export { type AvalancheTransportConfig } from "./clients/types/types.js";
export { createAvalancheTransportClient } from "./clients/utils.js";
export { type AdminRpcSchema } from "./methods/admin/adminRpcSchema.js";
export { type CChainRpcSchema } from "./methods/cChain/cChainRpcSchema.js";
export { type HealthRpcSchema } from "./methods/health/healthRpcSchema.js";
export { type IndexRpcSchema } from "./methods/index/indexRpcSchema.js";
export { type InfoRpcSchema } from "./methods/info/infoRpcSchema.js";
export { type PChainRpcSchema } from "./methods/pChain/pChainRpcSchema.js";
export { type ProposervmRpcSchema } from "./methods/proposervm/proposervmRpcSchema.js";
export { type AvalanchePublicRpcSchema } from "./methods/public/avalanchePublicRpcSchema.js";
export { type AvalancheWalletRpcSchema } from "./methods/wallet/avalancheWalletRPCSchema.js";
export { type XChainRpcSchema } from "./methods/xChain/xChainRpcSchema.js";
// Augment viem's Block type with Avalanche-specific fields
export type { Block } from "./types/block.js";
