/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { AvalancheError } from "./avalancheerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The error message describing the reason for the exception
 */
export type ForbiddenMessage = string | Array<string>;

export type ForbiddenErrorData = {
  /**
   * The error message describing the reason for the exception
   */
  message: string | Array<string>;
  /**
   * The HTTP status code of the response
   */
  statusCode: number;
  /**
   * The type of error
   */
  error: string;
};

export class ForbiddenError extends AvalancheError {
  /**
   * The type of error
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorData;

  constructor(
    err: ForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ForbiddenError";
  }
}

/** @internal */
export const ForbiddenMessage$inboundSchema: z.ZodType<
  ForbiddenMessage,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type ForbiddenMessage$Outbound = string | Array<string>;

/** @internal */
export const ForbiddenMessage$outboundSchema: z.ZodType<
  ForbiddenMessage$Outbound,
  z.ZodTypeDef,
  ForbiddenMessage
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ForbiddenMessage$ {
  /** @deprecated use `ForbiddenMessage$inboundSchema` instead. */
  export const inboundSchema = ForbiddenMessage$inboundSchema;
  /** @deprecated use `ForbiddenMessage$outboundSchema` instead. */
  export const outboundSchema = ForbiddenMessage$outboundSchema;
  /** @deprecated use `ForbiddenMessage$Outbound` instead. */
  export type Outbound = ForbiddenMessage$Outbound;
}

export function forbiddenMessageToJSON(
  forbiddenMessage: ForbiddenMessage,
): string {
  return JSON.stringify(
    ForbiddenMessage$outboundSchema.parse(forbiddenMessage),
  );
}

export function forbiddenMessageFromJSON(
  jsonString: string,
): SafeParseResult<ForbiddenMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForbiddenMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForbiddenMessage' from JSON`,
  );
}

/** @internal */
export const ForbiddenError$inboundSchema: z.ZodType<
  ForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.union([z.string(), z.array(z.string())]),
  statusCode: z.number(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ForbiddenError$Outbound = {
  message: string | Array<string>;
  statusCode: number;
  error: string;
};

/** @internal */
export const ForbiddenError$outboundSchema: z.ZodType<
  ForbiddenError$Outbound,
  z.ZodTypeDef,
  ForbiddenError
> = z.instanceof(ForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.union([z.string(), z.array(z.string())]),
    statusCode: z.number(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ForbiddenError$ {
  /** @deprecated use `ForbiddenError$inboundSchema` instead. */
  export const inboundSchema = ForbiddenError$inboundSchema;
  /** @deprecated use `ForbiddenError$outboundSchema` instead. */
  export const outboundSchema = ForbiddenError$outboundSchema;
  /** @deprecated use `ForbiddenError$Outbound` instead. */
  export type Outbound = ForbiddenError$Outbound;
}
