/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { AvalancheError } from "./avalancheerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The error message describing the reason for the exception
 */
export type TooManyRequestsMessage = string | Array<string>;

export type TooManyRequestsErrorData = {
  /**
   * The error message describing the reason for the exception
   */
  message: string | Array<string>;
  /**
   * The HTTP status code of the response
   */
  statusCode: number;
  /**
   * The type of error
   */
  error: string;
};

export class TooManyRequestsError extends AvalancheError {
  /**
   * The type of error
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: TooManyRequestsErrorData;

  constructor(
    err: TooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "TooManyRequestsError";
  }
}

/** @internal */
export const TooManyRequestsMessage$inboundSchema: z.ZodType<
  TooManyRequestsMessage,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);
/** @internal */
export type TooManyRequestsMessage$Outbound = string | Array<string>;

/** @internal */
export const TooManyRequestsMessage$outboundSchema: z.ZodType<
  TooManyRequestsMessage$Outbound,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

export function tooManyRequestsMessageToJSON(
  tooManyRequestsMessage: TooManyRequestsMessage,
): string {
  return JSON.stringify(
    TooManyRequestsMessage$outboundSchema.parse(tooManyRequestsMessage),
  );
}
export function tooManyRequestsMessageFromJSON(
  jsonString: string,
): SafeParseResult<TooManyRequestsMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TooManyRequestsMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TooManyRequestsMessage' from JSON`,
  );
}

/** @internal */
export const TooManyRequestsError$inboundSchema: z.ZodType<
  TooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.union([z.string(), z.array(z.string())]),
  statusCode: z.number(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new TooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type TooManyRequestsError$Outbound = {
  message: string | Array<string>;
  statusCode: number;
  error: string;
};

/** @internal */
export const TooManyRequestsError$outboundSchema: z.ZodType<
  TooManyRequestsError$Outbound,
  z.ZodTypeDef,
  TooManyRequestsError
> = z.instanceof(TooManyRequestsError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.union([z.string(), z.array(z.string())]),
    statusCode: z.number(),
    error: z.string(),
  }));
