// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type ServiceUnavailableError struct {
	// The error message describing the reason for the exception
	Message components.ServiceUnavailableMessage `json:"message"`
	// The HTTP status code of the response
	StatusCode float64 `json:"statusCode"`
	// The type of error
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ServiceUnavailableError{}

func (e *ServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
