export { bls, secp256k1, utils } from "@avalabs/avalanchejs";
export { utf8ToBytes } from "@noble/hashes/utils";
export {
  buildRequest,
  /** @deprecated Use `ccipRequest`. */
  ccipRequest as ccipFetch,
  ccipRequest,
  offchainLookup,
  offchainLookupAbiItem,
  offchainLookupSignature,
  type OffchainLookupErrorType,
  type RequestErrorType,
} from "viem/utils";
export {
  avaxToNanoAvax,
  avaxToWei,
  nanoAvaxToAvax,
  nanoAvaxToWei,
  weiToAvax,
  weiToNanoAvax,
} from "../methods/wallet/utils.js";
export { buildUtxoBytes } from "./buildUtxoBytes.js";
export { CB58ToHex, hexToCB58 } from "./common.js";
export { getTxFromBytes, getUnsignedTxFromBytes } from "./getTxFromBytes.js";
export { getUtxoFromBytes } from "./getUtxoFromBytes.js";
export {
  getUtxosForAddress,
  type GetUtxosForAddressParams,
} from "./getUtxosForAddress.js";
export { removeChecksum } from "./removeChecksum.js";

export {
  assertCurrentChain,
  defineChain,
  extractChain,
  getChainContractAddress,
  type AssertCurrentChainErrorType,
  type AssertCurrentChainParameters,
  type ExtractChainErrorType,
  type ExtractChainParameters,
  type ExtractChainReturnType,
  type GetChainContractAddressErrorType,
} from "viem/utils";

export { arrayRegex, bytesRegex, integerRegex } from "viem/utils";

export {
  assertRequest,
  assertTransactionEIP1559,
  assertTransactionEIP2930,
  assertTransactionLegacy,
  boolToBytes,
  boolToHex,
  bytesToBigInt,
  bytesToBigInt as bytesToBigint,
  bytesToBool,
  bytesToHex,
  bytesToNumber,
  bytesToString,
  concat,
  concatBytes,
  concatHex,
  containsNodeError,
  createNonceManager,
  decodeAbiParameters,
  decodeErrorResult,
  decodeEventLog,
  decodeFunctionData,
  decodeFunctionResult,
  defineBlock,
  defineFormatter,
  defineTransaction,
  defineTransactionReceipt,
  defineTransactionRequest,
  encodeAbiParameters,
  encodeDeployData,
  encodeErrorResult,
  encodeEventTopics,
  encodeFunctionData,
  encodeFunctionResult,
  encodePacked,
  extract,
  formatAbiItem,
  formatAbiItemWithArgs,
  formatAbiParams,
  formatBlock,
  formatEther,
  formatGwei,
  formatLog,
  formatTransaction,
  formatTransactionRequest,
  formatUnits,
  fromBytes,
  fromHex,
  fromRlp,
  getAbiItem,
  getAction,
  getAddress,
  getCallError,
  getContractAddress,
  getContractError,
  getCreate2Address,
  getCreateAddress,
  getEstimateGasError,
  /** @deprecated use `toEventSelector`. */
  toEventSelector as getEventSelector,
  /** @deprecated use `toEventSignature`. */
  toEventSignature as getEventSignature,
  /** @deprecated use `toFunctionSelector`. */
  toFunctionSelector as getFunctionSelector,
  /** @deprecated use `toFunctionSignature`. */
  toFunctionSignature as getFunctionSignature,
  getHttpRpcClient,
  getNodeError,
  getSerializedTransactionType,
  getSocket,
  getSocketRpcClient,
  getTransactionError,
  getTransactionType,
  getWebSocketRpcClient,
  hashAuthorization,
  hashMessage,
  hashStruct,
  hashTypedData,
  hexToBigInt,
  hexToBool,
  hexToBytes,
  hexToNumber,
  hexToString,
  isAddress,
  isAddressEqual,
  isBytes,
  isErc6492Signature,
  isHash,
  isHex,
  keccak256,
  nonceManager,
  numberToBytes,
  numberToHex,
  pad,
  padBytes,
  padHex,
  parseAbi,
  parseAbiItem,
  parseAbiParameter,
  parseAbiParameters,
  parseAccount,
  parseErc6492Signature,
  parseEther,
  parseEventLogs,
  parseGwei,
  parseTransaction,
  parseUnits,
  publicKeyToAddress,
  recoverAddress,
  recoverAuthorizationAddress,
  recoverMessageAddress,
  recoverPublicKey,
  recoverTypedDataAddress,
  ripemd160,
  rpc,
  serializeAccessList,
  serializeAuthorizationList,
  serializeErc6492Signature,
  serializeTransaction,
  serializeTypedData,
  sha256,
  size,
  slice,
  sliceBytes,
  sliceHex,
  socketClientCache,
  stringify,
  stringToBytes,
  stringToHex,
  toBytes,
  toEventHash,
  toEventSelector,
  toEventSignature,
  toFunctionHash,
  toFunctionSelector,
  toFunctionSignature,
  toHex,
  toRlp,
  transactionType,
  trim,
  validateTypedData,
  verifyAuthorization,
  verifyHash,
  verifyMessage,
  verifyTypedData,
  type AssertEndOffsetErrorType,
  type AssertRequestErrorType,
  type AssertSizeErrorType,
  type AssertStartOffsetErrorType,
  type AssertTransactionEIP1559ErrorType,
  type AssertTransactionEIP2930ErrorType,
  type AssertTransactionLegacyErrorType,
  type BoolToBytesErrorType,
  type BoolToBytesOpts,
  type BoolToHexErrorType,
  type BoolToHexOpts,
  type BytesToBigIntErrorType,
  type BytesToBigIntOpts,
  type BytesToBoolErrorType,
  type BytesToBoolOpts,
  type BytesToHexErrorType,
  type BytesToHexOpts,
  type BytesToNumberErrorType,
  type BytesToNumberOpts,
  type BytesToRlpErrorType,
  type BytesToStringErrorType,
  type BytesToStringOpts,
  type ChecksumAddressErrorType,
  type ConcatBytesErrorType,
  type ConcatErrorType,
  type ConcatHexErrorType,
  type CreateNonceManagerParameters,
  type DecodeAbiParametersErrorType,
  type DecodeAbiParametersReturnType,
  type DecodeErrorResultErrorType,
  type DecodeErrorResultParameters,
  type DecodeErrorResultReturnType,
  type DecodeEventLogErrorType,
  type DecodeEventLogParameters,
  type DecodeEventLogReturnType,
  type DecodeFunctionDataErrorType,
  type DecodeFunctionDataParameters,
  type DecodeFunctionDataReturnType,
  type DecodeFunctionResultErrorType,
  type DecodeFunctionResultParameters,
  type DecodeFunctionResultReturnType,
  type DefineBlockErrorType,
  type DefineFormatterErrorType,
  type DefineTransactionErrorType,
  type DefineTransactionReceiptErrorType,
  type DefineTransactionRequestErrorType,
  type DomainSeparatorErrorType,
  type EncodeAbiParametersErrorType,
  type EncodeAbiParametersReturnType,
  type EncodeArgErrorType,
  type EncodeDeployDataErrorType,
  type EncodeDeployDataParameters,
  type EncodeErrorResultErrorType,
  type EncodeErrorResultParameters,
  type EncodeEventTopicsParameters,
  type EncodeEventTopicsReturnType,
  type EncodeFunctionDataErrorType,
  type EncodeFunctionDataParameters,
  type EncodeFunctionResultErrorType,
  type EncodeFunctionResultParameters,
  type EncodePackedErrorType,
  type ExtractErrorType,
  type FormatAbiItemErrorType,
  type FormatAbiItemWithArgsErrorType,
  type FormatAbiParamErrorType,
  type FormatAbiParamsErrorType,
  type FormatBlockErrorType,
  type FormatEtherErrorType,
  type FormatGweiErrorType,
  type FormatLogErrorType,
  type FormattedBlock,
  type FormattedTransaction,
  type FormattedTransactionReceipt,
  type FormattedTransactionRequest,
  type FormatTransactionErrorType,
  type FormatTransactionReceiptErrorType,
  type FormatTransactionRequestErrorType,
  type FormatUnitsErrorType,
  type FromBytesErrorType,
  type FromBytesParameters,
  type FromBytesReturnType,
  type FromHexErrorType,
  type FromHexParameters,
  type FromHexReturnType,
  type FromRlpErrorType,
  type GetAbiItemErrorType,
  type GetAbiItemParameters,
  type GetCallErrorReturnType,
  type GetContractAddressOptions,
  type GetContractErrorReturnType,
  type GetCreate2AddressErrorType,
  type GetCreate2AddressOptions,
  type GetCreateAddressErrorType,
  type GetCreateAddressOptions,
  type GetEstimateGasErrorReturnType,
  /** @deprecated use `ToEventSelectorErrorType`. */
  type ToEventSelectorErrorType as GetEventSelectorErrorType,
  /** @deprecated use `ToEventSignatureErrorType`. */
  type ToEventSignatureErrorType as GetEventSignatureErrorType,
  /** @deprecated use `ToFunctionSelectorErrorType`. */
  type ToFunctionSelectorErrorType as GetFunctionSelectorErrorType,
  /** @deprecated use `ToFunctionSignatureErrorType`. */
  type ToFunctionSignatureErrorType as GetFunctionSignatureErrorType,
  type GetNodeErrorParameters,
  type GetNodeErrorReturnType,
  type GetSerializedTransactionType,
  type GetSerializedTransactionTypeErrorType,
  type GetSocketParameters,
  type GetSocketRpcClientErrorType,
  type GetSocketRpcClientParameters,
  type GetTransactionErrorParameters,
  type GetTransactionErrorReturnType,
  type GetTransactionType,
  type GetTransactionTypeErrorType,
  type HashAuthorizationErrorType,
  type HashAuthorizationParameters,
  type HashAuthorizationReturnType,
  type HashDomainErrorType,
  type HashMessageErrorType,
  type HashMessageReturnType,
  type HashStructErrorType,
  type HashTypedDataParameters,
  type HashTypedDataReturnType,
  type HexToBigIntErrorType,
  type HexToBigIntOpts,
  type HexToBoolErrorType,
  type HexToBoolOpts,
  type HexToBytesErrorType,
  type HexToBytesOpts,
  type HexToNumberErrorType,
  type HexToNumberOpts,
  type HexToRlpErrorType,
  type HexToStringErrorType,
  type HexToStringOpts,
  type HttpRequestErrorType,
  type HttpRequestParameters,
  type HttpRequestReturnType,
  type HttpRpcClient,
  type HttpRpcClientOptions,
  type IsAddressEqualErrorType,
  type IsAddressErrorType,
  type IsBytesErrorType,
  type IsErc6492SignatureErrorType,
  type IsErc6492SignatureParameters,
  type IsErc6492SignatureReturnType,
  type IsHashErrorType,
  type IsHexErrorType,
  type Keccak256ErrorType,
  type NonceManager,
  type NonceManagerSource,
  type NumberToBytesErrorType,
  type NumberToHexErrorType,
  type NumberToHexOpts,
  type PadBytesErrorType,
  type PadErrorType,
  type PadHexErrorType,
  type ParseAbi,
  type ParseAbiItem,
  type ParseAbiParameter,
  type ParseAbiParameters,
  type ParseAccountErrorType,
  type ParseErc6492SignatureErrorType,
  type ParseErc6492SignatureParameters,
  type ParseErc6492SignatureReturnType,
  type ParseEtherErrorType,
  type ParseEventLogsErrorType,
  type ParseEventLogsParameters,
  type ParseEventLogsReturnType,
  type ParseGweiErrorType,
  type ParseTransactionErrorType,
  type ParseUnitsErrorType,
  type PublicKeyToAddressErrorType,
  type RecoverAddressErrorType,
  type RecoverAddressParameters,
  type RecoverAddressReturnType,
  type RecoverAuthorizationAddressErrorType,
  type RecoverAuthorizationAddressParameters,
  type RecoverAuthorizationAddressReturnType,
  type RecoverMessageAddressErrorType,
  type RecoverMessageAddressParameters,
  type RecoverMessageAddressReturnType,
  type RecoverPublicKeyErrorType,
  type RecoverPublicKeyParameters,
  type RecoverPublicKeyReturnType,
  type RecoverTypedDataAddressErrorType,
  type RecoverTypedDataAddressParameters,
  type RecoverTypedDataAddressReturnType,
  type Ripemd160ErrorType,
  type SerializeAccessListErrorType,
  type SerializeAuthorizationListErrorType,
  type SerializeAuthorizationListReturnType,
  type SerializeErc6492SignatureErrorType,
  type SerializeErc6492SignatureParameters,
  type SerializeErc6492SignatureReturnType,
  type SerializeTransactionErrorType,
  type SerializeTransactionFn,
  type SerializeTypedDataErrorType,
  type Sha256ErrorType,
  type SizeErrorType,
  type SliceBytesErrorType,
  type SliceErrorType,
  type SliceHexErrorType,
  type SliceReturnType,
  type Socket,
  type SocketRpcClient,
  type StringifyErrorType,
  type StringToBytesErrorType,
  type StringToBytesOpts,
  type StringToHexErrorType,
  type StringToHexOpts,
  type ToBytesErrorType,
  type ToBytesParameters,
  type ToEventHashErrorType,
  type ToEventSelectorErrorType,
  type ToEventSignatureErrorType,
  type ToFunctionHashErrorType,
  type ToFunctionSelectorErrorType,
  type ToFunctionSignatureErrorType,
  type ToHexErrorType,
  type ToHexParameters,
  type ToRlpErrorType,
  type ToRlpReturnType,
  type TrimErrorType,
  type TrimReturnType,
  type ValidateTypedDataErrorType,
  type VerifyAuthorizationErrorType,
  type VerifyAuthorizationParameters,
  type VerifyAuthorizationReturnType,
  type VerifyHashErrorType,
  type VerifyHashParameters,
  type VerifyHashReturnType,
  type VerifyMessageErrorType,
  type VerifyMessageParameters,
  type VerifyMessageReturnType,
  type VerifyTypedDataErrorType,
  type VerifyTypedDataParameters,
  type VerifyTypedDataReturnType,
  type WebSocketAsyncErrorType,
  type WebSocketAsyncOptions,
  type WebSocketAsyncReturnType,
  type WebSocketErrorType,
  type WebSocketOptions,
  type WebSocketReturnType,
} from "viem/utils";
