// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type APIFeature string

const (
	APIFeatureNftIndexing APIFeature = "nftIndexing"
	APIFeatureWebhooks    APIFeature = "webhooks"
	APIFeatureTeleporter  APIFeature = "teleporter"
)

func (e APIFeature) ToPointer() *APIFeature {
	return &e
}
func (e *APIFeature) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "nftIndexing":
		fallthrough
	case "webhooks":
		fallthrough
	case "teleporter":
		*e = APIFeature(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIFeature: %v", v)
	}
}
