// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type BadRequestMessageType string

const (
	BadRequestMessageTypeStr        BadRequestMessageType = "str"
	BadRequestMessageTypeArrayOfStr BadRequestMessageType = "arrayOfStr"
)

// BadRequestMessage - The error message describing the reason for the exception
type BadRequestMessage struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type BadRequestMessageType
}

func CreateBadRequestMessageStr(str string) BadRequestMessage {
	typ := BadRequestMessageTypeStr

	return BadRequestMessage{
		Str:  &str,
		Type: typ,
	}
}

func CreateBadRequestMessageArrayOfStr(arrayOfStr []string) BadRequestMessage {
	typ := BadRequestMessageTypeArrayOfStr

	return BadRequestMessage{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *BadRequestMessage) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = BadRequestMessageTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, true); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = BadRequestMessageTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BadRequestMessage", string(data))
}

func (u BadRequestMessage) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type BadRequestMessage: all fields are null")
}
