// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BlockchainID string

const (
	BlockchainIDElevenNonillionOneHundredAndElevenOctillionOneHundredAndElevenSeptillionOneHundredAndElevenSextillionOneHundredAndElevenQuintillionOneHundredAndElevenQuadrillionOneHundredAndElevenTrillionOneHundredAndElevenBillionOneHundredAndElevenMillionOneHundredAndElevenThousandOneHundredAndElevenLpoYy BlockchainID = "11111111111111111111111111111111LpoYY"
	BlockchainIDTwooYmbnv4eNHyqk2fjjV5nVqlDbtmNJzq5s3qs3Lo6ftnC6FByM                                                                                                                                                                                                                                                BlockchainID = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM"
	BlockchainIDTwoJvsBoinj9C2J33VntvzYtVjnZdN2NKiwwKjcumHuwEb5DbBrm                                                                                                                                                                                                                                                BlockchainID = "2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm"
	BlockchainIDTwopiQ2AvhCjnduiWXsSy15DtbVuwHe2cwMhYnExHsLl73BBkdbV                                                                                                                                                                                                                                                BlockchainID = "2piQ2AVHCjnduiWXsSY15DtbVuwHE2cwMHYnEXHsLL73BBkdbV"
	BlockchainIDTwoq9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAx5UQxse55x1Q5                                                                                                                                                                                                                                                 BlockchainID = "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5"
	BlockchainIDYh8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QyNfcdoS6k6HWp                                                                                                                                                                                                                                                   BlockchainID = "yH8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QYNfcdoS6k6HWp"
	BlockchainIDVv3cui1DsEpc3nLcgh9rorwo8s6BYxM2Hz4Qfe5gEYjwTqAu                                                                                                                                                                                                                                                    BlockchainID = "vV3cui1DsEPC3nLCGH9rorwo8s6BYxM2Hz4QFE5gEYjwTqAu"
	BlockchainIDPChain                                                                                                                                                                                                                                                                                              BlockchainID = "p-chain"
	BlockchainIDXChain                                                                                                                                                                                                                                                                                              BlockchainID = "x-chain"
	BlockchainIDCChain                                                                                                                                                                                                                                                                                              BlockchainID = "c-chain"
)

func (e BlockchainID) ToPointer() *BlockchainID {
	return &e
}
func (e *BlockchainID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "11111111111111111111111111111111LpoYY":
		fallthrough
	case "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM":
		fallthrough
	case "2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm":
		fallthrough
	case "2piQ2AVHCjnduiWXsSY15DtbVuwHE2cwMHYnEXHsLL73BBkdbV":
		fallthrough
	case "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5":
		fallthrough
	case "yH8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QYNfcdoS6k6HWp":
		fallthrough
	case "vV3cui1DsEPC3nLCGH9rorwo8s6BYxM2Hz4QFE5gEYjwTqAu":
		fallthrough
	case "p-chain":
		fallthrough
	case "x-chain":
		fallthrough
	case "c-chain":
		*e = BlockchainID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BlockchainID: %v", v)
	}
}
