// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BlockchainGenesisData - The genesis data of the blockchain.
type BlockchainGenesisData struct {
}

type Blockchain struct {
	CreateBlockTimestamp float64 `json:"createBlockTimestamp"`
	CreateBlockNumber    string  `json:"createBlockNumber"`
	BlockchainID         string  `json:"blockchainId"`
	VMID                 string  `json:"vmId"`
	SubnetID             string  `json:"subnetId"`
	BlockchainName       string  `json:"blockchainName"`
	// EVM Chain ID for the EVM-based chains. This field is extracted from genesis data, and may be present for non-EVM chains as well.
	EvmChainID float64 `json:"evmChainId"`
	// The genesis data of the blockchain.
	GenesisData *BlockchainGenesisData `json:"genesisData,omitempty"`
}

func (o *Blockchain) GetCreateBlockTimestamp() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreateBlockTimestamp
}

func (o *Blockchain) GetCreateBlockNumber() string {
	if o == nil {
		return ""
	}
	return o.CreateBlockNumber
}

func (o *Blockchain) GetBlockchainID() string {
	if o == nil {
		return ""
	}
	return o.BlockchainID
}

func (o *Blockchain) GetVMID() string {
	if o == nil {
		return ""
	}
	return o.VMID
}

func (o *Blockchain) GetSubnetID() string {
	if o == nil {
		return ""
	}
	return o.SubnetID
}

func (o *Blockchain) GetBlockchainName() string {
	if o == nil {
		return ""
	}
	return o.BlockchainName
}

func (o *Blockchain) GetEvmChainID() float64 {
	if o == nil {
		return 0.0
	}
	return o.EvmChainID
}

func (o *Blockchain) GetGenesisData() *BlockchainGenesisData {
	if o == nil {
		return nil
	}
	return o.GenesisData
}
