// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CChainImportTransactionTxType - Type of transaction.
type CChainImportTransactionTxType string

const (
	CChainImportTransactionTxTypeImportTx CChainImportTransactionTxType = "ImportTx"
)

func (e CChainImportTransactionTxType) ToPointer() *CChainImportTransactionTxType {
	return &e
}
func (e *CChainImportTransactionTxType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ImportTx":
		*e = CChainImportTransactionTxType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CChainImportTransactionTxType: %v", v)
	}
}

type CChainImportTransaction struct {
	// Unique ID for this transaction.
	TxHash string `json:"txHash"`
	// Height of the block this transaction belongs to.
	BlockHeight float64 `json:"blockHeight"`
	// Hash of the block this transaction belongs to.
	BlockHash string `json:"blockHash"`
	// Latest timestamp in seconds this transaction was accepted.
	Timestamp float64 `json:"timestamp"`
	// Hex encoded memo bytes for this transaction.
	Memo string `json:"memo"`
	// Assets unlocked by inputs of this transaction.
	AmountUnlocked []AssetAmount `json:"amountUnlocked"`
	// Assets created by outputs of this transaction.
	AmountCreated []AssetAmount `json:"amountCreated"`
	// Source chain for an atomic transaction.
	SourceChain string `json:"sourceChain"`
	// Destination chain for an atomic transaction.
	DestinationChain string `json:"destinationChain"`
	// Type of transaction.
	TxType        CChainImportTransactionTxType `json:"txType"`
	EvmOutputs    []EVMOutput                   `json:"evmOutputs"`
	ConsumedUtxos []Utxo                        `json:"consumedUtxos"`
}

func (o *CChainImportTransaction) GetTxHash() string {
	if o == nil {
		return ""
	}
	return o.TxHash
}

func (o *CChainImportTransaction) GetBlockHeight() float64 {
	if o == nil {
		return 0.0
	}
	return o.BlockHeight
}

func (o *CChainImportTransaction) GetBlockHash() string {
	if o == nil {
		return ""
	}
	return o.BlockHash
}

func (o *CChainImportTransaction) GetTimestamp() float64 {
	if o == nil {
		return 0.0
	}
	return o.Timestamp
}

func (o *CChainImportTransaction) GetMemo() string {
	if o == nil {
		return ""
	}
	return o.Memo
}

func (o *CChainImportTransaction) GetAmountUnlocked() []AssetAmount {
	if o == nil {
		return []AssetAmount{}
	}
	return o.AmountUnlocked
}

func (o *CChainImportTransaction) GetAmountCreated() []AssetAmount {
	if o == nil {
		return []AssetAmount{}
	}
	return o.AmountCreated
}

func (o *CChainImportTransaction) GetSourceChain() string {
	if o == nil {
		return ""
	}
	return o.SourceChain
}

func (o *CChainImportTransaction) GetDestinationChain() string {
	if o == nil {
		return ""
	}
	return o.DestinationChain
}

func (o *CChainImportTransaction) GetTxType() CChainImportTransactionTxType {
	if o == nil {
		return CChainImportTransactionTxType("")
	}
	return o.TxType
}

func (o *CChainImportTransaction) GetEvmOutputs() []EVMOutput {
	if o == nil {
		return []EVMOutput{}
	}
	return o.EvmOutputs
}

func (o *CChainImportTransaction) GetConsumedUtxos() []Utxo {
	if o == nil {
		return []Utxo{}
	}
	return o.ConsumedUtxos
}
