// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChainAddressChainIDMapListResponse struct {
	Addresses []ChainAddressChainIDMap `json:"addresses"`
}

func (o *ChainAddressChainIDMapListResponse) GetAddresses() []ChainAddressChainIDMap {
	if o == nil {
		return []ChainAddressChainIDMap{}
	}
	return o.Addresses
}
