// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePrimaryNetworkTransactionExportRequest struct {
	Type      PrimaryNetworkOperationType `json:"type"`
	FirstDate *string                     `json:"firstDate,omitempty"`
	LastDate  *string                     `json:"lastDate,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	StartDate *string `json:"startDate,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EndDate *string               `json:"endDate,omitempty"`
	Options PrimaryNetworkOptions `json:"options"`
}

func (o *CreatePrimaryNetworkTransactionExportRequest) GetType() PrimaryNetworkOperationType {
	if o == nil {
		return PrimaryNetworkOperationType("")
	}
	return o.Type
}

func (o *CreatePrimaryNetworkTransactionExportRequest) GetFirstDate() *string {
	if o == nil {
		return nil
	}
	return o.FirstDate
}

func (o *CreatePrimaryNetworkTransactionExportRequest) GetLastDate() *string {
	if o == nil {
		return nil
	}
	return o.LastDate
}

func (o *CreatePrimaryNetworkTransactionExportRequest) GetStartDate() *string {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *CreatePrimaryNetworkTransactionExportRequest) GetEndDate() *string {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *CreatePrimaryNetworkTransactionExportRequest) GetOptions() PrimaryNetworkOptions {
	if o == nil {
		return PrimaryNetworkOptions{}
	}
	return o.Options
}
