// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DelegationStatusType string

const (
	DelegationStatusTypeCompleted DelegationStatusType = "completed"
	DelegationStatusTypeActive    DelegationStatusType = "active"
	DelegationStatusTypePending   DelegationStatusType = "pending"
)

func (e DelegationStatusType) ToPointer() *DelegationStatusType {
	return &e
}
func (e *DelegationStatusType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "completed":
		fallthrough
	case "active":
		fallthrough
	case "pending":
		*e = DelegationStatusType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DelegationStatusType: %v", v)
	}
}
