// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DelegatorsDetails struct {
	DelegatorCount    float64 `json:"delegatorCount"`
	TotalAmountStaked string  `json:"totalAmountStaked"`
}

func (o *DelegatorsDetails) GetDelegatorCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.DelegatorCount
}

func (o *DelegatorsDetails) GetTotalAmountStaked() string {
	if o == nil {
		return ""
	}
	return o.TotalAmountStaked
}
