// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Erc1155ContractErcType string

const (
	Erc1155ContractErcTypeErc1155 Erc1155ContractErcType = "ERC-1155"
)

func (e Erc1155ContractErcType) ToPointer() *Erc1155ContractErcType {
	return &e
}
func (e *Erc1155ContractErcType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ERC-1155":
		*e = Erc1155ContractErcType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Erc1155ContractErcType: %v", v)
	}
}

type Erc1155Contract struct {
	// The contract name.
	Name          *string        `json:"name,omitempty"`
	Description   *string        `json:"description,omitempty"`
	OfficialSite  *string        `json:"officialSite,omitempty"`
	Email         *string        `json:"email,omitempty"`
	LogoAsset     *ImageAsset    `json:"logoAsset,omitempty"`
	BannerAsset   *ImageAsset    `json:"bannerAsset,omitempty"`
	Color         *string        `json:"color,omitempty"`
	ResourceLinks []ResourceLink `json:"resourceLinks,omitempty"`
	Tags          []string       `json:"tags,omitempty"`
	// A wallet or contract address in mixed-case checksum encoding.
	Address           string                     `json:"address"`
	DeploymentDetails *ContractDeploymentDetails `json:"deploymentDetails,omitempty"`
	ErcType           Erc1155ContractErcType     `json:"ercType"`
	// The contract symbol.
	Symbol           *string           `json:"symbol,omitempty"`
	PricingProviders *PricingProviders `json:"pricingProviders,omitempty"`
}

func (o *Erc1155Contract) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Erc1155Contract) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Erc1155Contract) GetOfficialSite() *string {
	if o == nil {
		return nil
	}
	return o.OfficialSite
}

func (o *Erc1155Contract) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Erc1155Contract) GetLogoAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.LogoAsset
}

func (o *Erc1155Contract) GetBannerAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.BannerAsset
}

func (o *Erc1155Contract) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *Erc1155Contract) GetResourceLinks() []ResourceLink {
	if o == nil {
		return nil
	}
	return o.ResourceLinks
}

func (o *Erc1155Contract) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Erc1155Contract) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *Erc1155Contract) GetDeploymentDetails() *ContractDeploymentDetails {
	if o == nil {
		return nil
	}
	return o.DeploymentDetails
}

func (o *Erc1155Contract) GetErcType() Erc1155ContractErcType {
	if o == nil {
		return Erc1155ContractErcType("")
	}
	return o.ErcType
}

func (o *Erc1155Contract) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}

func (o *Erc1155Contract) GetPricingProviders() *PricingProviders {
	if o == nil {
		return nil
	}
	return o.PricingProviders
}
