// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Erc20ContractErcType string

const (
	Erc20ContractErcTypeErc20 Erc20ContractErcType = "ERC-20"
)

func (e Erc20ContractErcType) ToPointer() *Erc20ContractErcType {
	return &e
}
func (e *Erc20ContractErcType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ERC-20":
		*e = Erc20ContractErcType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Erc20ContractErcType: %v", v)
	}
}

type Erc20Contract struct {
	// The contract name.
	Name          *string        `json:"name,omitempty"`
	Description   *string        `json:"description,omitempty"`
	OfficialSite  *string        `json:"officialSite,omitempty"`
	Email         *string        `json:"email,omitempty"`
	LogoAsset     *ImageAsset    `json:"logoAsset,omitempty"`
	BannerAsset   *ImageAsset    `json:"bannerAsset,omitempty"`
	Color         *string        `json:"color,omitempty"`
	ResourceLinks []ResourceLink `json:"resourceLinks,omitempty"`
	Tags          []string       `json:"tags,omitempty"`
	// A wallet or contract address in mixed-case checksum encoding.
	Address           string                     `json:"address"`
	DeploymentDetails *ContractDeploymentDetails `json:"deploymentDetails,omitempty"`
	ErcType           Erc20ContractErcType       `json:"ercType"`
	// The contract symbol.
	Symbol *string `json:"symbol,omitempty"`
	// The number of decimals the token uses. For example `6`, means to divide the token amount by `1000000` to get its user representation.
	Decimals         float64           `json:"decimals"`
	PricingProviders *PricingProviders `json:"pricingProviders,omitempty"`
}

func (o *Erc20Contract) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Erc20Contract) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Erc20Contract) GetOfficialSite() *string {
	if o == nil {
		return nil
	}
	return o.OfficialSite
}

func (o *Erc20Contract) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Erc20Contract) GetLogoAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.LogoAsset
}

func (o *Erc20Contract) GetBannerAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.BannerAsset
}

func (o *Erc20Contract) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *Erc20Contract) GetResourceLinks() []ResourceLink {
	if o == nil {
		return nil
	}
	return o.ResourceLinks
}

func (o *Erc20Contract) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Erc20Contract) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *Erc20Contract) GetDeploymentDetails() *ContractDeploymentDetails {
	if o == nil {
		return nil
	}
	return o.DeploymentDetails
}

func (o *Erc20Contract) GetErcType() Erc20ContractErcType {
	if o == nil {
		return Erc20ContractErcType("")
	}
	return o.ErcType
}

func (o *Erc20Contract) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}

func (o *Erc20Contract) GetDecimals() float64 {
	if o == nil {
		return 0.0
	}
	return o.Decimals
}

func (o *Erc20Contract) GetPricingProviders() *PricingProviders {
	if o == nil {
		return nil
	}
	return o.PricingProviders
}
