// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Erc20TransferDetails struct {
	From       RichAddress `json:"from"`
	To         RichAddress `json:"to"`
	LogIndex   float64     `json:"logIndex"`
	Value      string      `json:"value"`
	Erc20Token Erc20Token  `json:"erc20Token"`
}

func (o *Erc20TransferDetails) GetFrom() RichAddress {
	if o == nil {
		return RichAddress{}
	}
	return o.From
}

func (o *Erc20TransferDetails) GetTo() RichAddress {
	if o == nil {
		return RichAddress{}
	}
	return o.To
}

func (o *Erc20TransferDetails) GetLogIndex() float64 {
	if o == nil {
		return 0.0
	}
	return o.LogIndex
}

func (o *Erc20TransferDetails) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *Erc20TransferDetails) GetErc20Token() Erc20Token {
	if o == nil {
		return Erc20Token{}
	}
	return o.Erc20Token
}
