// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Erc721TransferDetails struct {
	From        RichAddress `json:"from"`
	To          RichAddress `json:"to"`
	LogIndex    float64     `json:"logIndex"`
	Erc721Token Erc721Token `json:"erc721Token"`
}

func (o *Erc721TransferDetails) GetFrom() RichAddress {
	if o == nil {
		return RichAddress{}
	}
	return o.From
}

func (o *Erc721TransferDetails) GetTo() RichAddress {
	if o == nil {
		return RichAddress{}
	}
	return o.To
}

func (o *Erc721TransferDetails) GetLogIndex() float64 {
	if o == nil {
		return 0.0
	}
	return o.LogIndex
}

func (o *Erc721TransferDetails) GetErc721Token() Erc721Token {
	if o == nil {
		return Erc721Token{}
	}
	return o.Erc721Token
}
