// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Erc721ContractErcType string

const (
	Erc721ContractErcTypeErc721 Erc721ContractErcType = "ERC-721"
)

func (e Erc721ContractErcType) ToPointer() *Erc721ContractErcType {
	return &e
}
func (e *Erc721ContractErcType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ERC-721":
		*e = Erc721ContractErcType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Erc721ContractErcType: %v", v)
	}
}

type Erc721Contract struct {
	// The contract name.
	Name          *string        `json:"name,omitempty"`
	Description   *string        `json:"description,omitempty"`
	OfficialSite  *string        `json:"officialSite,omitempty"`
	Email         *string        `json:"email,omitempty"`
	LogoAsset     *ImageAsset    `json:"logoAsset,omitempty"`
	BannerAsset   *ImageAsset    `json:"bannerAsset,omitempty"`
	Color         *string        `json:"color,omitempty"`
	ResourceLinks []ResourceLink `json:"resourceLinks,omitempty"`
	Tags          []string       `json:"tags,omitempty"`
	// A wallet or contract address in mixed-case checksum encoding.
	Address           string                     `json:"address"`
	DeploymentDetails *ContractDeploymentDetails `json:"deploymentDetails,omitempty"`
	ErcType           Erc721ContractErcType      `json:"ercType"`
	// The contract symbol.
	Symbol *string `json:"symbol,omitempty"`
}

func (o *Erc721Contract) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Erc721Contract) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Erc721Contract) GetOfficialSite() *string {
	if o == nil {
		return nil
	}
	return o.OfficialSite
}

func (o *Erc721Contract) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Erc721Contract) GetLogoAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.LogoAsset
}

func (o *Erc721Contract) GetBannerAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.BannerAsset
}

func (o *Erc721Contract) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *Erc721Contract) GetResourceLinks() []ResourceLink {
	if o == nil {
		return nil
	}
	return o.ResourceLinks
}

func (o *Erc721Contract) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Erc721Contract) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *Erc721Contract) GetDeploymentDetails() *ContractDeploymentDetails {
	if o == nil {
		return nil
	}
	return o.DeploymentDetails
}

func (o *Erc721Contract) GetErcType() Erc721ContractErcType {
	if o == nil {
		return Erc721ContractErcType("")
	}
	return o.ErcType
}

func (o *Erc721Contract) GetSymbol() *string {
	if o == nil {
		return nil
	}
	return o.Symbol
}
