// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EVMInput struct {
	// EVM address from which the asset is exported in ExportTx.
	FromAddress string `json:"fromAddress"`
	// AssetAmount details for the asset being transferred.
	Asset AssetAmount `json:"asset"`
	// Credentials that signed this transaction.
	Credentials []UtxoCredential `json:"credentials"`
}

func (o *EVMInput) GetFromAddress() string {
	if o == nil {
		return ""
	}
	return o.FromAddress
}

func (o *EVMInput) GetAsset() AssetAmount {
	if o == nil {
		return AssetAmount{}
	}
	return o.Asset
}

func (o *EVMInput) GetCredentials() []UtxoCredential {
	if o == nil {
		return []UtxoCredential{}
	}
	return o.Credentials
}
