// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetNativeBalanceResponse struct {
	// The native token balance for the address.
	NativeTokenBalance NativeTokenBalance `json:"nativeTokenBalance"`
}

func (o *GetNativeBalanceResponse) GetNativeTokenBalance() NativeTokenBalance {
	if o == nil {
		return NativeTokenBalance{}
	}
	return o.NativeTokenBalance
}
