// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetNetworkDetailsResponse struct {
	ValidatorDetails ValidatorsDetails `json:"validatorDetails"`
	DelegatorDetails DelegatorsDetails `json:"delegatorDetails"`
}

func (o *GetNetworkDetailsResponse) GetValidatorDetails() ValidatorsDetails {
	if o == nil {
		return ValidatorsDetails{}
	}
	return o.ValidatorDetails
}

func (o *GetNetworkDetailsResponse) GetDelegatorDetails() DelegatorsDetails {
	if o == nil {
		return DelegatorsDetails{}
	}
	return o.DelegatorDetails
}
