// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetPrimaryNetworkBlockResponse struct {
	BlockNumber             string           `json:"blockNumber"`
	BlockHash               string           `json:"blockHash"`
	ParentHash              string           `json:"parentHash"`
	BlockTimestamp          float64          `json:"blockTimestamp"`
	BlockType               string           `json:"blockType"`
	TxCount                 float64          `json:"txCount"`
	Transactions            []string         `json:"transactions"`
	BlockSizeBytes          float64          `json:"blockSizeBytes"`
	L1ValidatorsAccruedFees *float64         `json:"l1ValidatorsAccruedFees,omitempty"`
	ActiveL1Validators      *float64         `json:"activeL1Validators,omitempty"`
	CurrentSupply           *string          `json:"currentSupply,omitempty"`
	ProposerDetails         *ProposerDetails `json:"proposerDetails,omitempty"`
}

func (o *GetPrimaryNetworkBlockResponse) GetBlockNumber() string {
	if o == nil {
		return ""
	}
	return o.BlockNumber
}

func (o *GetPrimaryNetworkBlockResponse) GetBlockHash() string {
	if o == nil {
		return ""
	}
	return o.BlockHash
}

func (o *GetPrimaryNetworkBlockResponse) GetParentHash() string {
	if o == nil {
		return ""
	}
	return o.ParentHash
}

func (o *GetPrimaryNetworkBlockResponse) GetBlockTimestamp() float64 {
	if o == nil {
		return 0.0
	}
	return o.BlockTimestamp
}

func (o *GetPrimaryNetworkBlockResponse) GetBlockType() string {
	if o == nil {
		return ""
	}
	return o.BlockType
}

func (o *GetPrimaryNetworkBlockResponse) GetTxCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.TxCount
}

func (o *GetPrimaryNetworkBlockResponse) GetTransactions() []string {
	if o == nil {
		return []string{}
	}
	return o.Transactions
}

func (o *GetPrimaryNetworkBlockResponse) GetBlockSizeBytes() float64 {
	if o == nil {
		return 0.0
	}
	return o.BlockSizeBytes
}

func (o *GetPrimaryNetworkBlockResponse) GetL1ValidatorsAccruedFees() *float64 {
	if o == nil {
		return nil
	}
	return o.L1ValidatorsAccruedFees
}

func (o *GetPrimaryNetworkBlockResponse) GetActiveL1Validators() *float64 {
	if o == nil {
		return nil
	}
	return o.ActiveL1Validators
}

func (o *GetPrimaryNetworkBlockResponse) GetCurrentSupply() *string {
	if o == nil {
		return nil
	}
	return o.CurrentSupply
}

func (o *GetPrimaryNetworkBlockResponse) GetProposerDetails() *ProposerDetails {
	if o == nil {
		return nil
	}
	return o.ProposerDetails
}
