// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ImageAsset struct {
	AssetID *string `json:"assetId,omitempty"`
	// OUTPUT ONLY
	ImageURI *string `json:"imageUri,omitempty"`
}

func (o *ImageAsset) GetAssetID() *string {
	if o == nil {
		return nil
	}
	return o.AssetID
}

func (o *ImageAsset) GetImageURI() *string {
	if o == nil {
		return nil
	}
	return o.ImageURI
}
