// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type L1ValidatorDetailsFullBlsCredentials struct {
}

type L1ValidatorDetailsFull struct {
	// Unique L1 validation ID used network-wide to identify L1 validation until its weight is reduced to 0 i.e. removed.
	ValidationID string `json:"validationId"`
	// Unique L1 validation ID used network-wide to identify L1 validation until its weight is reduced to 0 i.e. removed. In hex format
	ValidationIDHex string `json:"validationIdHex"`
	NodeID          string `json:"nodeId"`
	SubnetID        string `json:"subnetId"`
	// Weight of the L1 validator used while sampling validators within the L1. A zero-weight L1 validator means it has been removed from the L1, and the validationID is no longer valid
	Weight float64 `json:"weight"`
	// Remaining L1 validator balance in nAVAX until inactive. It can rejoin L1 sampling by increasing balance with IncreaseL1ValidatorBalanceTx
	RemainingBalance float64 `json:"remainingBalance"`
	// The timestamp of the transaction which created this L1 validator
	CreationTimestamp float64                              `json:"creationTimestamp"`
	BlsCredentials    L1ValidatorDetailsFullBlsCredentials `json:"blsCredentials"`
	// The L1 validator owner's balance, returned after it's disabled or removed
	RemainingBalanceOwner BalanceOwner `json:"remainingBalanceOwner"`
	// Owner ddresses details which can disable or remove the L1 validator
	DeactivationOwner BalanceOwner `json:"deactivationOwner"`
}

func (o *L1ValidatorDetailsFull) GetValidationID() string {
	if o == nil {
		return ""
	}
	return o.ValidationID
}

func (o *L1ValidatorDetailsFull) GetValidationIDHex() string {
	if o == nil {
		return ""
	}
	return o.ValidationIDHex
}

func (o *L1ValidatorDetailsFull) GetNodeID() string {
	if o == nil {
		return ""
	}
	return o.NodeID
}

func (o *L1ValidatorDetailsFull) GetSubnetID() string {
	if o == nil {
		return ""
	}
	return o.SubnetID
}

func (o *L1ValidatorDetailsFull) GetWeight() float64 {
	if o == nil {
		return 0.0
	}
	return o.Weight
}

func (o *L1ValidatorDetailsFull) GetRemainingBalance() float64 {
	if o == nil {
		return 0.0
	}
	return o.RemainingBalance
}

func (o *L1ValidatorDetailsFull) GetCreationTimestamp() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreationTimestamp
}

func (o *L1ValidatorDetailsFull) GetBlsCredentials() L1ValidatorDetailsFullBlsCredentials {
	if o == nil {
		return L1ValidatorDetailsFullBlsCredentials{}
	}
	return o.BlsCredentials
}

func (o *L1ValidatorDetailsFull) GetRemainingBalanceOwner() BalanceOwner {
	if o == nil {
		return BalanceOwner{}
	}
	return o.RemainingBalanceOwner
}

func (o *L1ValidatorDetailsFull) GetDeactivationOwner() BalanceOwner {
	if o == nil {
		return BalanceOwner{}
	}
	return o.DeactivationOwner
}
