// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListPChainUtxosResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string                 `json:"nextPageToken,omitempty"`
	Utxos         []PChainUtxo            `json:"utxos"`
	ChainInfo     PrimaryNetworkChainInfo `json:"chainInfo"`
}

func (o *ListPChainUtxosResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListPChainUtxosResponse) GetUtxos() []PChainUtxo {
	if o == nil {
		return []PChainUtxo{}
	}
	return o.Utxos
}

func (o *ListPChainUtxosResponse) GetChainInfo() PrimaryNetworkChainInfo {
	if o == nil {
		return PrimaryNetworkChainInfo{}
	}
	return o.ChainInfo
}
