// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListPrimaryNetworkBlocksResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string                 `json:"nextPageToken,omitempty"`
	Blocks        []PrimaryNetworkBlock   `json:"blocks"`
	ChainInfo     PrimaryNetworkChainInfo `json:"chainInfo"`
}

func (o *ListPrimaryNetworkBlocksResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListPrimaryNetworkBlocksResponse) GetBlocks() []PrimaryNetworkBlock {
	if o == nil {
		return []PrimaryNetworkBlock{}
	}
	return o.Blocks
}

func (o *ListPrimaryNetworkBlocksResponse) GetChainInfo() PrimaryNetworkChainInfo {
	if o == nil {
		return PrimaryNetworkChainInfo{}
	}
	return o.ChainInfo
}
