// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListErc721BalancesResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The native token balance for the address.
	NativeTokenBalance NativeTokenBalance `json:"nativeTokenBalance"`
	// The list of ERC-721 token balances for the address.
	Erc721TokenBalances []Erc721TokenBalance `json:"erc721TokenBalances"`
}

func (o *ListErc721BalancesResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListErc721BalancesResponse) GetNativeTokenBalance() NativeTokenBalance {
	if o == nil {
		return NativeTokenBalance{}
	}
	return o.NativeTokenBalance
}

func (o *ListErc721BalancesResponse) GetErc721TokenBalances() []Erc721TokenBalance {
	if o == nil {
		return []Erc721TokenBalance{}
	}
	return o.Erc721TokenBalances
}
