// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListTransactionDetailsResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string              `json:"nextPageToken,omitempty"`
	Transactions  []TransactionDetails `json:"transactions"`
}

func (o *ListTransactionDetailsResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListTransactionDetailsResponse) GetTransactions() []TransactionDetails {
	if o == nil {
		return []TransactionDetails{}
	}
	return o.Transactions
}
