// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListBlockchainsResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string      `json:"nextPageToken,omitempty"`
	Blockchains   []Blockchain `json:"blockchains"`
}

func (o *ListBlockchainsResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListBlockchainsResponse) GetBlockchains() []Blockchain {
	if o == nil {
		return []Blockchain{}
	}
	return o.Blockchains
}
