// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListErc1155BalancesResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The native token balance for the address.
	NativeTokenBalance NativeTokenBalance `json:"nativeTokenBalance"`
	// The list of ERC-1155 token balances for the address.
	Erc1155TokenBalances []Erc1155TokenBalance `json:"erc1155TokenBalances"`
}

func (o *ListErc1155BalancesResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListErc1155BalancesResponse) GetNativeTokenBalance() NativeTokenBalance {
	if o == nil {
		return NativeTokenBalance{}
	}
	return o.NativeTokenBalance
}

func (o *ListErc1155BalancesResponse) GetErc1155TokenBalances() []Erc1155TokenBalance {
	if o == nil {
		return []Erc1155TokenBalance{}
	}
	return o.Erc1155TokenBalances
}
