// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListCChainAtomicBalancesResponse struct {
	Balances  CChainAtomicBalances    `json:"balances"`
	ChainInfo PrimaryNetworkChainInfo `json:"chainInfo"`
}

func (o *ListCChainAtomicBalancesResponse) GetBalances() CChainAtomicBalances {
	if o == nil {
		return CChainAtomicBalances{}
	}
	return o.Balances
}

func (o *ListCChainAtomicBalancesResponse) GetChainInfo() PrimaryNetworkChainInfo {
	if o == nil {
		return PrimaryNetworkChainInfo{}
	}
	return o.ChainInfo
}
