// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListUtxosResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string                 `json:"nextPageToken,omitempty"`
	Utxos         []Utxo                  `json:"utxos"`
	ChainInfo     PrimaryNetworkChainInfo `json:"chainInfo"`
}

func (o *ListUtxosResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListUtxosResponse) GetUtxos() []Utxo {
	if o == nil {
		return []Utxo{}
	}
	return o.Utxos
}

func (o *ListUtxosResponse) GetChainInfo() PrimaryNetworkChainInfo {
	if o == nil {
		return PrimaryNetworkChainInfo{}
	}
	return o.ChainInfo
}
