// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListErc1155TransactionsResponse struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string           `json:"nextPageToken,omitempty"`
	Transactions  []Erc1155Transfer `json:"transactions"`
}

func (o *ListErc1155TransactionsResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *ListErc1155TransactionsResponse) GetTransactions() []Erc1155Transfer {
	if o == nil {
		return []Erc1155Transfer{}
	}
	return o.Transactions
}
