// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAddressChainsResponse struct {
	IndexedChains   []ChainInfo `json:"indexedChains,omitempty"`
	UnindexedChains []string    `json:"unindexedChains,omitempty"`
}

func (o *ListAddressChainsResponse) GetIndexedChains() []ChainInfo {
	if o == nil {
		return nil
	}
	return o.IndexedChains
}

func (o *ListAddressChainsResponse) GetUnindexedChains() []string {
	if o == nil {
		return nil
	}
	return o.UnindexedChains
}
