// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LogsFormatMetadata struct {
	// The IP address of the client that made the request.
	IPAddress string `json:"ipAddress"`
	// The host for the request made by the client.
	Host string `json:"host"`
	// The user agent of the client that made the request.
	UserAgent string `json:"userAgent"`
}

func (o *LogsFormatMetadata) GetIPAddress() string {
	if o == nil {
		return ""
	}
	return o.IPAddress
}

func (o *LogsFormatMetadata) GetHost() string {
	if o == nil {
		return ""
	}
	return o.Host
}

func (o *LogsFormatMetadata) GetUserAgent() string {
	if o == nil {
		return ""
	}
	return o.UserAgent
}
