// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LogsResponseDTO struct {
	// A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The organization id of the request.
	OrgID string `json:"orgId"`
	// An array of logs representing the requests made by clients.
	Logs []LogsFormat `json:"logs"`
}

func (o *LogsResponseDTO) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}

func (o *LogsResponseDTO) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *LogsResponseDTO) GetLogs() []LogsFormat {
	if o == nil {
		return []LogsFormat{}
	}
	return o.Logs
}
