// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PChainSharedAsset struct {
	// Unique ID for an asset.
	AssetID string `json:"assetId"`
	// Name of this asset.
	Name string `json:"name"`
	// Symbol for this asset (max 4 characters).
	Symbol string `json:"symbol"`
	// Denomination of this asset to represent fungibility.
	Denomination float64 `json:"denomination"`
	// Type of asset like SECP256K1 or NFT.
	Type PrimaryNetworkAssetType `json:"type"`
	// Amount of the asset.
	Amount            string  `json:"amount"`
	UtxoCount         float64 `json:"utxoCount"`
	SharedWithChainID string  `json:"sharedWithChainId"`
	Status            string  `json:"status"`
}

func (o *PChainSharedAsset) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

func (o *PChainSharedAsset) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PChainSharedAsset) GetSymbol() string {
	if o == nil {
		return ""
	}
	return o.Symbol
}

func (o *PChainSharedAsset) GetDenomination() float64 {
	if o == nil {
		return 0.0
	}
	return o.Denomination
}

func (o *PChainSharedAsset) GetType() PrimaryNetworkAssetType {
	if o == nil {
		return PrimaryNetworkAssetType("")
	}
	return o.Type
}

func (o *PChainSharedAsset) GetAmount() string {
	if o == nil {
		return ""
	}
	return o.Amount
}

func (o *PChainSharedAsset) GetUtxoCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.UtxoCount
}

func (o *PChainSharedAsset) GetSharedWithChainID() string {
	if o == nil {
		return ""
	}
	return o.SharedWithChainID
}

func (o *PChainSharedAsset) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}
