// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// PrimaryNetworkAssetType - Type of asset like SECP256K1 or NFT.
type PrimaryNetworkAssetType string

const (
	PrimaryNetworkAssetTypeSecp256k1 PrimaryNetworkAssetType = "secp256k1"
	PrimaryNetworkAssetTypeNft       PrimaryNetworkAssetType = "nft"
)

func (e PrimaryNetworkAssetType) ToPointer() *PrimaryNetworkAssetType {
	return &e
}
func (e *PrimaryNetworkAssetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "secp256k1":
		fallthrough
	case "nft":
		*e = PrimaryNetworkAssetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PrimaryNetworkAssetType: %v", v)
	}
}
