// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PrimaryNetworkChainInfo struct {
	ChainName PrimaryNetworkChainName `json:"chainName"`
	Network   Network                 `json:"network"`
}

func (o *PrimaryNetworkChainInfo) GetChainName() PrimaryNetworkChainName {
	if o == nil {
		return PrimaryNetworkChainName("")
	}
	return o.ChainName
}

func (o *PrimaryNetworkChainInfo) GetNetwork() Network {
	if o == nil {
		return Network("")
	}
	return o.Network
}
