// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PrimaryNetworkChainName string

const (
	PrimaryNetworkChainNamePChain PrimaryNetworkChainName = "p-chain"
	PrimaryNetworkChainNameXChain PrimaryNetworkChainName = "x-chain"
	PrimaryNetworkChainNameCChain PrimaryNetworkChainName = "c-chain"
)

func (e PrimaryNetworkChainName) ToPointer() *PrimaryNetworkChainName {
	return &e
}
func (e *PrimaryNetworkChainName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "p-chain":
		fallthrough
	case "x-chain":
		fallthrough
	case "c-chain":
		*e = PrimaryNetworkChainName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PrimaryNetworkChainName: %v", v)
	}
}
