// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProposerDetails struct {
	ProposerID           *string  `json:"proposerId,omitempty"`
	ProposerParentID     *string  `json:"proposerParentId,omitempty"`
	ProposerNodeID       *string  `json:"proposerNodeId,omitempty"`
	ProposerPChainHeight *float64 `json:"proposerPChainHeight,omitempty"`
	ProposerTimestamp    *float64 `json:"proposerTimestamp,omitempty"`
}

func (o *ProposerDetails) GetProposerID() *string {
	if o == nil {
		return nil
	}
	return o.ProposerID
}

func (o *ProposerDetails) GetProposerParentID() *string {
	if o == nil {
		return nil
	}
	return o.ProposerParentID
}

func (o *ProposerDetails) GetProposerNodeID() *string {
	if o == nil {
		return nil
	}
	return o.ProposerNodeID
}

func (o *ProposerDetails) GetProposerPChainHeight() *float64 {
	if o == nil {
		return nil
	}
	return o.ProposerPChainHeight
}

func (o *ProposerDetails) GetProposerTimestamp() *float64 {
	if o == nil {
		return nil
	}
	return o.ProposerTimestamp
}
