// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Rewards struct {
	ValidationRewardAmount string   `json:"validationRewardAmount"`
	DelegationRewardAmount string   `json:"delegationRewardAmount"`
	RewardAddresses        []string `json:"rewardAddresses,omitempty"`
	RewardTxHash           *string  `json:"rewardTxHash,omitempty"`
}

func (o *Rewards) GetValidationRewardAmount() string {
	if o == nil {
		return ""
	}
	return o.ValidationRewardAmount
}

func (o *Rewards) GetDelegationRewardAmount() string {
	if o == nil {
		return ""
	}
	return o.DelegationRewardAmount
}

func (o *Rewards) GetRewardAddresses() []string {
	if o == nil {
		return nil
	}
	return o.RewardAddresses
}

func (o *Rewards) GetRewardTxHash() *string {
	if o == nil {
		return nil
	}
	return o.RewardTxHash
}
