// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignatureAggregatorRequest struct {
	Message          string   `json:"message"`
	Justification    *string  `json:"justification,omitempty"`
	SigningSubnetID  *string  `json:"signingSubnetId,omitempty"`
	QuorumPercentage *float64 `json:"quorumPercentage,omitempty"`
}

func (o *SignatureAggregatorRequest) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *SignatureAggregatorRequest) GetJustification() *string {
	if o == nil {
		return nil
	}
	return o.Justification
}

func (o *SignatureAggregatorRequest) GetSigningSubnetID() *string {
	if o == nil {
		return nil
	}
	return o.SigningSubnetID
}

func (o *SignatureAggregatorRequest) GetQuorumPercentage() *float64 {
	if o == nil {
		return nil
	}
	return o.QuorumPercentage
}
