// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SortByOption string

const (
	SortByOptionBlockIndex         SortByOption = "blockIndex"
	SortByOptionDelegationCapacity SortByOption = "delegationCapacity"
	SortByOptionTimeRemaining      SortByOption = "timeRemaining"
	SortByOptionDelegationFee      SortByOption = "delegationFee"
	SortByOptionUptimePerformance  SortByOption = "uptimePerformance"
)

func (e SortByOption) ToPointer() *SortByOption {
	return &e
}
func (e *SortByOption) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "blockIndex":
		fallthrough
	case "delegationCapacity":
		fallthrough
	case "timeRemaining":
		fallthrough
	case "delegationFee":
		fallthrough
	case "uptimePerformance":
		*e = SortByOption(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SortByOption: %v", v)
	}
}
