// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TeleporterSourceTransaction struct {
	TxHash    string  `json:"txHash"`
	Timestamp float64 `json:"timestamp"`
	GasSpent  string  `json:"gasSpent"`
}

func (o *TeleporterSourceTransaction) GetTxHash() string {
	if o == nil {
		return ""
	}
	return o.TxHash
}

func (o *TeleporterSourceTransaction) GetTimestamp() float64 {
	if o == nil {
		return 0.0
	}
	return o.Timestamp
}

func (o *TeleporterSourceTransaction) GetGasSpent() string {
	if o == nil {
		return ""
	}
	return o.GasSpent
}
