// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TeleporterMessageInfo struct {
	TeleporterMessageID string                   `json:"teleporterMessageId"`
	Direction           TransactionDirectionType `json:"direction"`
	// chain id of the source chain. valid only for destination transactions
	SourceChainID *string `json:"sourceChainId,omitempty"`
	// chain id of the destination chain. valid only for source transactions
	DestinationChainID *string `json:"destinationChainId,omitempty"`
}

func (o *TeleporterMessageInfo) GetTeleporterMessageID() string {
	if o == nil {
		return ""
	}
	return o.TeleporterMessageID
}

func (o *TeleporterMessageInfo) GetDirection() TransactionDirectionType {
	if o == nil {
		return TransactionDirectionType("")
	}
	return o.Direction
}

func (o *TeleporterMessageInfo) GetSourceChainID() *string {
	if o == nil {
		return nil
	}
	return o.SourceChainID
}

func (o *TeleporterMessageInfo) GetDestinationChainID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationChainID
}
