// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionDetails struct {
	// The native (top-level) transaction details.
	NativeTransaction NativeTransaction `json:"nativeTransaction"`
	// The list of ERC-20 transfers.
	Erc20Transfers []Erc20TransferDetails `json:"erc20Transfers,omitempty"`
	// The list of ERC-721 transfers.
	Erc721Transfers []Erc721TransferDetails `json:"erc721Transfers,omitempty"`
	// The list of ERC-1155 transfers.
	Erc1155Transfers []Erc1155TransferDetails `json:"erc1155Transfers,omitempty"`
	// The list of internal transactions. Note that this list only includes CALL and CALLCODE internal transactions that had a non-zero value and CREATE/CREATE2/CREATE3  calls. Use a client provider to recieve a full debug trace of the transaction.
	InternalTransactions []InternalTransactionDetails `json:"internalTransactions,omitempty"`
}

func (o *TransactionDetails) GetNativeTransaction() NativeTransaction {
	if o == nil {
		return NativeTransaction{}
	}
	return o.NativeTransaction
}

func (o *TransactionDetails) GetErc20Transfers() []Erc20TransferDetails {
	if o == nil {
		return nil
	}
	return o.Erc20Transfers
}

func (o *TransactionDetails) GetErc721Transfers() []Erc721TransferDetails {
	if o == nil {
		return nil
	}
	return o.Erc721Transfers
}

func (o *TransactionDetails) GetErc1155Transfers() []Erc1155TransferDetails {
	if o == nil {
		return nil
	}
	return o.Erc1155Transfers
}

func (o *TransactionDetails) GetInternalTransactions() []InternalTransactionDetails {
	if o == nil {
		return nil
	}
	return o.InternalTransactions
}
