// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UnknownContractErcType string

const (
	UnknownContractErcTypeUnknown UnknownContractErcType = "UNKNOWN"
)

func (e UnknownContractErcType) ToPointer() *UnknownContractErcType {
	return &e
}
func (e *UnknownContractErcType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		*e = UnknownContractErcType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UnknownContractErcType: %v", v)
	}
}

type UnknownContract struct {
	// The contract name.
	Name          *string        `json:"name,omitempty"`
	Description   *string        `json:"description,omitempty"`
	OfficialSite  *string        `json:"officialSite,omitempty"`
	Email         *string        `json:"email,omitempty"`
	LogoAsset     *ImageAsset    `json:"logoAsset,omitempty"`
	BannerAsset   *ImageAsset    `json:"bannerAsset,omitempty"`
	Color         *string        `json:"color,omitempty"`
	ResourceLinks []ResourceLink `json:"resourceLinks,omitempty"`
	Tags          []string       `json:"tags,omitempty"`
	// A wallet or contract address in mixed-case checksum encoding.
	Address           string                     `json:"address"`
	DeploymentDetails *ContractDeploymentDetails `json:"deploymentDetails,omitempty"`
	ErcType           UnknownContractErcType     `json:"ercType"`
}

func (o *UnknownContract) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UnknownContract) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UnknownContract) GetOfficialSite() *string {
	if o == nil {
		return nil
	}
	return o.OfficialSite
}

func (o *UnknownContract) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UnknownContract) GetLogoAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.LogoAsset
}

func (o *UnknownContract) GetBannerAsset() *ImageAsset {
	if o == nil {
		return nil
	}
	return o.BannerAsset
}

func (o *UnknownContract) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *UnknownContract) GetResourceLinks() []ResourceLink {
	if o == nil {
		return nil
	}
	return o.ResourceLinks
}

func (o *UnknownContract) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *UnknownContract) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *UnknownContract) GetDeploymentDetails() *ContractDeploymentDetails {
	if o == nil {
		return nil
	}
	return o.DeploymentDetails
}

func (o *UnknownContract) GetErcType() UnknownContractErcType {
	if o == nil {
		return UnknownContractErcType("")
	}
	return o.ErcType
}
