// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UsageMetricsResponseDTO struct {
	// Duration in which the metrics value is aggregated
	AggregateDuration string `json:"aggregateDuration"`
	// Org ID for which the metrics are aggregated
	OrgID string `json:"orgId"`
	// Metrics values
	Metrics []Metric `json:"metrics"`
}

func (o *UsageMetricsResponseDTO) GetAggregateDuration() string {
	if o == nil {
		return ""
	}
	return o.AggregateDuration
}

func (o *UsageMetricsResponseDTO) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *UsageMetricsResponseDTO) GetMetrics() []Metric {
	if o == nil {
		return []Metric{}
	}
	return o.Metrics
}
