// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UtilityAddresses struct {
	Multicall *string `json:"multicall,omitempty"`
}

func (o *UtilityAddresses) GetMulticall() *string {
	if o == nil {
		return nil
	}
	return o.Multicall
}
