// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Utxo struct {
	// Addresses that are eligible to sign the consumption of this output.
	Addresses []string    `json:"addresses"`
	Asset     AssetAmount `json:"asset"`
	// Blockchain ID on which this output is consumed on.
	ConsumedOnChainID string `json:"consumedOnChainId"`
	// Transaction ID that consumed this output.
	ConsumingTxHash *string `json:"consumingTxHash,omitempty"`
	// Blockchain ID on which this output is created on.
	CreatedOnChainID string `json:"createdOnChainId"`
	// UTXO ID for this output.
	UtxoID string `json:"utxoId"`
	// Unix timestamp in seconds at which this output was consumed.
	ConsumingTxTimestamp *float64 `json:"consumingTxTimestamp,omitempty"`
	// Transaction ID that created this output.
	CreationTxHash string `json:"creationTxHash"`
	// Credentials that signed the transaction to consume this utxo
	Credentials []UtxoCredential `json:"credentials,omitempty"`
	// Index representing the minting set for the NFT mint output.
	GroupID *float64 `json:"groupId,omitempty"`
	// Locktime in seconds after which this output can be consumed.
	Locktime float64 `json:"locktime"`
	// Postion of this output in a list of lexiographically sorted outputs of a transaction.
	OutputIndex string `json:"outputIndex"`
	// Hex encoded data for NFT assets.
	Payload *string `json:"payload,omitempty"`
	// Minimum number of signatures required to consume this output.
	Threshold float64 `json:"threshold"`
	// Unix timestamp in seconds at which this outptut was created.
	Timestamp float64 `json:"timestamp"`
	// Type of output.
	UtxoType string `json:"utxoType"`
}

func (o *Utxo) GetAddresses() []string {
	if o == nil {
		return []string{}
	}
	return o.Addresses
}

func (o *Utxo) GetAsset() AssetAmount {
	if o == nil {
		return AssetAmount{}
	}
	return o.Asset
}

func (o *Utxo) GetConsumedOnChainID() string {
	if o == nil {
		return ""
	}
	return o.ConsumedOnChainID
}

func (o *Utxo) GetConsumingTxHash() *string {
	if o == nil {
		return nil
	}
	return o.ConsumingTxHash
}

func (o *Utxo) GetCreatedOnChainID() string {
	if o == nil {
		return ""
	}
	return o.CreatedOnChainID
}

func (o *Utxo) GetUtxoID() string {
	if o == nil {
		return ""
	}
	return o.UtxoID
}

func (o *Utxo) GetConsumingTxTimestamp() *float64 {
	if o == nil {
		return nil
	}
	return o.ConsumingTxTimestamp
}

func (o *Utxo) GetCreationTxHash() string {
	if o == nil {
		return ""
	}
	return o.CreationTxHash
}

func (o *Utxo) GetCredentials() []UtxoCredential {
	if o == nil {
		return nil
	}
	return o.Credentials
}

func (o *Utxo) GetGroupID() *float64 {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *Utxo) GetLocktime() float64 {
	if o == nil {
		return 0.0
	}
	return o.Locktime
}

func (o *Utxo) GetOutputIndex() string {
	if o == nil {
		return ""
	}
	return o.OutputIndex
}

func (o *Utxo) GetPayload() *string {
	if o == nil {
		return nil
	}
	return o.Payload
}

func (o *Utxo) GetThreshold() float64 {
	if o == nil {
		return 0.0
	}
	return o.Threshold
}

func (o *Utxo) GetTimestamp() float64 {
	if o == nil {
		return 0.0
	}
	return o.Timestamp
}

func (o *Utxo) GetUtxoType() string {
	if o == nil {
		return ""
	}
	return o.UtxoType
}
