// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ValidatorHealthDetails struct {
	// Percent of requests responded to in last polling.
	ReachabilityPercent float64 `json:"reachabilityPercent"`
	// Percent of requests benched on the P-Chain in last polling.
	BenchedPChainRequestsPercent float64 `json:"benchedPChainRequestsPercent"`
	// Percentage of requests benched on the X-Chain in last polling.
	BenchedXChainRequestsPercent float64 `json:"benchedXChainRequestsPercent"`
	// Percentage of requests benched on the C-Chain in last polling.
	BenchedCChainRequestsPercent float64 `json:"benchedCChainRequestsPercent"`
}

func (o *ValidatorHealthDetails) GetReachabilityPercent() float64 {
	if o == nil {
		return 0.0
	}
	return o.ReachabilityPercent
}

func (o *ValidatorHealthDetails) GetBenchedPChainRequestsPercent() float64 {
	if o == nil {
		return 0.0
	}
	return o.BenchedPChainRequestsPercent
}

func (o *ValidatorHealthDetails) GetBenchedXChainRequestsPercent() float64 {
	if o == nil {
		return 0.0
	}
	return o.BenchedXChainRequestsPercent
}

func (o *ValidatorHealthDetails) GetBenchedCChainRequestsPercent() float64 {
	if o == nil {
		return 0.0
	}
	return o.BenchedCChainRequestsPercent
}
