// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VMName string

const (
	VMNameEvm      VMName = "EVM"
	VMNameBitcoin  VMName = "BITCOIN"
	VMNameEthereum VMName = "ETHEREUM"
)

func (e VMName) ToPointer() *VMName {
	return &e
}
func (e *VMName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EVM":
		fallthrough
	case "BITCOIN":
		fallthrough
	case "ETHEREUM":
		*e = VMName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VMName: %v", v)
	}
}
