// biome-ignore lint/performance/noBarrelFile: entrypoint module
export {
  addChain,
  call,
  createAccessList,
  createBlockFilter,
  createContractEventFilter,
  createEventFilter,
  createPendingTransactionFilter,
  defaultPrepareTransactionRequestParameters,
  deployContract,
  dropTransaction,
  dumpState,
  estimateContractGas,
  estimateFeesPerGas,
  estimateGas,
  estimateMaxPriorityFeePerGas,
  getAddresses,
  getAutomine,
  getBalance,
  getBlobBaseFee,
  getBlock,
  getBlockNumber,
  getBlockTransactionCount,
  /** @deprecated Use `getCode` instead  */
  getCode as getBytecode,
  getCallsStatus,
  getCapabilities,
  getChainId,
  getCode,
  getContractEvents,
  getEip712Domain,
  getEnsAddress,
  getEnsAvatar,
  getEnsName,
  getEnsResolver,
  getEnsText,
  getFeeHistory,
  getFilterChanges,
  getFilterLogs,
  getGasPrice,
  getLogs,
  getPermissions,
  getProof,
  getStorageAt,
  getTransaction,
  getTransactionConfirmations,
  getTransactionCount,
  getTransactionReceipt,
  getTxpoolContent,
  getTxpoolStatus,
  impersonateAccount,
  increaseTime,
  inspectTxpool,
  loadState,
  mine,
  multicall,
  prepareAuthorization,
  prepareTransactionRequest,
  readContract,
  removeBlockTimestampInterval,
  requestAddresses,
  requestPermissions,
  reset,
  revert,
  sendCalls,
  sendRawTransaction,
  sendTransaction,
  sendUnsignedTransaction,
  setAutomine,
  setBalance,
  setBlockGasLimit,
  setBlockTimestampInterval,
  setCode,
  setCoinbase,
  setIntervalMining,
  setLoggingEnabled,
  setMinGasPrice,
  setNextBlockBaseFeePerGas,
  setNextBlockTimestamp,
  setNonce,
  setRpcUrl,
  setStorageAt,
  showCallsStatus,
  signAuthorization,
  signMessage,
  signTransaction,
  signTypedData,
  /** @deprecated Use `simulateBlocks` instead */
  simulateBlocks as simulate,
  simulateBlocks,
  simulateCalls,
  simulateContract,
  snapshot,
  stopImpersonatingAccount,
  switchChain,
  uninstallFilter,
  verifyHash,
  verifyMessage,
  verifyTypedData,
  waitForCallsStatus,
  waitForTransactionReceipt,
  watchAsset,
  watchBlockNumber,
  watchBlocks,
  watchContractEvent,
  watchEvent,
  watchPendingTransactions,
  writeContract,
  type AddChainErrorType,
  type AddChainParameters,
  type CallErrorType,
  type CallParameters,
  type CallReturnType,
  type CreateAccessListErrorType,
  type CreateAccessListParameters,
  type CreateAccessListReturnType,
  type CreateBlockFilterErrorType,
  type CreateBlockFilterReturnType,
  type CreateContractEventFilterErrorType,
  type CreateContractEventFilterParameters,
  type CreateContractEventFilterReturnType,
  type CreateEventFilterErrorType,
  type CreateEventFilterParameters,
  type CreateEventFilterReturnType,
  type CreatePendingTransactionFilterErrorType,
  type CreatePendingTransactionFilterReturnType,
  type DeployContractErrorType,
  type DeployContractParameters,
  type DeployContractReturnType,
  type DropTransactionParameters,
  type DumpStateErrorType,
  type DumpStateReturnType,
  type EstimateContractGasErrorType,
  type EstimateContractGasParameters,
  type EstimateContractGasReturnType,
  type EstimateFeesPerGasErrorType,
  type EstimateFeesPerGasParameters,
  type EstimateFeesPerGasReturnType,
  type EstimateGasErrorType,
  type EstimateGasParameters,
  type EstimateGasReturnType,
  type EstimateMaxPriorityFeePerGasErrorType,
  type EstimateMaxPriorityFeePerGasParameters,
  type EstimateMaxPriorityFeePerGasReturnType,
  type GetAddressesErrorType,
  type GetAddressesReturnType,
  type GetAutomineErrorType,
  type GetAutomineReturnType,
  type GetBalanceErrorType,
  type GetBalanceParameters,
  type GetBalanceReturnType,
  type GetBlobBaseFeeErrorType,
  type GetBlobBaseFeeReturnType,
  type GetBlockErrorType,
  type GetBlockNumberErrorType,
  type GetBlockNumberParameters,
  type GetBlockNumberReturnType,
  type GetBlockParameters,
  type GetBlockReturnType,
  type GetBlockTransactionCountErrorType,
  type GetBlockTransactionCountParameters,
  type GetBlockTransactionCountReturnType,
  /** @deprecated Use `GetCodeErrorType` instead */
  type GetCodeErrorType as GetBytecodeErrorType,
  /** @deprecated Use `GetCodeParameters` instead */
  type GetCodeParameters as GetBytecodeParameters,
  /** @deprecated Use `GetCodeReturnType` instead  */
  type GetCodeReturnType as GetBytecodeReturnType,
  type GetCallsStatusErrorType,
  type GetCallsStatusParameters,
  type GetCallsStatusReturnType,
  type GetCapabilitiesErrorType,
  type GetCapabilitiesParameters,
  type GetCapabilitiesReturnType,
  type GetChainIdErrorType,
  type GetChainIdReturnType,
  type GetCodeErrorType,
  type GetCodeParameters,
  type GetCodeReturnType,
  type GetContractEventsErrorType,
  type GetContractEventsParameters,
  type GetContractEventsReturnType,
  type GetEip712DomainErrorType,
  type GetEip712DomainParameters,
  type GetEip712DomainReturnType,
  type GetEnsAddressErrorType,
  type GetEnsAddressParameters,
  type GetEnsAddressReturnType,
  type GetEnsAvatarErrorType,
  type GetEnsAvatarParameters,
  type GetEnsAvatarReturnType,
  type GetEnsNameErrorType,
  type GetEnsNameParameters,
  type GetEnsNameReturnType,
  type GetEnsResolverErrorType,
  type GetEnsResolverParameters,
  type GetEnsResolverReturnType,
  type GetEnsTextErrorType,
  type GetEnsTextParameters,
  type GetEnsTextReturnType,
  type GetFeeHistoryErrorType,
  type GetFeeHistoryParameters,
  type GetFeeHistoryReturnType,
  type GetFilterChangesErrorType,
  type GetFilterChangesParameters,
  type GetFilterChangesReturnType,
  type GetFilterLogsErrorType,
  type GetFilterLogsParameters,
  type GetFilterLogsReturnType,
  type GetGasPriceErrorType,
  type GetGasPriceReturnType,
  type GetLogsErrorType,
  type GetLogsParameters,
  type GetLogsReturnType,
  type GetPermissionsErrorType,
  type GetPermissionsReturnType,
  type GetProofErrorType,
  type GetProofParameters,
  type GetProofReturnType,
  type GetStorageAtErrorType,
  type GetStorageAtParameters,
  type GetStorageAtReturnType,
  type GetTransactionConfirmationsErrorType,
  type GetTransactionConfirmationsParameters,
  type GetTransactionConfirmationsReturnType,
  type GetTransactionCountErrorType,
  type GetTransactionCountParameters,
  type GetTransactionCountReturnType,
  type GetTransactionErrorType,
  type GetTransactionParameters,
  type GetTransactionReceiptErrorType,
  type GetTransactionReceiptParameters,
  type GetTransactionReceiptReturnType,
  type GetTransactionReturnType,
  type GetTxpoolContentErrorType,
  type GetTxpoolContentReturnType,
  type GetTxpoolStatusErrorType,
  type GetTxpoolStatusReturnType,
  type ImpersonateAccountErrorType,
  type ImpersonateAccountParameters,
  type IncreaseTimeErrorType,
  type IncreaseTimeParameters,
  type InspectTxpoolErrorType,
  type InspectTxpoolReturnType,
  type LoadStateErrorType,
  type LoadStateParameters,
  type LoadStateReturnType,
  type MineErrorType,
  type MineParameters,
  type MulticallErrorType,
  type MulticallParameters,
  type MulticallReturnType,
  type OnBlock,
  type OnBlockNumberFn,
  type OnBlockNumberParameter,
  type OnBlockParameter,
  type OnTransactionsFn,
  type OnTransactionsParameter,
  type PrepareAuthorizationErrorType,
  type PrepareAuthorizationParameters,
  type PrepareAuthorizationReturnType,
  type PrepareTransactionRequestErrorType,
  type PrepareTransactionRequestParameters,
  type PrepareTransactionRequestReturnType,
  type ReadContractErrorType,
  type ReadContractParameters,
  type ReadContractReturnType,
  type RemoveBlockTimestampIntervalErrorType,
  type ReplacementReason,
  type ReplacementReturnType,
  type RequestAddressesErrorType,
  type RequestAddressesReturnType,
  type RequestPermissionsErrorType,
  type RequestPermissionsParameters,
  type RequestPermissionsReturnType,
  type ResetErrorType,
  type ResetParameters,
  type RevertErrorType,
  type RevertParameters,
  type SendCallsErrorType,
  type SendCallsParameters,
  type SendCallsReturnType,
  type SendRawTransactionErrorType,
  type SendRawTransactionParameters,
  type SendRawTransactionReturnType,
  type SendTransactionErrorType,
  type SendTransactionParameters,
  type SendTransactionReturnType,
  type SendUnsignedTransactionErrorType,
  type SendUnsignedTransactionParameters,
  type SendUnsignedTransactionReturnType,
  type SetAutomineErrorType,
  type SetBalanceErrorType,
  type SetBalanceParameters,
  type SetBlockGasLimitErrorType,
  type SetBlockGasLimitParameters,
  type SetBlockTimestampIntervalErrorType,
  type SetBlockTimestampIntervalParameters,
  type SetCodeErrorType,
  type SetCodeParameters,
  type SetCoinbaseErrorType,
  type SetCoinbaseParameters,
  type SetIntervalMiningErrorType,
  type SetIntervalMiningParameters,
  type SetLoggingEnabledErrorType,
  type SetMinGasPriceErrorType,
  type SetMinGasPriceParameters,
  type SetNextBlockBaseFeePerGasErrorType,
  type SetNextBlockBaseFeePerGasParameters,
  type SetNextBlockTimestampErrorType,
  type SetNextBlockTimestampParameters,
  type SetNonceErrorType,
  type SetNonceParameters,
  type SetRpcUrlErrorType,
  type SetStorageAtErrorType,
  type SetStorageAtParameters,
  type ShowCallsStatusErrorType,
  type ShowCallsStatusParameters,
  type ShowCallsStatusReturnType,
  type SignAuthorizationErrorType,
  type SignAuthorizationParameters,
  type SignAuthorizationReturnType,
  type SignMessageErrorType,
  type SignMessageParameters,
  type SignMessageReturnType,
  type SignTransactionErrorType,
  type SignTransactionParameters,
  type SignTransactionReturnType,
  type SignTypedDataErrorType,
  type SignTypedDataParameters,
  type SignTypedDataReturnType,
  type SimulateBlocksErrorType,
  type SimulateBlocksParameters,
  type SimulateBlocksReturnType,
  type SimulateCallsErrorType,
  type SimulateCallsParameters,
  type SimulateCallsReturnType,
  type SimulateContractErrorType,
  type SimulateContractParameters,
  type SimulateContractReturnType,
  /** @deprecated Use `SimulateBlocksErrorType` instead */
  type SimulateBlocksErrorType as SimulateErrorType,
  /** @deprecated Use `SimulateBlocksParameters` instead */
  type SimulateBlocksParameters as SimulateParameters,
  /** @deprecated Use `SimulateBlocksReturnType` instead */
  type SimulateBlocksReturnType as SimulateReturnType,
  type SnapshotErrorType,
  type StopImpersonatingAccountErrorType,
  type StopImpersonatingAccountParameters,
  type SwitchChainErrorType,
  type SwitchChainParameters,
  type UninstallFilterErrorType,
  type UninstallFilterParameters,
  type UninstallFilterReturnType,
  type VerifyHashErrorType,
  type VerifyHashParameters,
  type VerifyHashReturnType,
  type VerifyMessageErrorType,
  type VerifyMessageParameters,
  type VerifyMessageReturnType,
  type VerifyTypedDataErrorType,
  type VerifyTypedDataParameters,
  type VerifyTypedDataReturnType,
  type WaitForCallsStatusErrorType,
  type WaitForCallsStatusParameters,
  type WaitForCallsStatusReturnType,
  type WaitForCallsStatusTimeoutErrorType,
  type WaitForTransactionReceiptErrorType,
  type WaitForTransactionReceiptParameters,
  type WaitForTransactionReceiptReturnType,
  type WatchAssetErrorType,
  type WatchAssetParameters,
  type WatchAssetReturnType,
  type WatchBlockNumberErrorType,
  type WatchBlockNumberParameters,
  type WatchBlockNumberReturnType,
  type WatchBlocksErrorType,
  type WatchBlocksParameters,
  type WatchBlocksReturnType,
  type WatchContractEventErrorType,
  type WatchContractEventParameters,
  type WatchContractEventReturnType,
  type WatchEventOnLogsFn,
  type WatchEventOnLogsParameter,
  type WatchEventParameters,
  type WatchEventReturnType,
  type WatchPendingTransactionsErrorType,
  type WatchPendingTransactionsParameters,
  type WatchPendingTransactionsReturnType,
  type WriteContractErrorType,
  type WriteContractParameters,
  type WriteContractReturnType,
} from "viem/actions";

export * from "./consts.js";
