/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTeleporterMessageRequest = {
  /**
   * The message ID of the teleporter message.
   */
  messageId: string;
};

/**
 * Successful response
 */
export type GetTeleporterMessageResponse =
  | (components.DeliveredTeleporterMessage & { status: "delivered" })
  | (components.PendingTeleporterMessage & { status: "pending" })
  | (components.DeliveredSourceNotIndexedTeleporterMessage & {
    status: "delivered_source_not_indexed";
  });

/** @internal */
export const GetTeleporterMessageRequest$inboundSchema: z.ZodType<
  GetTeleporterMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: z.string(),
});

/** @internal */
export type GetTeleporterMessageRequest$Outbound = {
  messageId: string;
};

/** @internal */
export const GetTeleporterMessageRequest$outboundSchema: z.ZodType<
  GetTeleporterMessageRequest$Outbound,
  z.ZodTypeDef,
  GetTeleporterMessageRequest
> = z.object({
  messageId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTeleporterMessageRequest$ {
  /** @deprecated use `GetTeleporterMessageRequest$inboundSchema` instead. */
  export const inboundSchema = GetTeleporterMessageRequest$inboundSchema;
  /** @deprecated use `GetTeleporterMessageRequest$outboundSchema` instead. */
  export const outboundSchema = GetTeleporterMessageRequest$outboundSchema;
  /** @deprecated use `GetTeleporterMessageRequest$Outbound` instead. */
  export type Outbound = GetTeleporterMessageRequest$Outbound;
}

export function getTeleporterMessageRequestToJSON(
  getTeleporterMessageRequest: GetTeleporterMessageRequest,
): string {
  return JSON.stringify(
    GetTeleporterMessageRequest$outboundSchema.parse(
      getTeleporterMessageRequest,
    ),
  );
}

export function getTeleporterMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTeleporterMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTeleporterMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTeleporterMessageRequest' from JSON`,
  );
}

/** @internal */
export const GetTeleporterMessageResponse$inboundSchema: z.ZodType<
  GetTeleporterMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.DeliveredTeleporterMessage$inboundSchema.and(
    z.object({ status: z.literal("delivered") }).transform((v) => ({
      status: v.status,
    })),
  ),
  components.PendingTeleporterMessage$inboundSchema.and(
    z.object({ status: z.literal("pending") }).transform((v) => ({
      status: v.status,
    })),
  ),
  components.DeliveredSourceNotIndexedTeleporterMessage$inboundSchema.and(
    z.object({ status: z.literal("delivered_source_not_indexed") }).transform((
      v,
    ) => ({ status: v.status })),
  ),
]);

/** @internal */
export type GetTeleporterMessageResponse$Outbound =
  | (components.DeliveredTeleporterMessage$Outbound & { status: "delivered" })
  | (components.PendingTeleporterMessage$Outbound & { status: "pending" })
  | (components.DeliveredSourceNotIndexedTeleporterMessage$Outbound & {
    status: "delivered_source_not_indexed";
  });

/** @internal */
export const GetTeleporterMessageResponse$outboundSchema: z.ZodType<
  GetTeleporterMessageResponse$Outbound,
  z.ZodTypeDef,
  GetTeleporterMessageResponse
> = z.union([
  components.DeliveredTeleporterMessage$outboundSchema.and(
    z.object({ status: z.literal("delivered") }).transform((v) => ({
      status: v.status,
    })),
  ),
  components.PendingTeleporterMessage$outboundSchema.and(
    z.object({ status: z.literal("pending") }).transform((v) => ({
      status: v.status,
    })),
  ),
  components.DeliveredSourceNotIndexedTeleporterMessage$outboundSchema.and(
    z.object({ status: z.literal("delivered_source_not_indexed") }).transform((
      v,
    ) => ({ status: v.status })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTeleporterMessageResponse$ {
  /** @deprecated use `GetTeleporterMessageResponse$inboundSchema` instead. */
  export const inboundSchema = GetTeleporterMessageResponse$inboundSchema;
  /** @deprecated use `GetTeleporterMessageResponse$outboundSchema` instead. */
  export const outboundSchema = GetTeleporterMessageResponse$outboundSchema;
  /** @deprecated use `GetTeleporterMessageResponse$Outbound` instead. */
  export type Outbound = GetTeleporterMessageResponse$Outbound;
}

export function getTeleporterMessageResponseToJSON(
  getTeleporterMessageResponse: GetTeleporterMessageResponse,
): string {
  return JSON.stringify(
    GetTeleporterMessageResponse$outboundSchema.parse(
      getTeleporterMessageResponse,
    ),
  );
}

export function getTeleporterMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTeleporterMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTeleporterMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTeleporterMessageResponse' from JSON`,
  );
}
