/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeactivateWebhookRequest = {
  /**
   * The webhook identifier.
   */
  id: string;
};

/**
 * Successful response
 */
export type DeactivateWebhookResponse =
  | components.EVMAddressActivityResponse
  | components.PlatformActivityResponse;

/** @internal */
export const DeactivateWebhookRequest$inboundSchema: z.ZodType<
  DeactivateWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeactivateWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeactivateWebhookRequest$outboundSchema: z.ZodType<
  DeactivateWebhookRequest$Outbound,
  z.ZodTypeDef,
  DeactivateWebhookRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeactivateWebhookRequest$ {
  /** @deprecated use `DeactivateWebhookRequest$inboundSchema` instead. */
  export const inboundSchema = DeactivateWebhookRequest$inboundSchema;
  /** @deprecated use `DeactivateWebhookRequest$outboundSchema` instead. */
  export const outboundSchema = DeactivateWebhookRequest$outboundSchema;
  /** @deprecated use `DeactivateWebhookRequest$Outbound` instead. */
  export type Outbound = DeactivateWebhookRequest$Outbound;
}

export function deactivateWebhookRequestToJSON(
  deactivateWebhookRequest: DeactivateWebhookRequest,
): string {
  return JSON.stringify(
    DeactivateWebhookRequest$outboundSchema.parse(deactivateWebhookRequest),
  );
}

export function deactivateWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeactivateWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeactivateWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeactivateWebhookRequest' from JSON`,
  );
}

/** @internal */
export const DeactivateWebhookResponse$inboundSchema: z.ZodType<
  DeactivateWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.EVMAddressActivityResponse$inboundSchema,
  components.PlatformActivityResponse$inboundSchema,
]);

/** @internal */
export type DeactivateWebhookResponse$Outbound =
  | components.EVMAddressActivityResponse$Outbound
  | components.PlatformActivityResponse$Outbound;

/** @internal */
export const DeactivateWebhookResponse$outboundSchema: z.ZodType<
  DeactivateWebhookResponse$Outbound,
  z.ZodTypeDef,
  DeactivateWebhookResponse
> = z.union([
  components.EVMAddressActivityResponse$outboundSchema,
  components.PlatformActivityResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeactivateWebhookResponse$ {
  /** @deprecated use `DeactivateWebhookResponse$inboundSchema` instead. */
  export const inboundSchema = DeactivateWebhookResponse$inboundSchema;
  /** @deprecated use `DeactivateWebhookResponse$outboundSchema` instead. */
  export const outboundSchema = DeactivateWebhookResponse$outboundSchema;
  /** @deprecated use `DeactivateWebhookResponse$Outbound` instead. */
  export type Outbound = DeactivateWebhookResponse$Outbound;
}

export function deactivateWebhookResponseToJSON(
  deactivateWebhookResponse: DeactivateWebhookResponse,
): string {
  return JSON.stringify(
    DeactivateWebhookResponse$outboundSchema.parse(deactivateWebhookResponse),
  );
}

export function deactivateWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeactivateWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeactivateWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeactivateWebhookResponse' from JSON`,
  );
}
