workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    data-source:
        inputs:
            - location: https://glacier-api.avax.network/api-json
        overlays:
            - location: data/overlays/overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-data-typescript
    metrics-source:
        inputs:
            - location: https://popsicle-api.avax.network/api-json
        overlays:
            - location: metrics/overlays/overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-metrics-typescript
targets:
    data-sdk:
        target: typescript
        source: data-source
        output: data
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-data-typescript-code-samples
            langOverride: javascript
            labelOverride:
                fixedValue: JavaScript
            blocking: false
    metrics-sdk:
        target: typescript
        source: metrics-source
        output: metrics
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-metrics-typescript-code-samples
            langOverride: javascript
            labelOverride:
                fixedValue: JavaScript
            blocking: false
