workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    devtools-source:
        inputs:
            - location: https://popsicle-api.avax.network/api-json
            - location: https://glacier-api.avax.network/api-json
        overlays:
            - location: devtools/overlays/overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-devtools-typescript
targets:
    devtools-sdk:
        target: typescript
        source: devtools-source
        output: devtools
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-devtools-typescript-code-samples
            langOverride: javascript
            labelOverride:
                fixedValue: JavaScript
            blocking: false