workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    chainkit-source:
        inputs:
            - location: https://metrics.avax.network/api-json
            - location: https://data-api.avax.network/api-json
        overlays:
            - location: chainkit/overlays/overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-chainkit-typescript
targets:
    chainkit-sdk:
        target: typescript
        source: chainkit-source
        output: chainkit
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/avalabs/avalabs/avalanche-sdk-chainkit-typescript-code-samples
            langOverride: javascript
            labelOverride:
                fixedValue: JavaScript
            blocking: false
