// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetBlockGlobals struct {
	// A supported EVM chain id, chain alias, or blockchain id.
	ChainID *string `pathParam:"style=simple,explode=false,name=chainId"`
}

func (o *GetBlockGlobals) GetChainID() *string {
	if o == nil {
		return nil
	}
	return o.ChainID
}

type GetBlockRequest struct {
	// A supported evm chain id or blockchain id. Use the `/chains` endpoint to get a list of supported chain ids.
	ChainID *string `pathParam:"style=simple,explode=false,name=chainId"`
	// A block identifier which is either a block number or the block hash.
	BlockID string `pathParam:"style=simple,explode=false,name=blockId"`
}

func (o *GetBlockRequest) GetChainID() *string {
	if o == nil {
		return nil
	}
	return o.ChainID
}

func (o *GetBlockRequest) GetBlockID() string {
	if o == nil {
		return ""
	}
	return o.BlockID
}

type GetBlockResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	GetEvmBlockResponse *components.GetEvmBlockResponse
}

func (o *GetBlockResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBlockResponse) GetGetEvmBlockResponse() *components.GetEvmBlockResponse {
	if o == nil {
		return nil
	}
	return o.GetEvmBlockResponse
}
