// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetChainInfoGlobals struct {
	// A supported EVM chain id, chain alias, or blockchain id.
	ChainID *string `pathParam:"style=simple,explode=false,name=chainId"`
}

func (o *GetChainInfoGlobals) GetChainID() *string {
	if o == nil {
		return nil
	}
	return o.ChainID
}

type GetChainInfoRequest struct {
	// A supported evm chain id or blockchain id. Use the `/chains` endpoint to get a list of supported chain ids.
	ChainID *string `pathParam:"style=simple,explode=false,name=chainId"`
}

func (o *GetChainInfoRequest) GetChainID() *string {
	if o == nil {
		return nil
	}
	return o.ChainID
}

type GetChainInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	GetChainResponse *components.GetChainResponse
}

func (o *GetChainInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetChainInfoResponse) GetGetChainResponse() *components.GetChainResponse {
	if o == nil {
		return nil
	}
	return o.GetChainResponse
}
