// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOperationResultRequest struct {
	// UUID of given operation
	OperationID string `pathParam:"style=simple,explode=false,name=operationId"`
}

func (o *GetOperationResultRequest) GetOperationID() string {
	if o == nil {
		return ""
	}
	return o.OperationID
}

type GetOperationResultResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	OperationStatusResponse *components.OperationStatusResponse
}

func (o *GetOperationResultResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOperationResultResponse) GetOperationStatusResponse() *components.OperationStatusResponse {
	if o == nil {
		return nil
	}
	return o.OperationStatusResponse
}
