// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSubnetByIDGlobals struct {
	// A supported network type mainnet or testnet/fuji.
	Network *components.GlobalParamNetwork `pathParam:"style=simple,explode=false,name=network"`
}

func (o *GetSubnetByIDGlobals) GetNetwork() *components.GlobalParamNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

type GetSubnetByIDRequest struct {
	// Either mainnet or testnet/fuji.
	Network *components.GlobalParamNetwork `pathParam:"style=simple,explode=false,name=network"`
	// Subnet ID to fetch details for
	SubnetID string `pathParam:"style=simple,explode=false,name=subnetId"`
}

func (o *GetSubnetByIDRequest) GetNetwork() *components.GlobalParamNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

func (o *GetSubnetByIDRequest) GetSubnetID() string {
	if o == nil {
		return ""
	}
	return o.SubnetID
}

type GetSubnetByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Subnet *components.Subnet
}

func (o *GetSubnetByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSubnetByIDResponse) GetSubnet() *components.Subnet {
	if o == nil {
		return nil
	}
	return o.Subnet
}
