// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetVertexByHeightGlobals struct {
	// A supported network type mainnet or testnet/fuji.
	Network *components.GlobalParamNetwork `pathParam:"style=simple,explode=false,name=network"`
}

func (o *GetVertexByHeightGlobals) GetNetwork() *components.GlobalParamNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

type GetVertexByHeightRequest struct {
	// The height of a vertex.
	VertexHeight int64 `queryParam:"style=form,explode=true,name=vertexHeight"`
	// A page token, received from a previous list call. Provide this to retrieve the subsequent page.
	PageToken *string `queryParam:"style=form,explode=true,name=pageToken"`
	// The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
	PageSize *int64 `default:"10" queryParam:"style=form,explode=true,name=pageSize"`
	// A primary network blockchain id or alias.
	BlockchainID components.XChainID `pathParam:"style=simple,explode=false,name=blockchainId"`
	// Either mainnet or testnet/fuji.
	Network *components.GlobalParamNetwork `pathParam:"style=simple,explode=false,name=network"`
	// The order by which to sort results. Use "asc" for ascending order, "desc" for descending order. Sorted by timestamp or the `sortBy` query parameter, if provided.
	SortOrder *components.SortOrder `queryParam:"style=form,explode=true,name=sortOrder"`
}

func (g GetVertexByHeightRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetVertexByHeightRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetVertexByHeightRequest) GetVertexHeight() int64 {
	if o == nil {
		return 0
	}
	return o.VertexHeight
}

func (o *GetVertexByHeightRequest) GetPageToken() *string {
	if o == nil {
		return nil
	}
	return o.PageToken
}

func (o *GetVertexByHeightRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *GetVertexByHeightRequest) GetBlockchainID() components.XChainID {
	if o == nil {
		return components.XChainID("")
	}
	return o.BlockchainID
}

func (o *GetVertexByHeightRequest) GetNetwork() *components.GlobalParamNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

func (o *GetVertexByHeightRequest) GetSortOrder() *components.SortOrder {
	if o == nil {
		return nil
	}
	return o.SortOrder
}

type GetVertexByHeightResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	ListXChainVerticesResponse *components.ListXChainVerticesResponse

	Next func() (*GetVertexByHeightResponse, error)
}

func (o *GetVertexByHeightResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVertexByHeightResponse) GetListXChainVerticesResponse() *components.ListXChainVerticesResponse {
	if o == nil {
		return nil
	}
	return o.ListXChainVerticesResponse
}
