// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ListAllLatestBlocksRequest struct {
	// A page token, received from a previous list call. Provide this to retrieve the subsequent page.
	PageToken *string `queryParam:"style=form,explode=true,name=pageToken"`
	// The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
	PageSize *int64 `default:"10" queryParam:"style=form,explode=true,name=pageSize"`
	// Either mainnet or testnet/fuji.
	Network *components.Network `queryParam:"style=form,explode=true,name=network"`
}

func (l ListAllLatestBlocksRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAllLatestBlocksRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAllLatestBlocksRequest) GetPageToken() *string {
	if o == nil {
		return nil
	}
	return o.PageToken
}

func (o *ListAllLatestBlocksRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListAllLatestBlocksRequest) GetNetwork() *components.Network {
	if o == nil {
		return nil
	}
	return o.Network
}

type ListAllLatestBlocksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	ListEvmBlocksResponse *components.ListEvmBlocksResponse

	Next func() (*ListAllLatestBlocksResponse, error)
}

func (o *ListAllLatestBlocksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAllLatestBlocksResponse) GetListEvmBlocksResponse() *components.ListEvmBlocksResponse {
	if o == nil {
		return nil
	}
	return o.ListEvmBlocksResponse
}
