// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ListAllLatestTransactionsRequest struct {
	// A page token, received from a previous list call. Provide this to retrieve the subsequent page.
	PageToken *string `queryParam:"style=form,explode=true,name=pageToken"`
	// The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
	PageSize *int64 `default:"10" queryParam:"style=form,explode=true,name=pageSize"`
	// Either mainnet or testnet/fuji.
	Network *components.Network `queryParam:"style=form,explode=true,name=network"`
	// A status filter for listed transactions.
	Status *components.TransactionStatus `queryParam:"style=form,explode=true,name=status"`
}

func (l ListAllLatestTransactionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAllLatestTransactionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAllLatestTransactionsRequest) GetPageToken() *string {
	if o == nil {
		return nil
	}
	return o.PageToken
}

func (o *ListAllLatestTransactionsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListAllLatestTransactionsRequest) GetNetwork() *components.Network {
	if o == nil {
		return nil
	}
	return o.Network
}

func (o *ListAllLatestTransactionsRequest) GetStatus() *components.TransactionStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type ListAllLatestTransactionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	ListNativeTransactionsResponse *components.ListNativeTransactionsResponse

	Next func() (*ListAllLatestTransactionsResponse, error)
}

func (o *ListAllLatestTransactionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAllLatestTransactionsResponse) GetListNativeTransactionsResponse() *components.ListNativeTransactionsResponse {
	if o == nil {
		return nil
	}
	return o.ListNativeTransactionsResponse
}
