// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ListLatestXChainVerticesGlobals struct {
	// A supported network type mainnet or testnet/fuji.
	Network *components.GlobalParamNetwork `pathParam:"style=simple,explode=false,name=network"`
}

func (o *ListLatestXChainVerticesGlobals) GetNetwork() *components.GlobalParamNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

type ListLatestXChainVerticesRequest struct {
	// A page token, received from a previous list call. Provide this to retrieve the subsequent page.
	PageToken *string `queryParam:"style=form,explode=true,name=pageToken"`
	// The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
	PageSize *int64 `default:"10" queryParam:"style=form,explode=true,name=pageSize"`
	// A primary network blockchain id or alias.
	BlockchainID components.XChainID `pathParam:"style=simple,explode=false,name=blockchainId"`
	// Either mainnet or testnet/fuji.
	Network *components.GlobalParamNetwork `pathParam:"style=simple,explode=false,name=network"`
}

func (l ListLatestXChainVerticesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListLatestXChainVerticesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListLatestXChainVerticesRequest) GetPageToken() *string {
	if o == nil {
		return nil
	}
	return o.PageToken
}

func (o *ListLatestXChainVerticesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListLatestXChainVerticesRequest) GetBlockchainID() components.XChainID {
	if o == nil {
		return components.XChainID("")
	}
	return o.BlockchainID
}

func (o *ListLatestXChainVerticesRequest) GetNetwork() *components.GlobalParamNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

type ListLatestXChainVerticesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	ListXChainVerticesResponse *components.ListXChainVerticesResponse

	Next func() (*ListLatestXChainVerticesResponse, error)
}

func (o *ListLatestXChainVerticesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListLatestXChainVerticesResponse) GetListXChainVerticesResponse() *components.ListXChainVerticesResponse {
	if o == nil {
		return nil
	}
	return o.ListXChainVerticesResponse
}
