// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type PostTransactionExportJobRequestType string

const (
	PostTransactionExportJobRequestTypeCreateEvmTransactionExportRequest            PostTransactionExportJobRequestType = "CreateEvmTransactionExportRequest"
	PostTransactionExportJobRequestTypeCreatePrimaryNetworkTransactionExportRequest PostTransactionExportJobRequestType = "CreatePrimaryNetworkTransactionExportRequest"
)

type PostTransactionExportJobRequest struct {
	CreateEvmTransactionExportRequest            *components.CreateEvmTransactionExportRequest            `queryParam:"inline"`
	CreatePrimaryNetworkTransactionExportRequest *components.CreatePrimaryNetworkTransactionExportRequest `queryParam:"inline"`

	Type PostTransactionExportJobRequestType
}

func CreatePostTransactionExportJobRequestCreateEvmTransactionExportRequest(createEvmTransactionExportRequest components.CreateEvmTransactionExportRequest) PostTransactionExportJobRequest {
	typ := PostTransactionExportJobRequestTypeCreateEvmTransactionExportRequest

	return PostTransactionExportJobRequest{
		CreateEvmTransactionExportRequest: &createEvmTransactionExportRequest,
		Type:                              typ,
	}
}

func CreatePostTransactionExportJobRequestCreatePrimaryNetworkTransactionExportRequest(createPrimaryNetworkTransactionExportRequest components.CreatePrimaryNetworkTransactionExportRequest) PostTransactionExportJobRequest {
	typ := PostTransactionExportJobRequestTypeCreatePrimaryNetworkTransactionExportRequest

	return PostTransactionExportJobRequest{
		CreatePrimaryNetworkTransactionExportRequest: &createPrimaryNetworkTransactionExportRequest,
		Type: typ,
	}
}

func (u *PostTransactionExportJobRequest) UnmarshalJSON(data []byte) error {

	var createEvmTransactionExportRequest components.CreateEvmTransactionExportRequest = components.CreateEvmTransactionExportRequest{}
	if err := utils.UnmarshalJSON(data, &createEvmTransactionExportRequest, "", true, true); err == nil {
		u.CreateEvmTransactionExportRequest = &createEvmTransactionExportRequest
		u.Type = PostTransactionExportJobRequestTypeCreateEvmTransactionExportRequest
		return nil
	}

	var createPrimaryNetworkTransactionExportRequest components.CreatePrimaryNetworkTransactionExportRequest = components.CreatePrimaryNetworkTransactionExportRequest{}
	if err := utils.UnmarshalJSON(data, &createPrimaryNetworkTransactionExportRequest, "", true, true); err == nil {
		u.CreatePrimaryNetworkTransactionExportRequest = &createPrimaryNetworkTransactionExportRequest
		u.Type = PostTransactionExportJobRequestTypeCreatePrimaryNetworkTransactionExportRequest
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PostTransactionExportJobRequest", string(data))
}

func (u PostTransactionExportJobRequest) MarshalJSON() ([]byte, error) {
	if u.CreateEvmTransactionExportRequest != nil {
		return utils.MarshalJSON(u.CreateEvmTransactionExportRequest, "", true)
	}

	if u.CreatePrimaryNetworkTransactionExportRequest != nil {
		return utils.MarshalJSON(u.CreatePrimaryNetworkTransactionExportRequest, "", true)
	}

	return nil, errors.New("could not marshal union type PostTransactionExportJobRequest: all fields are null")
}

type PostTransactionExportJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	OperationStatusResponse *components.OperationStatusResponse
}

func (o *PostTransactionExportJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostTransactionExportJobResponse) GetOperationStatusResponse() *components.OperationStatusResponse {
	if o == nil {
		return nil
	}
	return o.OperationStatusResponse
}
