// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ReindexNftGlobals struct {
	// A supported EVM chain id, chain alias, or blockchain id.
	ChainID *string `pathParam:"style=simple,explode=false,name=chainId"`
}

func (o *ReindexNftGlobals) GetChainID() *string {
	if o == nil {
		return nil
	}
	return o.ChainID
}

type ReindexNftRequest struct {
	// A supported evm chain id or blockchain id. Use the `/chains` endpoint to get a list of supported chain ids.
	ChainID *string `pathParam:"style=simple,explode=false,name=chainId"`
	// Contract address on the relevant chain.
	Address string `pathParam:"style=simple,explode=false,name=address"`
	// TokenId on the contract
	TokenID string `pathParam:"style=simple,explode=false,name=tokenId"`
}

func (o *ReindexNftRequest) GetChainID() *string {
	if o == nil {
		return nil
	}
	return o.ChainID
}

func (o *ReindexNftRequest) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *ReindexNftRequest) GetTokenID() string {
	if o == nil {
		return ""
	}
	return o.TokenID
}

type ReindexNftResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *ReindexNftResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
