// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type SupportedChainsRequest struct {
	// Either mainnet or testnet/fuji.
	Network *components.Network `queryParam:"style=form,explode=true,name=network"`
	// Filter by feature.
	Feature *components.APIFeature `queryParam:"style=form,explode=true,name=feature"`
}

func (o *SupportedChainsRequest) GetNetwork() *components.Network {
	if o == nil {
		return nil
	}
	return o.Network
}

func (o *SupportedChainsRequest) GetFeature() *components.APIFeature {
	if o == nil {
		return nil
	}
	return o.Feature
}

type SupportedChainsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	ListChainsResponse *components.ListChainsResponse
}

func (o *SupportedChainsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SupportedChainsResponse) GetListChainsResponse() *components.ListChainsResponse {
	if o == nil {
		return nil
	}
	return o.ListChainsResponse
}
