export {
  abey,
  abstract,
  abstractTestnet,
  acala,
  acria,
  adf,
  aioz,
  alephZero,
  alephZeroTestnet,
  alienx,
  alienxHalTestnet,
  ancient8,
  ancient8Sepolia,
  anvil,
  apeChain,
  apexTestnet,
  arbitrum,
  arbitrumGoerli,
  arbitrumNova,
  arbitrumSepolia,
  arenaz,
  areonNetwork,
  areonNetworkTestnet,
  artelaTestnet,
  arthera,
  artheraTestnet,
  assetChain,
  assetChainTestnet,
  astar,
  astarZkEVM,
  astarZkyoto,
  atletaOlympia,
  aurora,
  auroraTestnet,
  auroria,
  b3,
  b3Sepolia,
  bahamut,
  base,
  basecampTestnet,
  baseGoerli,
  baseSepolia,
  beam,
  beamTestnet,
  bearNetworkChainMainnet,
  bearNetworkChainTestnet,
  berachain,
  berachainBepolia,
  berachainTestnet,
  berachainTestnetbArtio,
  bevmMainnet,
  bifrost,
  birdlayer,
  bitgert,
  bitkub,
  bitkubTestnet,
  bitlayer,
  bitlayerTestnet,
  bitrock,
  bitTorrent,
  bitTorrentTestnet,
  blast,
  blastSepolia,
  bob,
  boba,
  bobaSepolia,
  bobSepolia,
  boolBetaMainnet,
  botanixTestnet,
  bounceBit,
  bounceBitTestnet,
  bronos,
  bronosTestnet,
  bsc,
  bscGreenfield,
  bscTestnet,
  bsquared,
  bsquaredTestnet,
  btr,
  btrTestnet,
  bxn,
  bxnTestnet,
  cannon,
  canto,
  celo,
  celoAlfajores,
  chang,
  chiliz,
  chips,
  citreaTestnet,
  classic,
  coinbit,
  coinex,
  confluxESpace,
  confluxESpaceTestnet,
  coreDao,
  coreTestnet1,
  coreTestnet2,
  corn,
  cornTestnet,
  crab,
  creatorTestnet,
  creditCoin3Mainnet,
  creditCoin3Testnet,
  cronos,
  cronosTestnet,
  cronoszkEVM,
  cronoszkEVMTestnet,
  crossbell,
  curtis,
  cyber,
  cyberTestnet,
  dailyNetwork,
  dailyNetworkTestnet,
  darwinia,
  dbkchain,
  dchain,
  dchainTestnet,
  defichainEvm,
  defichainEvmTestnet,
  degen,
  dfk,
  diode,
  disChain,
  dodochainTestnet,
  dogechain,
  donatuz,
  dosChain,
  dosChainTestnet,
  dreyerxMainnet,
  dreyerxTestnet,
  dustboyIoT,
  dymension,
  edexa,
  edexaTestnet,
  edgeless,
  edgelessTestnet,
  edgeware,
  edgewareTestnet,
  eduChain,
  eduChainTestnet,
  ekta,
  ektaTestnet,
  elastos,
  elastosTestnet,
  electroneum,
  electroneumTestnet,
  elysiumTestnet,
  energy,
  enuls,
  eon,
  eos,
  eosTestnet,
  etherlink,
  etherlinkTestnet,
  ethernity,
  etp,
  evmos,
  evmosTestnet,
  excelonMainnet,
  expanse,
  exsat,
  exsatTestnet,
  fantom,
} from "viem/chains";
export type {
  Assign,
  Chain,
  Omit,
  PartialBy,
  Prettify,
  UnionLooseOmit,
} from "viem/chains";
export { avalanche } from "./avalanche.js";
export { avalancheFuji } from "./avalancheFuji.js";
export { avalancheLocal } from "./avalancheLocal.js";
/** @deprecated Use `sonicTestnet` instead. */
export {
  fantomSonicTestnet,
  fantomTestnet,
  fibo,
  filecoin,
  filecoinCalibration,
  filecoinHyperspace,
  fireChain,
  flame,
  flare,
  flareTestnet,
  flowMainnet,
} from "viem/chains";
/** @deprecated */
export {
  flowPreviewnet,
  flowTestnet,
  fluence,
  fluenceStage,
  fluenceTestnet,
  fluentTestnet,
  form,
  forma,
  formicarium,
  formTestnet,
  forta,
} from "viem/chains";
/** @deprecated Use `anvil` instead. */
export {
  foundry,
  fraxtal,
  fraxtalTestnet,
  funkiMainnet,
  funkiSepolia,
  fuse,
  fuseSparknet,
  fusion,
  fusionTestnet,
  garnet,
  geist,
  genesys,
  glideL1Protocol,
  glideL2Protocol,
  gnosis,
  gnosisChiado,
  goat,
  gobi,
  goChain,
  godwoken,
  goerli,
  gravity,
  gunz,
  guruNetwork,
  guruTestnet,
  ham,
  happychainTestnet,
  haqqMainnet,
  haqqTestedge2,
  hardhat,
  harmonyOne,
  hashkey,
  hashkeyTestnet,
  haustTestnet,
  hedera,
  hederaPreviewnet,
  hederaTestnet,
  hela,
  hemi,
  hemiSepolia,
  holesky,
  hoodi,
  hpb,
  huddle01Mainnet,
  huddle01Testnet,
  humanode,
  humanodeTestnet5,
  hychain,
  hychainTestnet,
  idchain,
  immutableZkEvm,
  immutableZkEvmTestnet,
  inEVM,
  initVerse,
  initVerseGenesis,
  ink,
  inkSepolia,
  iota,
  iotaTestnet,
  iotex,
  iotexTestnet,
  iSunCoin,
  jbc,
  jbcTestnet,
  juneo,
  juneoBCH1Chain,
  juneoDAI1Chain,
  juneoDOGE1Chain,
  juneoEUR1Chain,
  juneoGLD1Chain,
  juneoLINK1Chain,
  juneoLTC1Chain,
  juneomBTC1Chain,
  juneoSGD1Chain,
  juneoSocotraTestnet,
  juneoUSD1Chain,
  juneoUSDT1Chain,
  karura,
} from "viem/chains";
/** @deprecated Use `kakarotStarknetSepolia` instead. */
export {
  kakarotSepolia,
  kakarotStarknetSepolia,
  kardiaChain,
  kava,
  kavaTestnet,
  kcc,
  kinto,
} from "viem/chains";
/** @deprecated Use `kaia` instead. */
export { kaia, kairos, klaytn } from "viem/chains";
/** @deprecated Use `kairos` instead. */
export {
  klaytnBaobab,
  koi,
  kroma,
  kromaSepolia,
  l3x,
  l3xTestnet,
  lavita,
  lens,
  lensTestnet,
  lestnet,
  lightlinkPegasus,
  lightlinkPhoenix,
  linea,
} from "viem/chains";
/** @deprecated Use `lineaSepolia` instead. */
export { lineaGoerli, lineaSepolia } from "viem/chains";
/** @deprecated Use `lineaSepolia` instead. */
export {
  lineaTestnet,
  lisk,
  liskSepolia,
  localhost,
  loop,
  lukso,
  luksoTestnet,
  lumiaMainnet,
  lumiaTestnet,
  lumoz,
  lumozTestnet,
  lycan,
  lyra,
  mainnet,
  mandala,
  manta,
  mantaSepoliaTestnet,
  mantaTestnet,
  mantle,
  mantleSepoliaTestnet,
  mantleTestnet,
  mapProtocol,
  matchain,
  matchainTestnet,
  mchVerse,
  megaethTestnet,
  mekong,
  meld,
  memecore,
  merlin,
  merlinErigonTestnet,
  metachain,
  metachainIstanbul,
  metadium,
  metalL2,
  meter,
  meterTestnet,
  metis,
  metisSepolia,
} from "viem/chains";
/** @deprecated Use `metisSepolia` instead. */
export {
  metisGoerli,
  mev,
  mevTestnet,
  mint,
  mintSepoliaTestnet,
  mitosisTestnet,
  mode,
  modeTestnet,
  monadTestnet,
  moonbaseAlpha,
  moonbeam,
  moonbeamDev,
  moonriver,
  morph,
  morphHolesky,
  morphSepolia,
  nahmii,
  nautilus,
  near,
  nearTestnet,
  neonDevnet,
  neonMainnet,
  neoxMainnet,
  neoxT4,
  newton,
  nexi,
  nexilix,
  nibiru,
  oasisTestnet,
  oasys,
  odysseyTestnet,
  okc,
  omax,
  oneWorld,
  oortMainnetDev,
  opBNB,
  opBNBTestnet,
  optimism,
  optimismGoerli,
  optimismSepolia,
  optopia,
  optopiaTestnet,
  orderly,
  orderlySepolia,
  otimDevnet,
  palm,
  palmTestnet,
  peaq,
  pgn,
  pgnTestnet,
  phoenix,
  planq,
  playfiAlbireo,
  plinga,
} from "viem/chains";
/** @deprecated Use `plumeMainnet` instead. */
export { plume } from "viem/chains";
/** @deprecated Use `plumeSepolia` instead. */
export { plumeDevnet, plumeMainnet, plumeSepolia } from "viem/chains";
/** @deprecated Use `plumeSepolia` instead. */
export {
  plumeTestnet,
  polterTestnet,
  polygon,
  polygonAmoy,
  polygonMumbai,
  polygonZkEvm,
  polygonZkEvmCardona,
} from "viem/chains";
/** @deprecated Use `polygonZkEvmCardona` instead. */
export {
  polygonZkEvmTestnet,
  polynomial,
  polynomialSepolia,
  premiumBlockTestnet,
  pulsechain,
  pulsechainV4,
  pumpfiTestnet,
  pyrope,
  ql1,
  qMainnet,
  qTestnet,
  real,
  redbellyMainnet,
  redbellyTestnet,
  reddioSepolia,
  redstone,
  rei,
  reyaNetwork,
  rivalz,
  rollux,
  rolluxTestnet,
  ronin,
  root,
  rootPorcini,
  rootstock,
  rootstockTestnet,
  rss3,
  rss3Sepolia,
  saakuru,
  saga,
  saigon,
  sanko,
  sapphire,
  sapphireTestnet,
  satoshiVM,
  satoshiVMTestnet,
  scroll,
  scrollSepolia,
  sei,
  seiDevnet,
  seismicDevnet,
  seiTestnet,
  sepolia,
  shape,
  shapeSepolia,
  shardeum,
  shardeumSphinx,
  shibarium,
  shibariumTestnet,
  shiden,
  shimmer,
  shimmerTestnet,
  sidraChain,
  silicon,
  siliconSepolia,
  sixProtocol,
  skaleBlockBrawlers,
  skaleCalypso,
  skaleCalypsoTestnet,
  skaleCryptoBlades,
} from "viem/chains";
/** @deprecated */
export {
  skaleCryptoColosseum,
  skaleEuropa,
  skaleEuropaTestnet,
  skaleExorde,
} from "viem/chains";
/** @deprecated */
export {
  skaleHumanProtocol,
  skaleNebula,
  skaleNebulaTestnet,
} from "viem/chains";
/** @deprecated Use `skaleEuropa` instead.*/
export {
  skaleRazor,
  skaleTitan,
  skaleTitanTestnet,
  sketchpad,
  snax,
  snaxTestnet,
  somniaTestnet,
  soneium,
  soneiumMinato,
  sonic,
} from "viem/chains";
/** @deprecated Use `sonicBlazeTestnet` instead. */
export {
  songbird,
  songbirdTestnet,
  sonicBlazeTestnet,
  sonicTestnet,
  sophon,
  sophonTestnet,
  spicy,
  statusSepolia as statusNetworkSepolia,
  statusSepolia,
  step,
  story,
  storyAeneid,
} from "viem/chains";
/** @deprecated Use `storyAeneid` instead. */
export { storyOdyssey } from "viem/chains";
/** @deprecated Use `storyAeneid` instead. */
export {
  storyTestnet,
  stratis,
  superlumio,
  superposition,
  superseed,
  superseedSepolia,
  swan,
  swanProximaTestnet,
  swanSaturnTestnet,
  swellchain,
  swellchainTestnet,
  swissdlt,
  syscoin,
  syscoinTestnet,
  taiko,
  taikoHekla,
  taikoJolnir,
  taikoKatla,
  taikoTestnetSepolia,
  taraxa,
  taraxaTestnet,
  telcoinTestnet,
  telos,
  telosTestnet,
  tenet,
  ternoa,
  thaiChain,
  that,
  theta,
  thetaTestnet,
  thunderCore,
  thunderTestnet,
  tiktrixTestnet,
  tomb,
  treasure,
  treasureTopaz,
  tron,
  tronShasta,
  ubiq,
  ultra,
  ultraTestnet,
  ultron,
  ultronTestnet,
  unichain,
  unichainSepolia,
  unique,
  uniqueOpal,
  uniqueQuartz,
  unreal,
  vanar,
  vechain,
  velas,
  viction,
  victionTestnet,
  vision,
  visionTestnet,
  wanchain,
  wanchainTestnet,
  weaveVMAlphanet,
  wemix,
  wemixTestnet,
  westendAssetHub,
  whitechain,
  whitechainTestnet,
  wmcTestnet,
  worldchain,
  worldchainSepolia,
  worldLand,
  /** @deprecated Use `xLayerTestnet` */
  x1Testnet,
  xai,
  xaiTestnet,
  xdc,
  xdcTestnet,
  xLayer,
  xLayerTestnet,
  xrOne,
  xrplevmDevnet,
  xrplevmTestnet,
  xrSepolia,
  yooldoVerse,
  yooldoVerseTestnet,
  zenchainTestnet,
  zeniq,
  zeroG,
  zeroNetwork,
  zetachain,
  zetachainAthensTestnet,
  zhejiang,
  zilliqa,
  zilliqaTestnet,
  zircuit,
  zircuitGarfieldTestnet,
} from "viem/chains";
/** @deprecated Use zircuitGarfieldTestnet instead */
export {
  zircuitTestnet,
  zkFair,
  zkFairTestnet,
  zkLinkNova,
  zkLinkNovaSepoliaTestnet,
  /** @deprecated Use `zksync` instead */
  zksync as zkSync,
  zksync,
  /** @deprecated Use `zksync` instead */
  zksyncInMemoryNode as zkSyncInMemoryNode,
  zksyncInMemoryNode,
  zksyncLocalCustomHyperchain,
  zksyncLocalHyperchain,
  zksyncLocalHyperchainL1,
  /** @deprecated Use `zksync` instead */
  zksyncLocalNode as zkSyncLocalNode,
  zksyncLocalNode,
  /** @deprecated Use `zksync` instead */
  zksyncSepoliaTestnet as zkSyncSepoliaTestnet,
  zksyncSepoliaTestnet,
  zora,
  zoraSepolia,
  zoraTestnet,
} from "viem/chains";
