/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EVMAddressActivityResponse,
  EVMAddressActivityResponse$inboundSchema,
  EVMAddressActivityResponse$Outbound,
  EVMAddressActivityResponse$outboundSchema,
} from "./evmaddressactivityresponse.js";
import {
  PlatformActivityResponse,
  PlatformActivityResponse$inboundSchema,
  PlatformActivityResponse$Outbound,
  PlatformActivityResponse$outboundSchema,
} from "./platformactivityresponse.js";

export type Webhook = EVMAddressActivityResponse | PlatformActivityResponse;

export type ListWebhooksResponse = {
  /**
   * A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  webhooks: Array<EVMAddressActivityResponse | PlatformActivityResponse>;
};

/** @internal */
export const Webhook$inboundSchema: z.ZodType<Webhook, z.ZodTypeDef, unknown> =
  z.union([
    EVMAddressActivityResponse$inboundSchema,
    PlatformActivityResponse$inboundSchema,
  ]);

/** @internal */
export type Webhook$Outbound =
  | EVMAddressActivityResponse$Outbound
  | PlatformActivityResponse$Outbound;

/** @internal */
export const Webhook$outboundSchema: z.ZodType<
  Webhook$Outbound,
  z.ZodTypeDef,
  Webhook
> = z.union([
  EVMAddressActivityResponse$outboundSchema,
  PlatformActivityResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Webhook$ {
  /** @deprecated use `Webhook$inboundSchema` instead. */
  export const inboundSchema = Webhook$inboundSchema;
  /** @deprecated use `Webhook$outboundSchema` instead. */
  export const outboundSchema = Webhook$outboundSchema;
  /** @deprecated use `Webhook$Outbound` instead. */
  export type Outbound = Webhook$Outbound;
}

export function webhookToJSON(webhook: Webhook): string {
  return JSON.stringify(Webhook$outboundSchema.parse(webhook));
}

export function webhookFromJSON(
  jsonString: string,
): SafeParseResult<Webhook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Webhook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Webhook' from JSON`,
  );
}

/** @internal */
export const ListWebhooksResponse$inboundSchema: z.ZodType<
  ListWebhooksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nextPageToken: z.string().optional(),
  webhooks: z.array(
    z.union([
      EVMAddressActivityResponse$inboundSchema,
      PlatformActivityResponse$inboundSchema,
    ]),
  ),
});

/** @internal */
export type ListWebhooksResponse$Outbound = {
  nextPageToken?: string | undefined;
  webhooks: Array<
    EVMAddressActivityResponse$Outbound | PlatformActivityResponse$Outbound
  >;
};

/** @internal */
export const ListWebhooksResponse$outboundSchema: z.ZodType<
  ListWebhooksResponse$Outbound,
  z.ZodTypeDef,
  ListWebhooksResponse
> = z.object({
  nextPageToken: z.string().optional(),
  webhooks: z.array(
    z.union([
      EVMAddressActivityResponse$outboundSchema,
      PlatformActivityResponse$outboundSchema,
    ]),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListWebhooksResponse$ {
  /** @deprecated use `ListWebhooksResponse$inboundSchema` instead. */
  export const inboundSchema = ListWebhooksResponse$inboundSchema;
  /** @deprecated use `ListWebhooksResponse$outboundSchema` instead. */
  export const outboundSchema = ListWebhooksResponse$outboundSchema;
  /** @deprecated use `ListWebhooksResponse$Outbound` instead. */
  export type Outbound = ListWebhooksResponse$Outbound;
}

export function listWebhooksResponseToJSON(
  listWebhooksResponse: ListWebhooksResponse,
): string {
  return JSON.stringify(
    ListWebhooksResponse$outboundSchema.parse(listWebhooksResponse),
  );
}

export function listWebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhooksResponse' from JSON`,
  );
}
