/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { ChainMetrics } from "./chainmetrics.js";

export class Chain extends ClientSDK {
  private _metrics?: ChainMetrics;
  get metrics(): ChainMetrics {
    return (this._metrics ??= new ChainMetrics(this._options));
  }
}
