export {
  call,
  createAccessList,
  createBlockFilter,
  createContractEventFilter,
  createEventFilter,
  createPendingTransactionFilter,
  estimateContractGas,
  estimateFeesPerGas,
  estimateGas,
  estimateMaxPriorityFeePerGas,
  getBalance,
  getBlobBaseFee,
  getBlock,
  getBlockNumber,
  getBlockTransactionCount,
  /** @deprecated Use `getCode` instead  */
  getCode as getBytecode,
  getChainId,
  getCode,
  getContractEvents,
  getEip712Domain,
  getFeeHistory,
  getFilterChanges,
  getFilterLogs,
  getGasPrice,
  getLogs,
  getStorageAt,
  getTransaction,
  getTransactionConfirmations,
  getTransactionCount,
  getTransactionReceipt,
  type CallErrorType,
  type CallParameters,
  type CallReturnType,
  type CreateAccessListErrorType,
  type CreateAccessListParameters,
  type CreateAccessListReturnType,
  type CreateBlockFilterErrorType,
  type CreateBlockFilterReturnType,
  type CreateContractEventFilterErrorType,
  type CreateContractEventFilterParameters,
  type CreateContractEventFilterReturnType,
  type CreateEventFilterErrorType,
  type CreateEventFilterParameters,
  type CreateEventFilterReturnType,
  type CreatePendingTransactionFilterErrorType,
  type CreatePendingTransactionFilterReturnType,
  type EstimateContractGasErrorType,
  type EstimateContractGasParameters,
  type EstimateContractGasReturnType,
  type EstimateFeesPerGasErrorType,
  type EstimateFeesPerGasParameters,
  type EstimateFeesPerGasReturnType,
  type EstimateGasErrorType,
  type EstimateGasParameters,
  type EstimateGasReturnType,
  type EstimateMaxPriorityFeePerGasErrorType,
  type EstimateMaxPriorityFeePerGasParameters,
  type EstimateMaxPriorityFeePerGasReturnType,
  type GetBalanceErrorType,
  type GetBalanceParameters,
  type GetBalanceReturnType,
  type GetBlobBaseFeeErrorType,
  type GetBlobBaseFeeReturnType,
  type GetBlockErrorType,
  type GetBlockNumberErrorType,
  type GetBlockNumberParameters,
  type GetBlockNumberReturnType,
  type GetBlockParameters,
  type GetBlockReturnType,
  type GetBlockTransactionCountErrorType,
  type GetBlockTransactionCountParameters,
  type GetBlockTransactionCountReturnType,
  /** @deprecated Use `GetCodeErrorType` instead */
  type GetCodeErrorType as GetBytecodeErrorType,
  /** @deprecated Use `GetCodeParameters` instead */
  type GetCodeParameters as GetBytecodeParameters,
  /** @deprecated Use `GetCodeReturnType` instead  */
  type GetCodeReturnType as GetBytecodeReturnType,
  type GetChainIdErrorType,
  type GetChainIdReturnType,
  type GetCodeErrorType,
  type GetCodeParameters,
  type GetCodeReturnType,
  type GetContractEventsErrorType,
  type GetContractEventsParameters,
  type GetContractEventsReturnType,
  type GetEip712DomainErrorType,
  type GetEip712DomainParameters,
  type GetEip712DomainReturnType,
  type GetFeeHistoryErrorType,
  type GetFeeHistoryParameters,
  type GetFeeHistoryReturnType,
  type GetFilterChangesErrorType,
  type GetFilterChangesParameters,
  type GetFilterChangesReturnType,
  type GetFilterLogsErrorType,
  type GetFilterLogsParameters,
  type GetFilterLogsReturnType,
  type GetGasPriceErrorType,
  type GetGasPriceReturnType,
  type GetLogsErrorType,
  type GetLogsParameters,
  type GetLogsReturnType,
  type GetStorageAtErrorType,
  type GetStorageAtParameters,
  type GetStorageAtReturnType,
  type GetTransactionConfirmationsErrorType,
  type GetTransactionConfirmationsParameters,
  type GetTransactionConfirmationsReturnType,
  type GetTransactionCountErrorType,
  type GetTransactionCountParameters,
  type GetTransactionCountReturnType,
  type GetTransactionErrorType,
  type GetTransactionParameters,
  type GetTransactionReceiptErrorType,
  type GetTransactionReceiptParameters,
  type GetTransactionReceiptReturnType,
  type GetTransactionReturnType,
} from "viem/actions";

export {
  getProof,
  multicall,
  readContract,
  /** @deprecated Use `simulateBlocks` instead */
  simulateBlocks as simulate,
  simulateBlocks,
  simulateCalls,
  simulateContract,
  uninstallFilter,
  verifyHash,
  verifyMessage,
  verifyTypedData,
  waitForTransactionReceipt,
  watchBlockNumber,
  watchBlocks,
  watchContractEvent,
  watchEvent,
  watchPendingTransactions,
  type GetProofErrorType,
  type GetProofParameters,
  type GetProofReturnType,
  type MulticallErrorType,
  type MulticallParameters,
  type MulticallReturnType,
  type OnBlock,
  type OnBlockNumberFn,
  type OnBlockNumberParameter,
  type OnBlockParameter,
  type OnTransactionsFn,
  type OnTransactionsParameter,
  type ReadContractErrorType,
  type ReadContractParameters,
  type ReadContractReturnType,
  type ReplacementReason,
  type ReplacementReturnType,
  type SimulateBlocksErrorType,
  type SimulateBlocksParameters,
  type SimulateBlocksReturnType,
  type SimulateCallsErrorType,
  type SimulateCallsParameters,
  type SimulateCallsReturnType,
  type SimulateContractErrorType,
  type SimulateContractParameters,
  type SimulateContractReturnType,
  /** @deprecated Use `SimulateBlocksErrorType` instead */
  type SimulateBlocksErrorType as SimulateErrorType,
  /** @deprecated Use `SimulateBlocksParameters` instead */
  type SimulateBlocksParameters as SimulateParameters,
  /** @deprecated Use `SimulateBlocksReturnType` instead */
  type SimulateBlocksReturnType as SimulateReturnType,
  type UninstallFilterErrorType,
  type UninstallFilterParameters,
  type UninstallFilterReturnType,
  type VerifyHashErrorType,
  type VerifyHashParameters,
  type VerifyHashReturnType,
  type VerifyMessageErrorType,
  type VerifyMessageParameters,
  type VerifyMessageReturnType,
  type VerifyTypedDataErrorType,
  type VerifyTypedDataParameters,
  type VerifyTypedDataReturnType,
  type WaitForTransactionReceiptErrorType,
  type WaitForTransactionReceiptParameters,
  type WaitForTransactionReceiptReturnType,
  type WatchBlockNumberErrorType,
  type WatchBlockNumberParameters,
  type WatchBlockNumberReturnType,
  type WatchBlocksErrorType,
  type WatchBlocksParameters,
  type WatchBlocksReturnType,
  type WatchContractEventErrorType,
  type WatchContractEventParameters,
  type WatchContractEventReturnType,
  type WatchEventOnLogsFn,
  type WatchEventOnLogsParameter,
  type WatchEventParameters,
  type WatchEventReturnType,
  type WatchPendingTransactionsErrorType,
  type WatchPendingTransactionsParameters,
  type WatchPendingTransactionsReturnType,
} from "viem/actions";
