/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Chains } from "./chains.js";
import { Contracts } from "./contracts.js";
import { EvmBalances } from "./evmbalances.js";
import { EvmBlocks } from "./evmblocks.js";
import { EvmTransactions } from "./evmtransactions.js";

export class Evm extends ClientSDK {
  private _chains?: Chains;
  get chains(): Chains {
    return (this._chains ??= new Chains(this._options));
  }

  private _transactions?: EvmTransactions;
  get transactions(): EvmTransactions {
    return (this._transactions ??= new EvmTransactions(this._options));
  }

  private _blocks?: EvmBlocks;
  get blocks(): EvmBlocks {
    return (this._blocks ??= new EvmBlocks(this._options));
  }

  private _balances?: EvmBalances;
  get balances(): EvmBalances {
    return (this._balances ??= new EvmBalances(this._options));
  }

  private _contracts?: Contracts;
  get contracts(): Contracts {
    return (this._contracts ??= new Contracts(this._options));
  }
}
