/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetApiLogsServerList = [
  "https://data-api.avax.network",
] as const;

/**
 * Filter data by request type.
 */
export const GetApiLogsRequestType = {
  Data: "data",
  Rpc: "rpc",
} as const;
/**
 * Filter data by request type.
 */
export type GetApiLogsRequestType = ClosedEnum<typeof GetApiLogsRequestType>;

export type GetApiLogsRequest = {
  /**
   * Organization ID to fetch usage metrics for
   */
  orgId?: string | undefined;
  /**
   * The start time of the range as a UNIX timestamp. The requested start time  will be rounded down to 0:00 UTC of the day.
   */
  startTimestamp?: number | undefined;
  /**
   * The end time of the range as a UNIX timestamp. The requested end time will be rounded down to 0:00 UTC of the day.
   */
  endTimestamp?: number | undefined;
  /**
   * Filter data by chain ID.
   */
  chainId?: string | undefined;
  /**
   * Filter data by response status code.
   */
  responseCode?: string | undefined;
  /**
   * Filter data by request type.
   */
  requestType?: GetApiLogsRequestType | undefined;
  /**
   * Filter data by API key ID.
   */
  apiKeyId?: string | undefined;
  /**
   * Filter data by request path.
   */
  requestPath?: string | undefined;
  /**
   * A page token, received from a previous list call. Provide this to retrieve the subsequent page.
   */
  pageToken?: string | undefined;
  /**
   * The maximum number of items to return.
   */
  pageSize?: number | undefined;
};

export type GetApiLogsResponse = {
  result: components.LogsResponseDTO;
};

/** @internal */
export const GetApiLogsRequestType$inboundSchema: z.ZodNativeEnum<
  typeof GetApiLogsRequestType
> = z.nativeEnum(GetApiLogsRequestType);
/** @internal */
export const GetApiLogsRequestType$outboundSchema: z.ZodNativeEnum<
  typeof GetApiLogsRequestType
> = GetApiLogsRequestType$inboundSchema;

/** @internal */
export const GetApiLogsRequest$inboundSchema: z.ZodType<
  GetApiLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  orgId: z.string().optional(),
  startTimestamp: z.number().int().optional(),
  endTimestamp: z.number().int().optional(),
  chainId: z.string().optional(),
  responseCode: z.string().optional(),
  requestType: GetApiLogsRequestType$inboundSchema.optional(),
  apiKeyId: z.string().optional(),
  requestPath: z.string().optional(),
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
});
/** @internal */
export type GetApiLogsRequest$Outbound = {
  orgId?: string | undefined;
  startTimestamp?: number | undefined;
  endTimestamp?: number | undefined;
  chainId?: string | undefined;
  responseCode?: string | undefined;
  requestType?: string | undefined;
  apiKeyId?: string | undefined;
  requestPath?: string | undefined;
  pageToken?: string | undefined;
  pageSize: number;
};

/** @internal */
export const GetApiLogsRequest$outboundSchema: z.ZodType<
  GetApiLogsRequest$Outbound,
  z.ZodTypeDef,
  GetApiLogsRequest
> = z.object({
  orgId: z.string().optional(),
  startTimestamp: z.number().int().optional(),
  endTimestamp: z.number().int().optional(),
  chainId: z.string().optional(),
  responseCode: z.string().optional(),
  requestType: GetApiLogsRequestType$outboundSchema.optional(),
  apiKeyId: z.string().optional(),
  requestPath: z.string().optional(),
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
});

export function getApiLogsRequestToJSON(
  getApiLogsRequest: GetApiLogsRequest,
): string {
  return JSON.stringify(
    GetApiLogsRequest$outboundSchema.parse(getApiLogsRequest),
  );
}
export function getApiLogsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiLogsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiLogsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiLogsRequest' from JSON`,
  );
}

/** @internal */
export const GetApiLogsResponse$inboundSchema: z.ZodType<
  GetApiLogsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.LogsResponseDTO$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetApiLogsResponse$Outbound = {
  Result: components.LogsResponseDTO$Outbound;
};

/** @internal */
export const GetApiLogsResponse$outboundSchema: z.ZodType<
  GetApiLogsResponse$Outbound,
  z.ZodTypeDef,
  GetApiLogsResponse
> = z.object({
  result: components.LogsResponseDTO$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getApiLogsResponseToJSON(
  getApiLogsResponse: GetApiLogsResponse,
): string {
  return JSON.stringify(
    GetApiLogsResponse$outboundSchema.parse(getApiLogsResponse),
  );
}
export function getApiLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiLogsResponse' from JSON`,
  );
}
