/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetLastActivityTimestampByAddressesV2ServerList = [
  "https://data-api.avax.network",
] as const;

export type GetLastActivityTimestampByAddressesV2Globals = {
  /**
   * A supported network type mainnet or testnet/fuji.
   */
  network?: components.GlobalParamNetwork | undefined;
};

export type GetLastActivityTimestampByAddressesV2Request = {
  /**
   * A primary network blockchain id or alias.
   */
  blockchainId: components.BlockchainId;
  /**
   * Either mainnet or testnet/fuji.
   */
  network?: components.GlobalParamNetwork | undefined;
  /**
   * The minimum UTXO amount in nAVAX (inclusive), used to filter the set of UTXOs being returned. Default is 0.
   */
  minUtxoAmount?: number | undefined;
  primaryNetworkAddressesBodyDto: components.PrimaryNetworkAddressesBodyDto;
};

/**
 * Successful response
 */
export type GetLastActivityTimestampByAddressesV2Response =
  components.LastActivityTimestamp;

/** @internal */
export const GetLastActivityTimestampByAddressesV2Globals$inboundSchema:
  z.ZodType<
    GetLastActivityTimestampByAddressesV2Globals,
    z.ZodTypeDef,
    unknown
  > = z.object({
    network: components.GlobalParamNetwork$inboundSchema.optional(),
  });
/** @internal */
export type GetLastActivityTimestampByAddressesV2Globals$Outbound = {
  network?: string | undefined;
};

/** @internal */
export const GetLastActivityTimestampByAddressesV2Globals$outboundSchema:
  z.ZodType<
    GetLastActivityTimestampByAddressesV2Globals$Outbound,
    z.ZodTypeDef,
    GetLastActivityTimestampByAddressesV2Globals
  > = z.object({
    network: components.GlobalParamNetwork$outboundSchema.optional(),
  });

export function getLastActivityTimestampByAddressesV2GlobalsToJSON(
  getLastActivityTimestampByAddressesV2Globals:
    GetLastActivityTimestampByAddressesV2Globals,
): string {
  return JSON.stringify(
    GetLastActivityTimestampByAddressesV2Globals$outboundSchema.parse(
      getLastActivityTimestampByAddressesV2Globals,
    ),
  );
}
export function getLastActivityTimestampByAddressesV2GlobalsFromJSON(
  jsonString: string,
): SafeParseResult<
  GetLastActivityTimestampByAddressesV2Globals,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetLastActivityTimestampByAddressesV2Globals$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetLastActivityTimestampByAddressesV2Globals' from JSON`,
  );
}

/** @internal */
export const GetLastActivityTimestampByAddressesV2Request$inboundSchema:
  z.ZodType<
    GetLastActivityTimestampByAddressesV2Request,
    z.ZodTypeDef,
    unknown
  > = z.object({
    blockchainId: components.BlockchainId$inboundSchema,
    network: components.GlobalParamNetwork$inboundSchema.optional(),
    minUtxoAmount: z.number().optional(),
    PrimaryNetworkAddressesBodyDto:
      components.PrimaryNetworkAddressesBodyDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "PrimaryNetworkAddressesBodyDto": "primaryNetworkAddressesBodyDto",
    });
  });
/** @internal */
export type GetLastActivityTimestampByAddressesV2Request$Outbound = {
  blockchainId: string;
  network?: string | undefined;
  minUtxoAmount?: number | undefined;
  PrimaryNetworkAddressesBodyDto:
    components.PrimaryNetworkAddressesBodyDto$Outbound;
};

/** @internal */
export const GetLastActivityTimestampByAddressesV2Request$outboundSchema:
  z.ZodType<
    GetLastActivityTimestampByAddressesV2Request$Outbound,
    z.ZodTypeDef,
    GetLastActivityTimestampByAddressesV2Request
  > = z.object({
    blockchainId: components.BlockchainId$outboundSchema,
    network: components.GlobalParamNetwork$outboundSchema.optional(),
    minUtxoAmount: z.number().optional(),
    primaryNetworkAddressesBodyDto:
      components.PrimaryNetworkAddressesBodyDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      primaryNetworkAddressesBodyDto: "PrimaryNetworkAddressesBodyDto",
    });
  });

export function getLastActivityTimestampByAddressesV2RequestToJSON(
  getLastActivityTimestampByAddressesV2Request:
    GetLastActivityTimestampByAddressesV2Request,
): string {
  return JSON.stringify(
    GetLastActivityTimestampByAddressesV2Request$outboundSchema.parse(
      getLastActivityTimestampByAddressesV2Request,
    ),
  );
}
export function getLastActivityTimestampByAddressesV2RequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetLastActivityTimestampByAddressesV2Request,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetLastActivityTimestampByAddressesV2Request$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetLastActivityTimestampByAddressesV2Request' from JSON`,
  );
}

/** @internal */
export const GetLastActivityTimestampByAddressesV2Response$inboundSchema:
  z.ZodType<
    GetLastActivityTimestampByAddressesV2Response,
    z.ZodTypeDef,
    unknown
  > = components.LastActivityTimestamp$inboundSchema;
/** @internal */
export type GetLastActivityTimestampByAddressesV2Response$Outbound =
  components.LastActivityTimestamp$Outbound;

/** @internal */
export const GetLastActivityTimestampByAddressesV2Response$outboundSchema:
  z.ZodType<
    GetLastActivityTimestampByAddressesV2Response$Outbound,
    z.ZodTypeDef,
    GetLastActivityTimestampByAddressesV2Response
  > = components.LastActivityTimestamp$outboundSchema;

export function getLastActivityTimestampByAddressesV2ResponseToJSON(
  getLastActivityTimestampByAddressesV2Response:
    GetLastActivityTimestampByAddressesV2Response,
): string {
  return JSON.stringify(
    GetLastActivityTimestampByAddressesV2Response$outboundSchema.parse(
      getLastActivityTimestampByAddressesV2Response,
    ),
  );
}
export function getLastActivityTimestampByAddressesV2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetLastActivityTimestampByAddressesV2Response,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetLastActivityTimestampByAddressesV2Response$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetLastActivityTimestampByAddressesV2Response' from JSON`,
  );
}
