/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetMetricsBySubnetIdServerList = [
  "https://metrics.avax.network",
] as const;

/**
 * Which metric to fetch for given subnet ID.
 */
export const GetMetricsBySubnetIdMetric = {
  PerSubnetDailyFeesPaid: "perSubnetDailyFeesPaid",
  PerSubnetCumulativeFeesPaid: "perSubnetCumulativeFeesPaid",
  PerSubnetPayingValidators: "perSubnetPayingValidators",
} as const;
/**
 * Which metric to fetch for given subnet ID.
 */
export type GetMetricsBySubnetIdMetric = ClosedEnum<
  typeof GetMetricsBySubnetIdMetric
>;

export type GetMetricsBySubnetIdRequest = {
  /**
   * Which metric to fetch for given subnet ID.
   */
  metric: GetMetricsBySubnetIdMetric;
  /**
   * Query param for retrieving items after a specific timestamp.
   */
  startTimestamp?: number | undefined;
  /**
   * Query param for retrieving items before a specific timestamp.
   */
  endTimestamp?: number | undefined;
  /**
   * The subnet ID to filter by.
   */
  subnetId: string;
};

/** @internal */
export const GetMetricsBySubnetIdMetric$inboundSchema: z.ZodNativeEnum<
  typeof GetMetricsBySubnetIdMetric
> = z.nativeEnum(GetMetricsBySubnetIdMetric);
/** @internal */
export const GetMetricsBySubnetIdMetric$outboundSchema: z.ZodNativeEnum<
  typeof GetMetricsBySubnetIdMetric
> = GetMetricsBySubnetIdMetric$inboundSchema;

/** @internal */
export const GetMetricsBySubnetIdRequest$inboundSchema: z.ZodType<
  GetMetricsBySubnetIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  metric: GetMetricsBySubnetIdMetric$inboundSchema,
  startTimestamp: z.number().int().optional(),
  endTimestamp: z.number().int().optional(),
  subnetId: z.string(),
});
/** @internal */
export type GetMetricsBySubnetIdRequest$Outbound = {
  metric: string;
  startTimestamp?: number | undefined;
  endTimestamp?: number | undefined;
  subnetId: string;
};

/** @internal */
export const GetMetricsBySubnetIdRequest$outboundSchema: z.ZodType<
  GetMetricsBySubnetIdRequest$Outbound,
  z.ZodTypeDef,
  GetMetricsBySubnetIdRequest
> = z.object({
  metric: GetMetricsBySubnetIdMetric$outboundSchema,
  startTimestamp: z.number().int().optional(),
  endTimestamp: z.number().int().optional(),
  subnetId: z.string(),
});

export function getMetricsBySubnetIdRequestToJSON(
  getMetricsBySubnetIdRequest: GetMetricsBySubnetIdRequest,
): string {
  return JSON.stringify(
    GetMetricsBySubnetIdRequest$outboundSchema.parse(
      getMetricsBySubnetIdRequest,
    ),
  );
}
export function getMetricsBySubnetIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMetricsBySubnetIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMetricsBySubnetIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMetricsBySubnetIdRequest' from JSON`,
  );
}
