/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetTotalL1ValidatorMetricsServerList = [
  "https://metrics.avax.network",
] as const;

/**
 * Which network level metric to fetch for L1 validator.
 */
export const GetTotalL1ValidatorMetricsMetric = {
  TotalCumulativeFeesDaily: "totalCumulativeFeesDaily",
  TotalValidatorFeesDaily: "totalValidatorFeesDaily",
  TotalPayingValidatorsDaily: "totalPayingValidatorsDaily",
} as const;
/**
 * Which network level metric to fetch for L1 validator.
 */
export type GetTotalL1ValidatorMetricsMetric = ClosedEnum<
  typeof GetTotalL1ValidatorMetricsMetric
>;

export type GetTotalL1ValidatorMetricsRequest = {
  /**
   * Which network level metric to fetch for L1 validator.
   */
  metric: GetTotalL1ValidatorMetricsMetric;
  /**
   * Query param for retrieving items after a specific timestamp.
   */
  startTimestamp?: number | undefined;
  /**
   * Query param for retrieving items before a specific timestamp.
   */
  endTimestamp?: number | undefined;
};

/** @internal */
export const GetTotalL1ValidatorMetricsMetric$inboundSchema: z.ZodNativeEnum<
  typeof GetTotalL1ValidatorMetricsMetric
> = z.nativeEnum(GetTotalL1ValidatorMetricsMetric);
/** @internal */
export const GetTotalL1ValidatorMetricsMetric$outboundSchema: z.ZodNativeEnum<
  typeof GetTotalL1ValidatorMetricsMetric
> = GetTotalL1ValidatorMetricsMetric$inboundSchema;

/** @internal */
export const GetTotalL1ValidatorMetricsRequest$inboundSchema: z.ZodType<
  GetTotalL1ValidatorMetricsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  metric: GetTotalL1ValidatorMetricsMetric$inboundSchema,
  startTimestamp: z.number().int().optional(),
  endTimestamp: z.number().int().optional(),
});
/** @internal */
export type GetTotalL1ValidatorMetricsRequest$Outbound = {
  metric: string;
  startTimestamp?: number | undefined;
  endTimestamp?: number | undefined;
};

/** @internal */
export const GetTotalL1ValidatorMetricsRequest$outboundSchema: z.ZodType<
  GetTotalL1ValidatorMetricsRequest$Outbound,
  z.ZodTypeDef,
  GetTotalL1ValidatorMetricsRequest
> = z.object({
  metric: GetTotalL1ValidatorMetricsMetric$outboundSchema,
  startTimestamp: z.number().int().optional(),
  endTimestamp: z.number().int().optional(),
});

export function getTotalL1ValidatorMetricsRequestToJSON(
  getTotalL1ValidatorMetricsRequest: GetTotalL1ValidatorMetricsRequest,
): string {
  return JSON.stringify(
    GetTotalL1ValidatorMetricsRequest$outboundSchema.parse(
      getTotalL1ValidatorMetricsRequest,
    ),
  );
}
export function getTotalL1ValidatorMetricsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTotalL1ValidatorMetricsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTotalL1ValidatorMetricsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTotalL1ValidatorMetricsRequest' from JSON`,
  );
}
