/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListAutoRenewedValidatorCyclesServerList = [
  "https://data-api.avax.network",
] as const;

export type ListAutoRenewedValidatorCyclesGlobals = {
  /**
   * A supported network type mainnet or testnet/fuji.
   */
  network?: components.GlobalParamNetwork | undefined;
};

export type ListAutoRenewedValidatorCyclesRequest = {
  /**
   * Restrict results to a single auto-renewed position, given its `AddAutoRenewedValidatorTx` hash. Only needed for a node that has held more than one auto-renewed validation, where `cycleIndex` restarts at 1 per position.
   */
  txHash?: string | undefined;
  /**
   * A page token, received from a previous list call. Provide this to retrieve the subsequent page.
   */
  pageToken?: string | undefined;
  /**
   * The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
   */
  pageSize?: number | undefined;
  /**
   * Either mainnet or testnet/fuji.
   */
  network?: components.GlobalParamNetwork | undefined;
  /**
   * A primary network (P or X chain) nodeId.
   */
  nodeId: string;
  /**
   * The order by which to sort results. Use "asc" for ascending order, "desc" for descending order. Sorted by timestamp or the `sortBy` query parameter, if provided.
   */
  sortOrder?: components.SortOrder | undefined;
};

export type ListAutoRenewedValidatorCyclesResponse = {
  result: components.ListAutoRenewedCyclesResponse;
};

/** @internal */
export const ListAutoRenewedValidatorCyclesGlobals$inboundSchema: z.ZodType<
  ListAutoRenewedValidatorCyclesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  network: components.GlobalParamNetwork$inboundSchema.optional(),
});
/** @internal */
export type ListAutoRenewedValidatorCyclesGlobals$Outbound = {
  network?: string | undefined;
};

/** @internal */
export const ListAutoRenewedValidatorCyclesGlobals$outboundSchema: z.ZodType<
  ListAutoRenewedValidatorCyclesGlobals$Outbound,
  z.ZodTypeDef,
  ListAutoRenewedValidatorCyclesGlobals
> = z.object({
  network: components.GlobalParamNetwork$outboundSchema.optional(),
});

export function listAutoRenewedValidatorCyclesGlobalsToJSON(
  listAutoRenewedValidatorCyclesGlobals: ListAutoRenewedValidatorCyclesGlobals,
): string {
  return JSON.stringify(
    ListAutoRenewedValidatorCyclesGlobals$outboundSchema.parse(
      listAutoRenewedValidatorCyclesGlobals,
    ),
  );
}
export function listAutoRenewedValidatorCyclesGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListAutoRenewedValidatorCyclesGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAutoRenewedValidatorCyclesGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAutoRenewedValidatorCyclesGlobals' from JSON`,
  );
}

/** @internal */
export const ListAutoRenewedValidatorCyclesRequest$inboundSchema: z.ZodType<
  ListAutoRenewedValidatorCyclesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  txHash: z.string().optional(),
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
  network: components.GlobalParamNetwork$inboundSchema.optional(),
  nodeId: z.string(),
  sortOrder: components.SortOrder$inboundSchema.optional(),
});
/** @internal */
export type ListAutoRenewedValidatorCyclesRequest$Outbound = {
  txHash?: string | undefined;
  pageToken?: string | undefined;
  pageSize: number;
  network?: string | undefined;
  nodeId: string;
  sortOrder?: string | undefined;
};

/** @internal */
export const ListAutoRenewedValidatorCyclesRequest$outboundSchema: z.ZodType<
  ListAutoRenewedValidatorCyclesRequest$Outbound,
  z.ZodTypeDef,
  ListAutoRenewedValidatorCyclesRequest
> = z.object({
  txHash: z.string().optional(),
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
  network: components.GlobalParamNetwork$outboundSchema.optional(),
  nodeId: z.string(),
  sortOrder: components.SortOrder$outboundSchema.optional(),
});

export function listAutoRenewedValidatorCyclesRequestToJSON(
  listAutoRenewedValidatorCyclesRequest: ListAutoRenewedValidatorCyclesRequest,
): string {
  return JSON.stringify(
    ListAutoRenewedValidatorCyclesRequest$outboundSchema.parse(
      listAutoRenewedValidatorCyclesRequest,
    ),
  );
}
export function listAutoRenewedValidatorCyclesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAutoRenewedValidatorCyclesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAutoRenewedValidatorCyclesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAutoRenewedValidatorCyclesRequest' from JSON`,
  );
}

/** @internal */
export const ListAutoRenewedValidatorCyclesResponse$inboundSchema: z.ZodType<
  ListAutoRenewedValidatorCyclesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ListAutoRenewedCyclesResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListAutoRenewedValidatorCyclesResponse$Outbound = {
  Result: components.ListAutoRenewedCyclesResponse$Outbound;
};

/** @internal */
export const ListAutoRenewedValidatorCyclesResponse$outboundSchema: z.ZodType<
  ListAutoRenewedValidatorCyclesResponse$Outbound,
  z.ZodTypeDef,
  ListAutoRenewedValidatorCyclesResponse
> = z.object({
  result: components.ListAutoRenewedCyclesResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listAutoRenewedValidatorCyclesResponseToJSON(
  listAutoRenewedValidatorCyclesResponse:
    ListAutoRenewedValidatorCyclesResponse,
): string {
  return JSON.stringify(
    ListAutoRenewedValidatorCyclesResponse$outboundSchema.parse(
      listAutoRenewedValidatorCyclesResponse,
    ),
  );
}
export function listAutoRenewedValidatorCyclesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAutoRenewedValidatorCyclesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListAutoRenewedValidatorCyclesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAutoRenewedValidatorCyclesResponse' from JSON`,
  );
}
