/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListContractDeploymentsServerList = [
  "https://data-api.avax.network",
] as const;

export type ListContractDeploymentsGlobals = {
  /**
   * A supported EVM chain id, chain alias, or blockchain id.
   */
  chainId?: string | undefined;
};

export type ListContractDeploymentsRequest = {
  /**
   * A page token, received from a previous list call. Provide this to retrieve the subsequent page.
   */
  pageToken?: string | undefined;
  /**
   * The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
   */
  pageSize?: number | undefined;
  /**
   * A supported evm chain id or blockchain id. Use the `/chains` endpoint to get a list of supported chain ids.
   */
  chainId?: string | undefined;
  /**
   * A wallet address.
   */
  address: string;
};

export type ListContractDeploymentsResponse = {
  result: components.ListContractsResponse;
};

/** @internal */
export const ListContractDeploymentsGlobals$inboundSchema: z.ZodType<
  ListContractDeploymentsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainId: z.string().optional(),
});
/** @internal */
export type ListContractDeploymentsGlobals$Outbound = {
  chainId?: string | undefined;
};

/** @internal */
export const ListContractDeploymentsGlobals$outboundSchema: z.ZodType<
  ListContractDeploymentsGlobals$Outbound,
  z.ZodTypeDef,
  ListContractDeploymentsGlobals
> = z.object({
  chainId: z.string().optional(),
});

export function listContractDeploymentsGlobalsToJSON(
  listContractDeploymentsGlobals: ListContractDeploymentsGlobals,
): string {
  return JSON.stringify(
    ListContractDeploymentsGlobals$outboundSchema.parse(
      listContractDeploymentsGlobals,
    ),
  );
}
export function listContractDeploymentsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListContractDeploymentsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContractDeploymentsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContractDeploymentsGlobals' from JSON`,
  );
}

/** @internal */
export const ListContractDeploymentsRequest$inboundSchema: z.ZodType<
  ListContractDeploymentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
  chainId: z.string().optional(),
  address: z.string(),
});
/** @internal */
export type ListContractDeploymentsRequest$Outbound = {
  pageToken?: string | undefined;
  pageSize: number;
  chainId?: string | undefined;
  address: string;
};

/** @internal */
export const ListContractDeploymentsRequest$outboundSchema: z.ZodType<
  ListContractDeploymentsRequest$Outbound,
  z.ZodTypeDef,
  ListContractDeploymentsRequest
> = z.object({
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
  chainId: z.string().optional(),
  address: z.string(),
});

export function listContractDeploymentsRequestToJSON(
  listContractDeploymentsRequest: ListContractDeploymentsRequest,
): string {
  return JSON.stringify(
    ListContractDeploymentsRequest$outboundSchema.parse(
      listContractDeploymentsRequest,
    ),
  );
}
export function listContractDeploymentsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListContractDeploymentsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContractDeploymentsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContractDeploymentsRequest' from JSON`,
  );
}

/** @internal */
export const ListContractDeploymentsResponse$inboundSchema: z.ZodType<
  ListContractDeploymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ListContractsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListContractDeploymentsResponse$Outbound = {
  Result: components.ListContractsResponse$Outbound;
};

/** @internal */
export const ListContractDeploymentsResponse$outboundSchema: z.ZodType<
  ListContractDeploymentsResponse$Outbound,
  z.ZodTypeDef,
  ListContractDeploymentsResponse
> = z.object({
  result: components.ListContractsResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listContractDeploymentsResponseToJSON(
  listContractDeploymentsResponse: ListContractDeploymentsResponse,
): string {
  return JSON.stringify(
    ListContractDeploymentsResponse$outboundSchema.parse(
      listContractDeploymentsResponse,
    ),
  );
}
export function listContractDeploymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListContractDeploymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContractDeploymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContractDeploymentsResponse' from JSON`,
  );
}
