/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListLatestTransactionsServerList = [
  "https://data-api.avax.network",
] as const;

export type ListLatestTransactionsGlobals = {
  /**
   * A supported EVM chain id, chain alias, or blockchain id.
   */
  chainId?: string | undefined;
};

export type ListLatestTransactionsRequest = {
  /**
   * A page token, received from a previous list call. Provide this to retrieve the subsequent page.
   */
  pageToken?: string | undefined;
  /**
   * The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 100.
   */
  pageSize?: number | undefined;
  /**
   * A supported evm chain id or blockchain id. Use the `/chains` endpoint to get a list of supported chain ids.
   */
  chainId?: string | undefined;
  /**
   * A status filter for listed transactions.
   */
  status?: components.TransactionStatus | undefined;
};

export type ListLatestTransactionsResponse = {
  result: components.ListNativeTransactionsResponse;
};

/** @internal */
export const ListLatestTransactionsGlobals$inboundSchema: z.ZodType<
  ListLatestTransactionsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainId: z.string().optional(),
});
/** @internal */
export type ListLatestTransactionsGlobals$Outbound = {
  chainId?: string | undefined;
};

/** @internal */
export const ListLatestTransactionsGlobals$outboundSchema: z.ZodType<
  ListLatestTransactionsGlobals$Outbound,
  z.ZodTypeDef,
  ListLatestTransactionsGlobals
> = z.object({
  chainId: z.string().optional(),
});

export function listLatestTransactionsGlobalsToJSON(
  listLatestTransactionsGlobals: ListLatestTransactionsGlobals,
): string {
  return JSON.stringify(
    ListLatestTransactionsGlobals$outboundSchema.parse(
      listLatestTransactionsGlobals,
    ),
  );
}
export function listLatestTransactionsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListLatestTransactionsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLatestTransactionsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLatestTransactionsGlobals' from JSON`,
  );
}

/** @internal */
export const ListLatestTransactionsRequest$inboundSchema: z.ZodType<
  ListLatestTransactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
  chainId: z.string().optional(),
  status: components.TransactionStatus$inboundSchema.optional(),
});
/** @internal */
export type ListLatestTransactionsRequest$Outbound = {
  pageToken?: string | undefined;
  pageSize: number;
  chainId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const ListLatestTransactionsRequest$outboundSchema: z.ZodType<
  ListLatestTransactionsRequest$Outbound,
  z.ZodTypeDef,
  ListLatestTransactionsRequest
> = z.object({
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(10),
  chainId: z.string().optional(),
  status: components.TransactionStatus$outboundSchema.optional(),
});

export function listLatestTransactionsRequestToJSON(
  listLatestTransactionsRequest: ListLatestTransactionsRequest,
): string {
  return JSON.stringify(
    ListLatestTransactionsRequest$outboundSchema.parse(
      listLatestTransactionsRequest,
    ),
  );
}
export function listLatestTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListLatestTransactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLatestTransactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLatestTransactionsRequest' from JSON`,
  );
}

/** @internal */
export const ListLatestTransactionsResponse$inboundSchema: z.ZodType<
  ListLatestTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ListNativeTransactionsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListLatestTransactionsResponse$Outbound = {
  Result: components.ListNativeTransactionsResponse$Outbound;
};

/** @internal */
export const ListLatestTransactionsResponse$outboundSchema: z.ZodType<
  ListLatestTransactionsResponse$Outbound,
  z.ZodTypeDef,
  ListLatestTransactionsResponse
> = z.object({
  result: components.ListNativeTransactionsResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listLatestTransactionsResponseToJSON(
  listLatestTransactionsResponse: ListLatestTransactionsResponse,
): string {
  return JSON.stringify(
    ListLatestTransactionsResponse$outboundSchema.parse(
      listLatestTransactionsResponse,
    ),
  );
}
export function listLatestTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListLatestTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLatestTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLatestTransactionsResponse' from JSON`,
  );
}
