/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListBlockchainsServerList = [
  "https://data-api.avax.network",
] as const;

export type ListBlockchainsGlobals = {
  /**
   * A supported network type mainnet or testnet/fuji.
   */
  network?: components.GlobalParamNetwork | undefined;
};

export type ListBlockchainsRequest = {
  /**
   * A page token, received from a previous list call. Provide this to retrieve the subsequent page.
   */
  pageToken?: string | undefined;
  /**
   * The maximum number of items to return. The minimum page size is 1. The maximum pageSize is 10000.
   */
  pageSize?: number | undefined;
  /**
   * Either mainnet or testnet/fuji.
   */
  network?: components.GlobalParamNetwork | undefined;
  /**
   * The order by which to sort results. Use "asc" for ascending order, "desc" for descending order. Sorted by timestamp or the `sortBy` query parameter, if provided.
   */
  sortOrder?: components.SortOrder | undefined;
};

export type ListBlockchainsResponse = {
  result: components.ListBlockchainsResponse;
};

/** @internal */
export const ListBlockchainsGlobals$inboundSchema: z.ZodType<
  ListBlockchainsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  network: components.GlobalParamNetwork$inboundSchema.optional(),
});
/** @internal */
export type ListBlockchainsGlobals$Outbound = {
  network?: string | undefined;
};

/** @internal */
export const ListBlockchainsGlobals$outboundSchema: z.ZodType<
  ListBlockchainsGlobals$Outbound,
  z.ZodTypeDef,
  ListBlockchainsGlobals
> = z.object({
  network: components.GlobalParamNetwork$outboundSchema.optional(),
});

export function listBlockchainsGlobalsToJSON(
  listBlockchainsGlobals: ListBlockchainsGlobals,
): string {
  return JSON.stringify(
    ListBlockchainsGlobals$outboundSchema.parse(listBlockchainsGlobals),
  );
}
export function listBlockchainsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListBlockchainsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBlockchainsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBlockchainsGlobals' from JSON`,
  );
}

/** @internal */
export const ListBlockchainsRequest$inboundSchema: z.ZodType<
  ListBlockchainsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(100),
  network: components.GlobalParamNetwork$inboundSchema.optional(),
  sortOrder: components.SortOrder$inboundSchema.optional(),
});
/** @internal */
export type ListBlockchainsRequest$Outbound = {
  pageToken?: string | undefined;
  pageSize: number;
  network?: string | undefined;
  sortOrder?: string | undefined;
};

/** @internal */
export const ListBlockchainsRequest$outboundSchema: z.ZodType<
  ListBlockchainsRequest$Outbound,
  z.ZodTypeDef,
  ListBlockchainsRequest
> = z.object({
  pageToken: z.string().optional(),
  pageSize: z.number().int().default(100),
  network: components.GlobalParamNetwork$outboundSchema.optional(),
  sortOrder: components.SortOrder$outboundSchema.optional(),
});

export function listBlockchainsRequestToJSON(
  listBlockchainsRequest: ListBlockchainsRequest,
): string {
  return JSON.stringify(
    ListBlockchainsRequest$outboundSchema.parse(listBlockchainsRequest),
  );
}
export function listBlockchainsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListBlockchainsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBlockchainsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBlockchainsRequest' from JSON`,
  );
}

/** @internal */
export const ListBlockchainsResponse$inboundSchema: z.ZodType<
  ListBlockchainsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ListBlockchainsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListBlockchainsResponse$Outbound = {
  Result: components.ListBlockchainsResponse$Outbound;
};

/** @internal */
export const ListBlockchainsResponse$outboundSchema: z.ZodType<
  ListBlockchainsResponse$Outbound,
  z.ZodTypeDef,
  ListBlockchainsResponse
> = z.object({
  result: components.ListBlockchainsResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listBlockchainsResponseToJSON(
  listBlockchainsResponse: ListBlockchainsResponse,
): string {
  return JSON.stringify(
    ListBlockchainsResponse$outboundSchema.parse(listBlockchainsResponse),
  );
}
export function listBlockchainsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListBlockchainsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBlockchainsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBlockchainsResponse' from JSON`,
  );
}
