name: Client SDK CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build:all

      - name: Run tests
        working-directory: client
        run: npm run test

  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build:all

      - name: Run coverage tests
        working-directory: client
        run: npm run test:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report
          path: client/coverage
          retention-days: 7
