name: Publish Client SDK

on:
  push:
    tags:
      - "client/v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0)"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Set version
        id: set_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            TAG_NAME=${GITHUB_REF#refs/tags/}
            VERSION=${TAG_NAME#client/v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          VERSION=${{ steps.set_version.outputs.version }}
          cd client
          npm version "$VERSION" --no-git-tag-version --allow-same-version
          npm run update-version

      - name: Install dependencies
        run: |
          cd client
          npm install
          npm run build:all --if-present

      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish package
        run: |
          cd client
          npm publish --access public
